# -*- coding: utf-8 -*-
"""
build_aa_unit3.py
Constructs Unit 3: Symmetric Groups, Alternating Groups & Group Actions
"""

def get_unit3():
    u3 = {
        "number": 3,
        "title": "Symmetric Groups, Alternating Groups & Group Actions",
        "leadSummary": "Symmetric group S_n, cycle notation, cycle decomposition theorem, transpositions, the sign homomorphism sgn(σ), alternating groups A_n, Dihedral groups D_{2n}, group actions on sets, orbits, stabilizers, Orbit-Stabilizer theorem, and Burnside's Lemma (Frobenius counting formula).",
        "simulations": ["sim_aa_permutation_orbits"],
        "sections": [
            {
                "secNumber": "3.1",
                "title": "Symmetric Groups S_n, Permutations & Disjoint Cycle Decomposition",
                "content": r"""### 1. The Symmetric Group $S_n$

Let $X = \{1, 2, \dots, n\}$ be a finite set of $n$ symbols.

> **Definition 3.1 (Permutation & Symmetric Group):**
> A **permutation** of $X$ is a bijection $\sigma: X \to X$.
> The set of all permutations of $X$, equipped with functional composition $\circ$, forms the **Symmetric Group of Degree $n$**, denoted by $S_n$.
> The order of $S_n$ is:
> $$|S_n| = n!$$

#### Two-Line Notation:
A permutation $\sigma \in S_n$ is traditionally displayed as:
$$\sigma = \begin{pmatrix} 1 & 2 & 3 & \dots & n \\ \sigma(1) & \sigma(2) & \sigma(3) & \dots & \sigma(n) \end{pmatrix}$$

---

### 2. Cycle Notation and Disjoint Cycles

> **Definition 3.2 ($k$-Cycle):**
> A permutation $\sigma \in S_n$ is called a **cycle of length $k$** (or **$k$-cycle**), denoted by $(a_1 \; a_2 \; \dots \; a_k)$, if:
> $$\sigma(a_1) = a_2, \quad \sigma(a_2) = a_3, \quad \dots, \quad \sigma(a_{k-1}) = a_k, \quad \sigma(a_k) = a_1$$
> and $\sigma(x) = x$ for all $x \notin \{a_1, a_2, \dots, a_k\}$.
> A 2-cycle $(a \; b)$ is called a **transposition**.

#### Definition 3.3 (Disjoint Cycles):
Two cycles $(a_1 \; \dots \; a_k)$ and $(b_1 \; \dots \; b_m)$ are **disjoint** if they have no elements in common:
$$\{a_1, \dots, a_k\} \cap \{b_1, \dots, b_m\} = \emptyset$$

#### Proposition 3.1 (Commutativity of Disjoint Cycles):
Disjoint cycles in $S_n$ commute:
$$\text{If } \sigma \text{ and } \tau \text{ are disjoint, then } \sigma \tau = \tau \sigma$$
*Proof:* If $x$ is moved by $\sigma$, it is fixed by $\tau$, so $\tau(\sigma(x)) = \sigma(x) = \sigma(\tau(x))$. If $x$ is fixed by both, both sides leave $x$ unchanged. $\blacksquare$

---

### 3. The Disjoint Cycle Decomposition Theorem

> **Theorem 3.1 (Cycle Decomposition Theorem):**
> Every permutation $\sigma \in S_n$ can be written uniquely (up to the order of factors) as a product of pairwise disjoint cycles.

#### Theorem 3.2 (Order of a Permutation):
The order of a permutation $\sigma \in S_n$ written in disjoint cycle form $\sigma = c_1 c_2 \dots c_r$ is the least common multiple of the lengths of its cycles:
$$|\sigma| = \text{lcm}(\text{length}(c_1), \, \text{length}(c_2), \, \dots, \, \text{length}(c_r))$$"""
            },
            {
                "secNumber": "3.2",
                "title": "Transpositions, Parity Homomorphism & Alternating Groups A_n",
                "content": r"""### 1. Transposition Factorization

Any $k$-cycle can be expressed as a product of 2-cycles (transpositions):
$$(a_1 \; a_2 \; a_3 \; \dots \; a_k) = (a_1 \; a_k)(a_1 \; a_{k-1}) \dots (a_1 \; a_3)(a_1 \; a_2)$$
Notice that a $k$-cycle decomposes into $(k - 1)$ transpositions.

> **Corollary 3.1:**
> Every permutation $\sigma \in S_n$ can be expressed as a product of transpositions.
> *(The symmetric group $S_n$ is generated by transpositions!)*

---

### 2. The Parity Theorem & The Sign Function $\text{sgn}(\sigma)$

While the decomposition into transpositions is not unique (e.g. $(1 \; 2) = (1 \; 2)(1 \; 3)(1 \; 3)$), the **parity of the number of transpositions is invariant**!

> **Theorem 3.3 (Parity Invariance Theorem):**
> If a permutation $\sigma \in S_n$ can be written as a product of $r$ transpositions and also as a product of $s$ transpositions:
> $$\sigma = \tau_1 \tau_2 \dots \tau_r = \tau_1' \tau_2' \dots \tau_s'$$
> then $r$ and $s$ have the same parity:
> $$r \equiv s \pmod 2$$

#### Definition 3.4 (Even and Odd Permutations):
- A permutation $\sigma \in S_n$ is **Even** if it can be written as a product of an even number of transpositions.
- A permutation $\sigma \in S_n$ is **Odd** if it can be written as a product of an odd number of transpositions.

The **Sign (Signature) Homomorphism** $\text{sgn}: S_n \to (\{+1, -1\}, \cdot)$ is:
$$\text{sgn}(\sigma) = \begin{cases} +1 & \text{if } \sigma \text{ is even} \\ -1 & \text{if } \sigma \text{ is odd} \end{cases}$$
satisfying $\text{sgn}(\sigma \tau) = \text{sgn}(\sigma) \cdot \text{sgn}(\tau)$.

---

### 3. The Alternating Group $A_n$

> **Definition 3.5 (Alternating Group):**
> The set of all even permutations of $S_n$ forms a normal subgroup called the **Alternating Group of Degree $n$**, denoted by $A_n$:
> $$A_n = \ker(\text{sgn}) = \{ \sigma \in S_n : \text{sgn}(\sigma) = +1 \}$$

#### Theorem 3.4 (Order of $A_n$):
For $n \ge 2$:
$$|A_n| = \frac{n!}{2}$$
*Proof:* The map $\text{sgn}: S_n \to \{\pm 1\}$ is a surjective group homomorphism. By the First Isomorphism Theorem:
$$S_n / A_n \cong \{\pm 1\} \implies [S_n : A_n] = 2 \implies |A_n| = \frac{|S_n|}{2} = \frac{n!}{2} \quad \blacksquare$$

> **Theorem 3.5 (Simplicity of $A_n$):**
> The alternating group $A_n$ is a **simple group** (contains no non-trivial proper normal subgroups) for all $n \ge 5$.
> *(This theorem is the Galois-theoretic cornerstone establishing the insolvability of the quintic by radicals!)*"""
            },
            {
                "secNumber": "3.3",
                "title": "Dihedral Groups D_2n, Geometric Symmetries & Group Presentations",
                "content": r"""### 1. Geometric Symmetries of Regular Polygons

The **Dihedral Group** $D_{2n}$ (also denoted $D_n$) is the group of all rigid planar symmetries (rotations and reflections) of a regular $n$-gon.
The group has order:
$$|D_{2n}| = 2n$$
consisting of:
- $n$ planar rotations: $R_k = \frac{2\pi k}{n}$ for $k = 0, 1, \dots, n-1$.
- $n$ planar reflections across symmetry axes: $s, sr, sr^2, \dots, sr^{n-1}$.

---

### 2. Group Presentation of $D_{2n}$

The group $D_{2n}$ is completely generated by two elements:
- $r$: Counterclockwise rotation by $2\pi/n$ (order $n$).
- $s$: Reflection across an axis passing through a vertex (order 2).

> **Theorem 3.6 (Presentation of $D_{2n}$):**
> $$D_{2n} = \langle r, s \mid r^n = 1, \; s^2 = 1, \; s r s = r^{-1} \rangle$$
> The fundamental relation $s r = r^{-1} s = r^{n-1} s$ allows any word in $\{r, s\}$ to be reduced into canonical form:
> $$D_{2n} = \{ r^k s^j : 0 \le k < n, \; j \in \{0, 1\} \}$$"""
            },
            {
                "secNumber": "3.4",
                "title": "Group Actions on Sets, Orbit-Stabilizer Theorem & Burnside's Lemma",
                "content": r"""### 1. Formal Definition of a Group Action

> **Definition 3.6 (Group Action):**
> Let $G$ be a group and $X$ a non-empty set. A **group action** of $G$ on $X$ is a map $\cdot: G \times X \to X$ satisfying:
> 1. **Identity:** $e \cdot x = x, \quad \forall x \in X$.
> 2. **Compatibility / Associativity:** $(g_1 g_2) \cdot x = g_1 \cdot (g_2 \cdot x), \quad \forall g_1, g_2 \in G, \; x \in X$.
> We write $G \curvearrowright X$ to denote $G$ acting on $X$.

---

### 2. Orbits and Stabilizers

Let $G \curvearrowright X$ and $x \in X$.

#### Definition 3.7 (Orbit):
The **orbit** of $x$, denoted by $\text{Orb}(x)$ or $G \cdot x$, is the set of all elements in $X$ to which $x$ can be moved by elements of $G$:
$$\text{Orb}(x) = \{ g \cdot x : g \in G \} \subseteq X$$
The orbits form an **equivalence partition** of the set $X$: $X = \coprod \text{Orb}(x)$.

#### Definition 3.8 (Stabilizer / Isotropy Subgroup):
The **stabilizer** of $x$, denoted by $\text{Stab}(x)$ or $G_x$, is the set of elements in $G$ that fix $x$:
$$\text{Stab}(x) = \{ g \in G : g \cdot x = x \} \le G$$
*Proposition:* $\text{Stab}(x)$ is a subgroup of $G$ for every $x \in X$.

---

### 3. The Orbit-Stabilizer Theorem

> **Theorem 3.7 (The Orbit-Stabilizer Theorem):**
> Let $G$ be a finite group acting on a set $X$. For every $x \in X$:
> $$|G| = |\text{Orb}(x)| \cdot |\text{Stab}(x)|$$
> Equivalently:
> $$|\text{Orb}(x)| = [G : \text{Stab}(x)]$$

#### Complete Proof:
Let $H = \text{Stab}(x) \le G$. Let $G / H$ denote the set of left cosets $\{g H : g \in G\}$.
Define the map $f: G / H \to \text{Orb}(x)$ by:
$$f(g H) = g \cdot x$$
1. **Well-Definedness and Injectivity:**
   $$\begin{aligned}
   g_1 H = g_2 H &\iff g_2^{-1} g_1 \in H = \text{Stab}(x) \\
   &\iff (g_2^{-1} g_1) \cdot x = x \\
   &\iff g_2^{-1} \cdot (g_1 \cdot x) = x \\
   &\iff g_1 \cdot x = g_2 \cdot x \\
   &\iff f(g_1 H) = f(g_2 H)
   \end{aligned}$$
   This chain of equivalences proves that $f$ is both **well-defined** (left to right) and **injective** (right to left).
2. **Surjectivity:**
   Any element in $\text{Orb}(x)$ has the form $y = g \cdot x = f(g H)$, so $f$ is surjective.
Thus $f$ is a bijection between $G/H$ and $\text{Orb}(x)$.
Therefore $|\text{Orb}(x)| = |G/H| = [G : H] = \frac{|G|}{|H|} = \frac{|G|}{|\text{Stab}(x)|}$.
Multiplying by $|\text{Stab}(x)|$ yields $|G| = |\text{Orb}(x)| \cdot |\text{Stab}(x)|$. $\blacksquare$

---

### 4. Burnside's Lemma (Frobenius Counting Formula)

Let $X^g = \{ x \in X : g \cdot x = x \}$ denote the set of elements fixed by $g \in G$.

> **Theorem 3.8 (Burnside's Lemma / Cauchy-Frobenius Theorem):**
> The number of distinct orbits $N$ of a finite group $G$ acting on a finite set $X$ is the average number of fixed points:
> $$N = |X / G| = \frac{1}{|G|} \sum_{g \in G} |X^g|$$"""
            }
        ],
        "problems": [
            {
                "tier": "Foundational",
                "title": "Cycle Decomposition, Parity and Inverses in S_8",
                "statement": r"Consider the permutations in $S_8$: $$\sigma = \begin{pmatrix} 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 \\ 3 & 5 & 7 & 8 & 1 & 6 & 4 & 2 \end{pmatrix}, \quad \tau = (1 \; 4 \; 7)(2 \; 8)(3 \; 6 \; 5)$$ 1. Write $\sigma$ as a product of disjoint cycles. 2. Compute the order $|\sigma|$ and parity $\text{sgn}(\sigma)$. 3. Compute the product $\sigma \tau$ in disjoint cycle form, and determine if $\sigma \tau \in A_8$.",
                "hints": [
                    "Follow the trajectory: $1 \\to 3 \\to 7 \\to 4 \\to 8 \\to 2 \\to 5 \\to 1$.",
                    "Order is $\\text{lcm}$ of cycle lengths; parity is $(-1)^{n - k}$ where $k$ is the number of cycles."
                ],
                "solution": r"""**Step 1: Disjoint Cycle Decomposition of $\sigma$**
Trace the orbits:
- Start with $1$: $1 \to 3 \to 7 \to 4 \to 8 \to 2 \to 5 \to 1$.
  This forms a cycle of length 7: $(1 \; 3 \; 7 \; 4 \; 8 \; 2 \; 5)$.
- Check remaining element $6$: $\sigma(6) = 6$ (fixed point).
Thus, the disjoint cycle decomposition is:
$$\sigma = (1 \; 3 \; 7 \; 4 \; 8 \; 2 \; 5)$$

---

**Step 2: Order and Parity of $\sigma$**
- **Order:** $|\sigma| = 7$ (length of the single disjoint cycle).
- **Parity:** A cycle of length $k$ decomposes into $k - 1$ transpositions:
  $$\sigma = (1 \; 5)(1 \; 2)(1 \; 8)(1 \; 4)(1 \; 7)(1 \; 3)$$
  Number of transpositions = $7 - 1 = 6$ (even number).
  Therefore:
  $$\text{sgn}(\sigma) = +1 \implies \sigma \in A_8 \text{ (Even permutation)}$$

---

**Step 3: Compute $\sigma \tau$**
Given $\tau = (1 \; 4 \; 7)(2 \; 8)(3 \; 6 \; 5)$.
Compose $\sigma \circ \tau$ from right to left:
- $1 \stackrel{\tau}{\to} 4 \stackrel{\sigma}{\to} 8$
- $8 \stackrel{\tau}{\to} 2 \stackrel{\sigma}{\to} 5$
- $5 \stackrel{\tau}{\to} 3 \stackrel{\sigma}{\to} 7$
- $7 \stackrel{\tau}{\to} 1 \stackrel{\sigma}{\to} 3$
- $3 \stackrel{\tau}{\to} 6 \stackrel{\sigma}{\to} 6$
- $6 \stackrel{\tau}{\to} 5 \stackrel{\sigma}{\to} 1$
This closes the cycle: $(1 \; 8 \; 5 \; 7 \; 3 \; 6)$.
Now check the remaining elements $\{2, 4\}$:
- $2 \stackrel{\tau}{\to} 8 \stackrel{\sigma}{\to} 2$ (fixed point)
- $4 \stackrel{\tau}{\to} 7 \stackrel{\sigma}{\to} 4$ (fixed point)

Therefore:
$$\sigma \tau = (1 \; 8 \; 5 \; 7 \; 3 \; 6)$$
Cycle length is 6.
Parity of a 6-cycle: $6 - 1 = 5$ transpositions (odd).
Therefore $\text{sgn}(\sigma \tau) = -1$, which means:
$$\sigma \tau \notin A_8 \quad (\sigma \tau \text{ is Odd})$$"""
            },
            {
                "tier": "Advanced",
                "title": "Combinatorial Coloring via Burnside's Lemma (Frobenius Formula)",
                "statement": r"A necklace is made of 6 beads arranged in a circle. Each bead can be colored using one of 3 colors (Red, Blue, Green). Two necklaces are considered identical if one can be obtained from the other by a rotation in the plane. 1. Identify the group $G$ acting on the set of $3^6 = 729$ colorings. 2. For each element $g \in G$, compute the number of fixed colorings $|X^g|$. 3. Apply Burnside's Lemma to calculate the exact number of distinct necklaces.",
                "hints": [
                    "The rotation group of a 6-bead necklace is the cyclic group $C_6 = \\mathbb{Z}_6$.",
                    "For a rotation $r^k$, the beads are partitioned into cycles of length $|r^k|$; each cycle must have the same color."
                ],
                "solution": r"""**Step 1: Group Action Formulation**
Let $X$ be the set of all colored bead configurations:
$$|X| = 3^6 = 729$$
The rotational symmetry group of the necklace is the cyclic group $G = C_6 = \{R_0, R_1, R_2, R_3, R_4, R_5\}$, where $R_k$ represents a clockwise rotation by $k \times 60^\circ$.
$|G| = 6$.

---

**Step 2: Fixed Point Analysis for Each $g \in G$**
For a coloring to be fixed by a rotation $R_k$, all beads in each disjoint cycle of $R_k$ must share the same color. If $R_k$ decomposes into $c(R_k)$ cycles, the number of fixed colorings is:
$$|X^{R_k}| = 3^{c(R_k)}$$

1. **$R_0$ (Identity, $0^\circ$ rotation):**
   Disjoint cycles: $(1)(2)(3)(4)(5)(6) \implies c(R_0) = 6$.
   $$|X^{R_0}| = 3^6 = 729$$

2. **$R_1$ ($60^\circ$ rotation):**
   Full cycle of length 6: $(1 \; 2 \; 3 \; 4 \; 5 \; 6) \implies c(R_1) = 1$.
   $$|X^{R_1}| = 3^1 = 3$$

3. **$R_2$ ($120^\circ$ rotation):**
   Two cycles of length 3: $(1 \; 3 \; 5)(2 \; 4 \; 6) \implies c(R_2) = 2$.
   $$|X^{R_2}| = 3^2 = 9$$

4. **$R_3$ ($180^\circ$ rotation):**
   Three cycles of length 2: $(1 \; 4)(2 \; 5)(3 \; 6) \implies c(R_3) = 3$.
   $$|X^{R_3}| = 3^3 = 27$$

5. **$R_4$ ($240^\circ$ rotation):**
   Two cycles of length 3: $(1 \; 5 \; 3)(2 \; 6 \; 4) \implies c(R_4) = 2$.
   $$|X^{R_4}| = 3^2 = 9$$

6. **$R_5$ ($300^\circ$ rotation):**
   Full cycle of length 6: $(1 \; 6 \; 5 \; 4 \; 3 \; 2) \implies c(R_5) = 1$.
   $$|X^{R_5}| = 3^1 = 3$$

---

**Step 3: Burnside's Lemma Summation**
Sum of fixed points:
$$\sum_{g \in G} |X^g| = 729 + 3 + 9 + 27 + 9 + 3 = 780$$
Applying Burnside's Lemma:
$$N = \frac{1}{|G|} \sum_{g \in G} |X^g| = \frac{780}{6} = 130$$
There are exactly **130** distinct non-equivalent 3-colored necklaces."""
            },
            {
                "tier": "Rigorous Examination / Derivation",
                "title": "Complete Proof of the Orbit-Stabilizer Theorem and Burnside's Lemma",
                "statement": r"1. For any action of a finite group $G$ on a finite set $X$, prove that the orbits form an equivalence partition of $X$. 2. Prove that the map $\psi: G/\text{Stab}(x) \to \text{Orb}(x)$ given by $\psi(g \text{Stab}(x)) = g \cdot x$ is a well-defined bijection, establishing $|G| = |\text{Orb}(x)| \cdot |\text{Stab}(x)|$. 3. Using double-counting of the set $S = \{(g, x) \in G \times X : g \cdot x = x\}$, derive Burnside's Lemma: $$|X/G| = \frac{1}{|G|} \sum_{g \in G} |X^g|$$",
                "hints": [
                    "For Part 1, define $x \\sim y \\iff \\exists g \\in G \\text{ with } g \\cdot x = y$ and verify equivalence axioms.",
                    "For Part 3, evaluate $\\sum_{g \\in G} |X^g|$ and $\\sum_{x \\in X} |\\text{Stab}(x)|$."
                ],
                "solution": r"""**Part 1: Proof that Orbits Partition $X$**
Define the relation $\sim$ on $X$ by:
$$x \sim y \iff \exists g \in G \text{ such that } g \cdot x = y$$
- **Reflexivity:** $e \cdot x = x \implies x \sim x$.
- **Symmetry:** If $x \sim y$, then $g \cdot x = y \implies x = g^{-1} \cdot y \implies y \sim x$ (since $g^{-1} \in G$).
- **Transitivity:** If $x \sim y$ and $y \sim z$, then $g_1 \cdot x = y$ and $g_2 \cdot y = z$.
  Then $z = g_2 \cdot (g_1 \cdot x) = (g_2 g_1) \cdot x$.
  Since $g_2 g_1 \in G$, $x \sim z$.
Hence $\sim$ is an equivalence relation. The equivalence classes are the orbits $\text{Orb}(x)$, which partition $X$. $\blacksquare$

---

**Part 2: Proof of the Orbit-Stabilizer Bijection**
Let $H = \text{Stab}(x) = \{ h \in G : h \cdot x = x \}$.
Define $\psi: G/H \to \text{Orb}(x)$ by $\psi(g H) = g \cdot x$.
- **Well-defined and Injective:**
  $$g_1 H = g_2 H \iff g_2^{-1} g_1 \in H \iff (g_2^{-1} g_1) \cdot x = x \iff g_1 \cdot x = g_2 \cdot x \iff \psi(g_1 H) = \psi(g_2 H)$$
  This proves simultaneously that $\psi$ is well-defined ($\implies$) and injective ($\impliedby$).
- **Surjective:** For any $y \in \text{Orb}(x)$, $y = g \cdot x = \psi(g H)$ for some $g \in G$.
Hence $\psi$ is a bijection, establishing:
$$|\text{Orb}(x)| = [G : H] = \frac{|G|}{|H|} = \frac{|G|}{|\text{Stab}(x)|} \implies |G| = |\text{Orb}(x)| \cdot |\text{Stab}(x)| \quad \blacksquare$$

---

**Part 3: Derivation of Burnside's Lemma via Double Counting**
Define the incidence set:
$$S = \{ (g, x) \in G \times X : g \cdot x = x \}$$
Count the cardinality of $S$ in two ways:
1. **Summing over $g \in G$:**
   $$|S| = \sum_{g \in G} |\{ x \in X : g \cdot x = x \}| = \sum_{g \in G} |X^g|$$
2. **Summing over $x \in X$:**
   $$|S| = \sum_{x \in X} |\{ g \in G : g \cdot x = x \}| = \sum_{x \in X} |\text{Stab}(x)|$$
Equating the two expressions:
$$\sum_{g \in G} |X^g| = \sum_{x \in X} |\text{Stab}(x)|$$
By the Orbit-Stabilizer theorem, $|\text{Stab}(x)| = \frac{|G|}{|\text{Orb}(x)|}$. Substituting:
$$\sum_{g \in G} |X^g| = \sum_{x \in X} \frac{|G|}{|\text{Orb}(x)|} = |G| \sum_{x \in X} \frac{1}{|\text{Orb}(x)|}$$
Since the orbits partition $X$, group the sum over distinct orbits $\mathcal{O} \in X/G$:
$$\sum_{x \in X} \frac{1}{|\text{Orb}(x)|} = \sum_{\mathcal{O} \in X/G} \sum_{x \in \mathcal{O}} \frac{1}{|\mathcal{O}|} = \sum_{\mathcal{O} \in X/G} |\mathcal{O}| \cdot \frac{1}{|\mathcal{O}|} = \sum_{\mathcal{O} \in X/G} 1 = |X/G|$$
Therefore:
$$\sum_{g \in G} |X^g| = |G| \cdot |X/G| \implies |X/G| = \frac{1}{|G|} \sum_{g \in G} |X^g| \quad \blacksquare$$"""
            }
        ]
    }
    return u3

if __name__ == "__main__":
    u = get_unit3()
    print("Unit 3 generated successfully:", u["title"])
    print("Sections:", len(u["sections"]))
    print("Problems:", len(u["problems"]))
