# -*- coding: utf-8 -*-
"""
build_pde_unit6.py
Constructs Unit 6: Elliptic Boundary Value Problems: Laplace & Poisson Equations and Harmonic Functions
Strictly ZERO course numbers.
"""

def get_unit6():
    u6 = {
        "number": 6,
        "title": "Elliptic Boundary Value Problems: Laplace & Poisson Equations and Harmonic Functions",
        "leadSummary": "Comprehensive theory of elliptic potential equations in mathematical physics: derivations from electrostatics, Newtonian gravitation, steady-state heat conduction, and irrotational fluid flow, properties of harmonic functions including the Mean Value Property, Strong Maximum Principle, and Liouville's theorem, separation of variables on rectangular, circular, and annular geometries, the Poisson integral representation formula for disks and half-planes, and variational Dirichlet principles with energy uniqueness proofs.",
        "simulations": ["sim_pde_laplace_harmonic_potential"],
        "sections": [
            {
                "secNumber": "6.1",
                "title": "Physical Derivations: Electrostatics, Gravitation, Steady Heat & Fluid Flow",
                "content": r"""### 1. The Universal Role of Elliptic Potential Equations

Elliptic partial differential equations govern time-independent, equilibrium, and steady-state phenomena throughout physics and engineering. The premier models are:
- **Laplace's Equation (Homogeneous Potential):** $\nabla^2 u = 0$
- **Poisson's Equation (Inhomogeneous Potential with Sources):** $\nabla^2 u = f(\mathbf{x})$
Solutions $u$ of Laplace's equation in an open set $\Omega \subset \mathbb{R}^n$ are termed **harmonic functions**.

---

### 2. Physical Manifestations

#### 1. Electrostatics (Maxwell's Equations)
In electrostatic equilibrium, Faraday's law $\nabla \times \mathbf{E} = \mathbf{0}$ implies the electric field is conservative, represented as the negative gradient of an electrostatic scalar potential $\Phi$:
$$\mathbf{E} = -\nabla \Phi$$
Gauss's law in differential form relates electric flux to charge density $\rho(\mathbf{x})$:
$$\nabla \cdot \mathbf{E} = \frac{\rho}{\epsilon_0} \implies \nabla \cdot (-\nabla \Phi) = \frac{\rho}{\epsilon_0} \implies \nabla^2 \Phi = -\frac{\rho(\mathbf{x})}{\epsilon_0}$$
In charge-free vacuum ($\rho = 0$), the electrostatic potential satisfies **Laplace's equation** $\nabla^2 \Phi = 0$.

#### 2. Newtonian Gravitation
The gravitational field $\mathbf{g} = -\nabla V_g$ generated by a mass density distribution $\mu(\mathbf{x})$ obeys Gauss's law for gravity $\nabla \cdot \mathbf{g} = -4\pi G \mu$, leading directly to Poisson's equation:
$$\nabla^2 V_g = 4\pi G \mu(\mathbf{x})$$

#### 3. Steady-State Heat Conduction
When a conducting medium reaches thermal equilibrium ($u_t = 0$), the heat equation $\rho c_p u_t = k \nabla^2 u + Q$ reduces to:
$$\nabla^2 u = -\frac{Q(\mathbf{x})}{k}$$
If no internal heat generation occurs ($Q = 0$), the steady temperature field satisfies $\nabla^2 u = 0$.

#### 4. Irrotational Incompressible Fluid Flow (Potential Flow)
For an ideal fluid with zero vorticity ($\nabla \times \mathbf{v} = \mathbf{0}$), there exists a velocity potential $\phi$ such that $\mathbf{v} = \nabla \phi$. Incompressibility requires $\nabla \cdot \mathbf{v} = 0$, giving:
$$\nabla \cdot (\nabla \phi) = \nabla^2 \phi = 0$$"""
            },
            {
                "secNumber": "6.2",
                "title": "Properties of Harmonic Functions: Mean Value Property & Maximum Principle",
                "content": r"""### 1. The Mean Value Property (MVP)

> **Theorem 6.1 (Gauss's Mean Value Property for Harmonic Functions):**
> Let $u \in C^2(\Omega)$ be harmonic in an open domain $\Omega \subseteq \mathbb{R}^n$.
> For any ball $B_R(\mathbf{x}_0) = \{ \mathbf{x} : \|\mathbf{x} - \mathbf{x}_0\| < R \} \subset \subset \Omega$:
> 1. **Spherical Mean Value Property:** The value at the center is the average over the boundary sphere:
>    $$u(\mathbf{x}_0) = \frac{1}{\omega_n R^{n-1}} \int_{\partial B_R(\mathbf{x}_0)} u(\mathbf{y})\,dS_y$$
>    In $\mathbb{R}^2$ ($n = 2$): $u(x_0, y_0) = \frac{1}{2\pi} \int_0^{2\pi} u(x_0 + R\cos\theta, y_0 + R\sin\theta)\,d\theta$.
> 2. **Ball Mean Value Property:** The value at the center is the volume average over the solid ball:
>    $$u(\mathbf{x}_0) = \frac{n}{\omega_n R^n} \int_{B_R(\mathbf{x}_0)} u(\mathbf{y})\,d\mathbf{y}$$

*Proof:*
Fix $\mathbf{x}_0 \in \Omega$ and define for $0 < r < R$:
$$\phi(r) = \frac{1}{\omega_n r^{n-1}}\int_{\partial B_r(\mathbf{x}_0)} u(\mathbf{y})\,dS_y = \frac{1}{\omega_n} \int_{|\mathbf{z}|=1} u(\mathbf{x}_0 + r\mathbf{z})\,dS_z$$
Differentiating with respect to $r$ under the integral sign:
$$\phi'(r) = \frac{1}{\omega_n} \int_{|\mathbf{z}|=1} \nabla u(\mathbf{x}_0 + r\mathbf{z}) \cdot \mathbf{z}\,dS_z = \frac{1}{\omega_n r^{n-1}} \int_{\partial B_r(\mathbf{x}_0)} \frac{\partial u}{\partial \mathbf{n}}\,dS_y$$
By Green's first identity (Divergence Theorem):
$$\int_{\partial B_r(\mathbf{x}_0)} \frac{\partial u}{\partial \mathbf{n}}\,dS_y = \int_{B_r(\mathbf{x}_0)} \nabla^2 u\,d\mathbf{y}$$
Since $u$ is harmonic, $\nabla^2 u = 0$, so $\phi'(r) = 0$ for all $r \in (0, R)$.
Thus $\phi(r)$ is constant. Taking the limit as $r \to 0^+$:
$$\lim_{r \to 0^+} \phi(r) = u(\mathbf{x}_0)$$
Hence $\phi(R) = u(\mathbf{x}_0)$.
Integrating $r^{n-1}\phi(r)$ from $0$ to $R$ immediately yields the solid ball average. $\blacksquare$

---

### 2. The Strong Maximum Principle

> **Theorem 6.2 (Strong Maximum Principle for Harmonic Functions):**
> Let $\Omega \subset \mathbb{R}^n$ be a connected open domain (a region). If $u \in C^2(\Omega)$ is harmonic and attains its global maximum (or minimum) at an interior point $\mathbf{x}_0 \in \Omega$, then $u$ is identically constant throughout $\Omega$.

*Proof:*
Let $M = \sup_\Omega u$. Suppose there exists $\mathbf{x}_0 \in \Omega$ such that $u(\mathbf{x}_0) = M$.
Consider the set:
$$E = \{ \mathbf{x} \in \Omega : u(\mathbf{x}) = M \}$$
1. Since $u$ is continuous, $E = u^{-1}(\{M\})$ is **closed** in $\Omega$.
2. We show $E$ is **open** in $\Omega$:
   Let $\mathbf{y} \in E$. Since $\Omega$ is open, choose $r > 0$ such that $B_r(\mathbf{y}) \subset \Omega$.
   By the Ball Mean Value Property:
   $$M = u(\mathbf{y}) = \frac{1}{|B_r|} \int_{B_r(\mathbf{y})} u(\mathbf{z})\,d\mathbf{z}$$
   $$0 = \frac{1}{|B_r|} \int_{B_r(\mathbf{y})} [M - u(\mathbf{z})]\,d\mathbf{z}$$
   Since $M$ is the global maximum, $M - u(\mathbf{z}) \ge 0$ everywhere.
   The integral of a continuous non-negative function vanishes if and only if the integrand is identically zero:
   $$M - u(\mathbf{z}) = 0 \implies u(\mathbf{z}) = M \quad \forall \mathbf{z} \in B_r(\mathbf{y})$$
   Thus $B_r(\mathbf{y}) \subseteq E$, so $E$ is open!
Since $\Omega$ is connected and $E$ is non-empty, open, and closed in $\Omega$, topological connectedness forces $E = \Omega$.
Therefore, $u(\mathbf{x}) \equiv M$ everywhere in $\Omega$. $\blacksquare$

---

### 3. Liouville's Theorem for Harmonic Functions

> **Theorem 6.3 (Liouville's Theorem):**
> If $u: \mathbb{R}^n \to \mathbb{R}$ is harmonic on the entire space $\mathbb{R}^n$ and bounded ($|u(\mathbf{x})| \le M$ for all $\mathbf{x} \in \mathbb{R}^n$), then $u$ is constant."""
            },
            {
                "secNumber": "6.3",
                "title": "Dirichlet & Neumann Problems on Rectangles and Circular Domains",
                "content": r"""### 1. Dirichlet Problem on a Rectangle $[0, a] \times [0, b]$

Consider steady-state temperature on a rectangular plate with three edges grounded at zero and top edge at potential $f(x)$:
$$\begin{cases}
u_{xx} + u_{yy} = 0, & 0 < x < a, \quad 0 < y < b \\
u(0, y) = 0, \quad u(a, y) = 0, & 0 \le y \le b \\
u(x, 0) = 0, \quad u(x, b) = f(x), & 0 \le x \le a
\end{cases}$$
Separating variables $u(x, y) = X(x) Y(y)$:
$$\frac{X''(x)}{X(x)} = -\frac{Y''(y)}{Y(y)} = -\lambda$$
- Spatial ODE in $x$: $X'' + \lambda X = 0, X(0) = X(a) = 0 \implies \lambda_n = (n\pi/a)^2, X_n(x) = \sin\left(\frac{n\pi x}{a}\right)$.
- ODE in $y$: $Y_n''(y) - \left(\frac{n\pi}{a}\right)^2 Y_n(y) = 0, Y_n(0) = 0 \implies Y_n(y) = \sinh\left(\frac{n\pi y}{a}\right)$.
General solution:
$$u(x, y) = \sum_{n=1}^\infty c_n \sin\left(\frac{n\pi x}{a}\right) \sinh\left(\frac{n\pi y}{a}\right)$$
At $y = b$:
$$f(x) = \sum_{n=1}^\infty \left[ c_n \sinh\left(\frac{n\pi b}{a}\right) \right] \sin\left(\frac{n\pi x}{a}\right)$$
Therefore:
$$c_n = \frac{2}{a \sinh\left(\frac{n\pi b}{a}\right)} \int_0^a f(x) \sin\left(\frac{n\pi x}{a}\right)\,dx$$

---

### 2. Dirichlet Problem in Polar Coordinates for the Disk

In polar coordinates $(r, \theta)$, Laplace's equation is:
$$\nabla^2 u = \frac{\partial^2 u}{\partial r^2} + \frac{1}{r}\frac{\partial u}{\partial r} + \frac{1}{r^2}\frac{\partial^2 u}{\partial \theta^2} = 0$$
Inside a disk of radius $R$ with boundary condition $u(R, \theta) = h(\theta)$:
Separating variables $u(r, \theta) = R(r) \Theta(\theta)$:
$$\frac{r^2 R'' + r R'}{R} = -\frac{\Theta''}{\Theta} = n^2 \quad (n \in \{0, 1, 2, \dots\})$$
- Angular equation: $\Theta_n(\theta) = A_n \cos(n\theta) + B_n \sin(n\theta)$ (by $2\pi$-periodicity).
- Radial equation (Euler-Cauchy): $r^2 R'' + r R' - n^2 R = 0$.
  Solutions are $R(r) = C r^n + D r^{-n}$.
  Since the solution must be bounded at the origin $r = 0$, we must set $D = 0$ for all $n \ge 0$.
Thus, the general series solution inside the disk is:
$$u(r, \theta) = \frac{a_0}{2} + \sum_{n=1}^\infty \left(\frac{r}{R}\right)^n \left[ a_n \cos(n\theta) + b_n \sin(n\theta) \right]$$
where $a_n, b_n$ are the standard Fourier coefficients of the boundary function $h(\theta)$."""
            },
            {
                "secNumber": "6.4",
                "title": "The Poisson Integral Formula for the Disk and Half-Plane",
                "content": r"""### 1. Summation of the Fourier Series into an Integral Kernel

Substitute the Fourier coefficient formulas into the disk series solution:
$$a_n = \frac{1}{\pi}\int_0^{2\pi} h(\phi) \cos(n\phi)\,d\phi, \qquad b_n = \frac{1}{\pi}\int_0^{2\pi} h(\phi) \sin(n\phi)\,d\phi$$
Exchanging summation and integration:
$$u(r, \theta) = \frac{1}{2\pi}\int_0^{2\pi} h(\phi) \left[ 1 + 2\sum_{n=1}^\infty \left(\frac{r}{R}\right)^n [\cos(n\theta)\cos(n\phi) + \sin(n\theta)\sin(n\phi)] \right] d\phi$$
Using the cosine subtraction identity:
$$u(r, \theta) = \frac{1}{2\pi}\int_0^{2\pi} h(\phi) \left[ 1 + 2\sum_{n=1}^\infty \left(\frac{r}{R}\right)^n \cos(n(\theta - \phi)) \right] d\phi$$

Summing the geometric series using Euler's identity:
Let $\rho = r/R < 1$ and $\psi = \theta - \phi$.
$$S = 1 + 2\sum_{n=1}^\infty \rho^n \cos(n\psi) = 1 + \sum_{n=1}^\infty \rho^n (e^{in\psi} + e^{-in\psi}) = -1 + \sum_{n=0}^\infty (\rho e^{i\psi})^n + \sum_{n=0}^\infty (\rho e^{-i\psi})^n$$
Using the sum of geometric series $\sum_{n=0}^\infty z^n = \frac{1}{1 - z}$:
$$S = -1 + \frac{1}{1 - \rho e^{i\psi}} + \frac{1}{1 - \rho e^{-i\psi}} = \frac{1 - \rho^2}{1 - 2\rho \cos\psi + \rho^2}$$
Restoring $\rho = r/R$:
$$S = \frac{1 - (r/R)^2}{1 - 2(r/R)\cos(\theta - \phi) + (r/R)^2} = \frac{R^2 - r^2}{R^2 - 2Rr\cos(\theta - \phi) + r^2}$$

> **Theorem 6.4 (Poisson Integral Formula for the Disk):**
> For any continuous boundary profile $h(\phi)$ on $\partial B_R$, the unique harmonic function in $B_R$ is given by:
> $$u(r, \theta) = \frac{1}{2\pi}\int_0^{2\pi} \frac{R^2 - r^2}{R^2 - 2Rr\cos(\theta - \phi) + r^2} h(\phi)\,d\phi, \qquad 0 \le r < R$$
> The kernel $P(r, \theta; R, \phi) = \frac{R^2 - r^2}{R^2 - 2Rr\cos(\theta - \phi) + r^2}$ is the **Poisson Kernel** for the disk.

---

### 2. Poisson Integral Formula for the Upper Half-Plane

For the upper half-plane $y > 0$ with boundary condition $u(x, 0) = f(x)$ on the real axis $\mathbb{R}$:
$$u(x, y) = \frac{y}{\pi} \int_{-\infty}^\infty \frac{f(s)}{(x - s)^2 + y^2}\,ds$$
where $P_y(x - s) = \frac{y}{\pi[(x - s)^2 + y^2]}$ is the Cauchy distribution / Poisson kernel for the half-plane."""
            },
            {
                "secNumber": "6.5",
                "title": "Well-Posedness of Elliptic BVPs: Dirichlet Principle & Energy Methods",
                "content": r"""### 1. Dirichlet Energy Functional and Dirichlet's Principle

Let $\Omega \subset \mathbb{R}^n$ be a bounded domain with smooth boundary $\partial \Omega$.
Consider the space of functions $V = \{ w \in C^1(\bar{\Omega}) : w|_{\partial\Omega} = g \}$.
Define the **Dirichlet energy functional**:
$$E[w] = \frac{1}{2}\int_\Omega \|\nabla w\|^2\,d\mathbf{x} = \frac{1}{2}\int_\Omega \sum_{i=1}^n \left(\frac{\partial w}{\partial x_i}\right)^2 d\mathbf{x}$$

> **Theorem 6.5 (Dirichlet's Principle):**
> A function $u \in V$ minimizes the energy functional $E[w]$ over all candidate functions in $V$ if and only if $u$ is harmonic in $\Omega$:
> $$\nabla^2 u = 0 \quad \text{in } \Omega$$

*Proof:*
Let $u \in V$ be harmonic. For any other function $w \in V$, let $v = w - u$.
Then $v \in C^1(\bar{\Omega})$ and $v|_{\partial\Omega} = g - g = 0$.
Now evaluate $E[w] = E[u + v]$:
$$E[u + v] = \frac{1}{2}\int_\Omega \|\nabla u + \nabla v\|^2\,d\mathbf{x} = \frac{1}{2}\int_\Omega \|\nabla u\|^2\,d\mathbf{x} + \int_\Omega \nabla u \cdot \nabla v\,d\mathbf{x} + \frac{1}{2}\int_\Omega \|\nabla v\|^2\,d\mathbf{x}$$
$$E[u + v] = E[u] + E[v] + \int_\Omega \nabla u \cdot \nabla v\,d\mathbf{x}$$
Applying Green's First Identity to the cross term:
$$\int_\Omega \nabla u \cdot \nabla v\,d\mathbf{x} = \int_{\partial\Omega} v \frac{\partial u}{\partial \mathbf{n}}\,dA - \int_\Omega v \nabla^2 u\,d\mathbf{x}$$
1. On the boundary $\partial\Omega$, $v = 0$, so the surface integral vanishes.
2. In the interior, $\nabla^2 u = 0$ since $u$ is harmonic.
Thus the cross term vanishes identically!
$$E[w] = E[u] + \frac{1}{2}\int_\Omega \|\nabla v\|^2\,d\mathbf{x} \ge E[u]$$
Equality holds if and only if $\|\nabla v\| = 0 \implies v = \text{constant}$.
Since $v = 0$ on $\partial\Omega$, $v \equiv 0 \implies w = u$.
Therefore, the harmonic function $u$ is the **unique global minimizer** of Dirichlet energy. $\blacksquare$

---

### 2. Uniqueness of the Neumann Boundary Value Problem

For the Neumann problem:
$$\begin{cases} \nabla^2 u = 0 & \text{in } \Omega \\ \frac{\partial u}{\partial \mathbf{n}} = h & \text{on } \partial\Omega \end{cases}$$
1. **Compatibility Condition:** By the Divergence Theorem:
   $$\int_{\partial\Omega} h\,dA = \int_{\partial\Omega} \frac{\partial u}{\partial \mathbf{n}}\,dA = \int_\Omega \nabla^2 u\,d\mathbf{x} = 0$$
   A solution exists if and only if the total boundary flux integrates to zero.
2. **Uniqueness up to an Additive Constant:**
   If $u_1$ and $u_2$ are solutions, $w = u_1 - u_2$ satisfies $\nabla^2 w = 0$ and $\frac{\partial w}{\partial\mathbf{n}} = 0$.
   By Green's identity:
   $$\int_\Omega \|\nabla w\|^2\,d\mathbf{x} = \int_{\partial\Omega} w \frac{\partial w}{\partial\mathbf{n}}\,dA - \int_\Omega w \nabla^2 w\,d\mathbf{x} = 0 - 0 = 0$$
   Thus $\nabla w = \mathbf{0} \implies w(\mathbf{x}) = C$. Solutions are unique up to an arbitrary additive constant."""
            }
        ],
        "problems": [
            {
                "tier": "Foundational",
                "title": "Dirichlet Problem on a Square Plate with Constant Edge Temperature",
                "statement": r"""Solve Laplace's equation $\nabla^2 u = 0$ on the square plate $0 < x < \pi, 0 < y < \pi$ with boundary conditions:
$$u(0, y) = 0, \quad u(\pi, y) = 0, \quad u(x, 0) = 0, \quad u(x, \pi) = T_0$$
where $T_0 > 0$ is a constant. Find the exact temperature at the center of the plate $(\pi/2, \pi/2)$.""",
                "solution": r"""### 1. Separation of Variables
Following Section 6.3, the general solution satisfying the three homogeneous boundaries is:
$$u(x, y) = \sum_{n=1}^\infty c_n \sin(nx) \sinh(ny)$$
At the top edge $y = \pi$:
$$u(x, \pi) = \sum_{n=1}^\infty [c_n \sinh(n\pi)] \sin(nx) = T_0, \qquad 0 < x < \pi$$

---

### 2. Determining Fourier Coefficients
The Fourier sine coefficients of the constant function $T_0$ on $[0, \pi]$ are:
$$b_n = \frac{2}{\pi}\int_0^\pi T_0 \sin(nx)\,dx = \frac{2T_0}{\pi}\left[ -\frac{\cos(nx)}{n} \right]_0^\pi = \frac{2T_0}{n\pi}[1 - (-1)^n]$$
- If $n$ is even: $b_n = 0$.
- If $n$ is odd ($n = 2k - 1$): $b_{2k-1} = \frac{4T_0}{(2k-1)\pi}$.

Equating $c_n \sinh(n\pi) = b_n$:
$$c_{2k-1} = \frac{4T_0}{(2k-1)\pi \sinh((2k-1)\pi)}$$

The complete series solution is:
$$u(x, y) = \frac{4T_0}{\pi} \sum_{k=1}^\infty \frac{\sin((2k-1)x) \sinh((2k-1)y)}{(2k-1)\sinh((2k-1)\pi)}$$

---

### 3. Temperature at the Center $(\pi/2, \pi/2)$
By fourfold symmetry of Laplace's equation on a square with three edges at 0 and one edge at $T_0$, the center temperature must be exactly:
$$u(\pi/2, \pi/2) = \frac{T_0}{4}$$
Let us verify this via the series:
At $x = \pi/2$: $\sin((2k-1)\pi/2) = (-1)^{k-1}$.
At $y = \pi/2$: $\sinh((2k-1)\pi/2)$.
Using the hyperbolic identity $\sinh(2\theta) = 2\sinh(\theta)\cosh(\theta)$, with $\theta = (2k-1)\pi/2$:
$$\frac{\sinh(\theta)}{\sinh(2\theta)} = \frac{1}{2\cosh(\theta)} = \frac{1}{2\cosh((2k-1)\pi/2)}$$
Thus:
$$u(\pi/2, \pi/2) = \frac{4T_0}{\pi} \sum_{k=1}^\infty \frac{(-1)^{k-1}}{2(2k-1)\cosh((2k-1)\pi/2)} = \frac{2T_0}{\pi} \sum_{k=1}^\infty \frac{(-1)^{k-1}}{(2k-1)\cosh((2k-1)\pi/2)} = \frac{T_0}{4} \approx 0.25 T_0$$
The symmetry deduction is confirmed. $\blacksquare$"""
            },
            {
                "tier": "Advanced",
                "title": "Dirichlet Problem in the Unit Disk with Quadratic Boundary Data",
                "statement": r"""Find the harmonic function $u(r, \theta)$ inside the unit disk $r \le 1$ satisfying Laplace's equation $\nabla^2 u = 0$ with boundary condition:
$$u(1, \theta) = \cos^2\theta, \qquad 0 \le \theta < 2\pi$$
1. Solve using separation of variables.
2. Verify the solution using the Poisson Integral Formula.
3. Express the solution in Cartesian coordinates $(x, y)$.""",
                "solution": r"""### 1. Separation of Variables
On the boundary $r = 1$:
$$h(\theta) = \cos^2\theta = \frac{1 + \cos(2\theta)}{2} = \frac{1}{2} + \frac{1}{2}\cos(2\theta)$$
The general series solution inside the unit disk ($R = 1$) is:
$$u(r, \theta) = \frac{a_0}{2} + \sum_{n=1}^\infty r^n [a_n \cos(n\theta) + b_n \sin(n\theta)]$$
Comparing directly with $h(\theta)$:
- $\frac{a_0}{2} = \frac{1}{2} \implies a_0 = 1$
- For $n = 2$: $a_2 = \frac{1}{2}$
- All other coefficients $a_n = 0$ ($n \ne 0, 2$) and $b_n = 0$ for all $n$.

Therefore, the exact solution inside the disk is:
$$u(r, \theta) = \frac{1}{2} + \frac{1}{2} r^2 \cos(2\theta)$$

---

### 2. Verification via Poisson Integral Formula
The Poisson integral formula for $R = 1$ gives at the center $r = 0$:
$$u(0, 0) = \frac{1}{2\pi}\int_0^{2\pi} \cos^2\phi\,d\phi = \frac{1}{2\pi} (\pi) = \frac{1}{2}$$
From our series: $u(0, \theta) = \frac{1}{2} + 0 = \frac{1}{2}$, matching the Mean Value Property.

---

### 3. Conversion to Cartesian Coordinates
Recall polar coordinates $x = r\cos\theta, y = r\sin\theta$.
Using the trigonometric identity $\cos(2\theta) = \cos^2\theta - \sin^2\theta$:
$$r^2 \cos(2\theta) = r^2(\cos^2\theta - \sin^2\theta) = (r\cos\theta)^2 - (r\sin\theta)^2 = x^2 - y^2$$
Substituting into $u(r, \theta)$:
$$u(x, y) = \frac{1}{2} + \frac{1}{2}(x^2 - y^2)$$
Check harmonicity directly in Cartesian coordinates:
$$u_{xx} = \frac{1}{2}(2) = 1, \qquad u_{yy} = \frac{1}{2}(-2) = -1$$
$$\nabla^2 u = u_{xx} + u_{yy} = 1 + (-1) = 0 \quad \checkmark$$
Check boundary on the unit circle $x^2 + y^2 = 1 \implies y^2 = 1 - x^2$:
$$u(x, y) = \frac{1}{2} + \frac{1}{2}(x^2 - (1 - x^2)) = \frac{1}{2} + \frac{1}{2}(2x^2 - 1) = x^2 = \cos^2\theta \quad \checkmark$$
The Cartesian expression is $u(x, y) = \frac{1}{2}(1 + x^2 - y^2)$. $\blacksquare$"""
            },
            {
                "tier": "Honors Challenge",
                "title": "Mean Value Property Proof and Interior Extrema Prohibition",
                "statement": r"""Let $\Omega \subset \mathbb{R}^2$ be a bounded domain and let $u \in C^2(\Omega) \cap C(\bar{\Omega})$ be harmonic ($\nabla^2 u = 0$).
1. Rigorously prove that for any disk $B_R(x_0, y_0) \subset \Omega$, $u(x_0, y_0) = \frac{1}{2\pi}\int_0^{2\pi} u(x_0 + R\cos\theta, y_0 + R\sin\theta)\,d\theta$.
2. Prove that if $u$ attains a local maximum at an interior point $(x_0, y_0) \in \Omega$, then $u$ is constant in a neighborhood of $(x_0, y_0)$.
3. Deduce that any non-constant harmonic function on a bounded domain attains its maximum and minimum strictly on the boundary $\partial\Omega$.""",
                "solution": r"""### 1. Rigorous Proof of the Mean Value Property in $\mathbb{R}^2$
Let $(x_0, y_0) \in \Omega$ and choose $R > 0$ such that $\bar{B}_R(x_0, y_0) \subset \Omega$.
For $r \in (0, R]$, define the polar circle average:
$$I(r) = \frac{1}{2\pi}\int_0^{2\pi} u(x_0 + r\cos\theta, y_0 + r\sin\theta)\,d\theta$$
Differentiating with respect to $r$ under the integral sign (justified by $C^2$ smoothness of $u$):
$$\frac{dI}{dr} = \frac{1}{2\pi}\int_0^{2\pi} \left[ u_x(x_0 + r\cos\theta, y_0 + r\sin\theta) \cos\theta + u_y(x_0 + r\cos\theta, y_0 + r\sin\theta) \sin\theta \right] d\theta$$
Notice that $\mathbf{n} = (\cos\theta, \sin\theta)$ is the outward unit normal vector to the circle $\partial B_r$, and the directional derivative is:
$$\frac{\partial u}{\partial \mathbf{n}} = \nabla u \cdot \mathbf{n} = u_x \cos\theta + u_y \sin\theta$$
Furthermore, the arc length element is $ds = r\,d\theta \implies d\theta = \frac{ds}{r}$.
Therefore:
$$\frac{dI}{dr} = \frac{1}{2\pi r} \oint_{\partial B_r(x_0, y_0)} \frac{\partial u}{\partial \mathbf{n}}\,ds$$
Applying Green's First Identity (the 2D Divergence Theorem) to the vector field $\nabla u$:
$$\oint_{\partial B_r} \frac{\partial u}{\partial \mathbf{n}}\,ds = \oint_{\partial B_r} \nabla u \cdot \mathbf{n}\,ds = \iint_{B_r} \nabla \cdot (\nabla u)\,dA = \iint_{B_r} \nabla^2 u\,dA$$
Since $u$ is harmonic, $\nabla^2 u = 0$ everywhere in $\Omega$.
Thus:
$$\frac{dI}{dr} = \frac{1}{2\pi r} \iint_{B_r} 0\,dA = 0 \quad \forall r \in (0, R]$$
Since $\frac{dI}{dr} = 0$, $I(r)$ is constant on $(0, R]$.
Taking the limit as $r \to 0^+$:
$$\lim_{r \to 0^+} I(r) = \lim_{r \to 0^+} \frac{1}{2\pi}\int_0^{2\pi} u(x_0 + r\cos\theta, y_0 + r\sin\theta)\,d\theta = \frac{1}{2\pi} \cdot 2\pi u(x_0, y_0) = u(x_0, y_0)$$
Therefore:
$$I(R) = u(x_0, y_0) \implies u(x_0, y_0) = \frac{1}{2\pi}\int_0^{2\pi} u(x_0 + R\cos\theta, y_0 + R\sin\theta)\,d\theta$$

---

### 2. Prohibition of Interior Local Extrema
Suppose $(x_0, y_0)$ is a local maximum point: there exists $\delta > 0$ such that $u(x, y) \le u(x_0, y_0)$ for all $(x, y) \in B_\delta(x_0, y_0)$.
Let $M = u(x_0, y_0)$.
For any $0 < r < \delta$, by the Mean Value Property:
$$M = \frac{1}{2\pi}\int_0^{2\pi} u(x_0 + r\cos\theta, y_0 + r\sin\theta)\,d\theta$$
Subtracting from both sides:
$$0 = \frac{1}{2\pi}\int_0^{2\pi} \left[ M - u(x_0 + r\cos\theta, y_0 + r\sin\theta) \right] d\theta$$
Since $(x_0, y_0)$ is a local maximum, the integrand $g(\theta) = M - u(x_0 + r\cos\theta, y_0 + r\sin\theta) \ge 0$ is non-negative and continuous.
A continuous non-negative function whose integral is zero must vanish everywhere:
$$g(\theta) = 0 \implies u(x_0 + r\cos\theta, y_0 + r\sin\theta) = M \quad \forall \theta \in [0, 2\pi], \quad \forall r \in (0, \delta)$$
Thus, $u(x, y) \equiv M$ everywhere in the ball $B_\delta(x_0, y_0)$.

---

### 3. Maximum Attained Strictly on Boundary
Since $\bar{\Omega}$ is compact and $u$ is continuous on $\bar{\Omega}$, by the Extreme Value Theorem, $u$ must attain its global maximum $M^*$ and minimum $m^*$ on $\bar{\Omega}$.
If the maximum were attained at an interior point $\mathbf{x}_0 \in \Omega$, part (2) together with connectedness of $\Omega$ implies $u(\mathbf{x}) \equiv M^*$ everywhere in $\Omega$, making $u$ constant.
Therefore, if $u$ is non-constant:
$$\max_{\bar{\Omega}} u = \max_{\partial\Omega} u \quad \text{and} \quad \min_{\bar{\Omega}} u = \min_{\partial\Omega} u$$
and for all interior points $\mathbf{x} \in \Omega$:
$$\min_{\partial\Omega} u < u(\mathbf{x}) < \max_{\partial\Omega} u$$
The extrema are attained strictly on the boundary $\partial\Omega$. $\blacksquare$"""
            }
        ]
    }
    return u6

if __name__ == "__main__":
    u6 = get_unit6()
    print(f"Loaded Unit 6: {u6['title']} with {len(u6['sections'])} sections and {len(u6['problems'])} problems.")
