# -*- coding: utf-8 -*-
"""
build_pde_unit5.py
Constructs Unit 5: The Heat/Diffusion Equation: Maximum Principles, Fundamental Solution & Separation of Variables
Strictly ZERO course numbers.
"""

def get_unit5():
    u5 = {
        "number": 5,
        "title": "The Heat/Diffusion Equation: Maximum Principles, Fundamental Solution & Separation of Variables",
        "leadSummary": "Parabolic diffusion processes in continuum physics: macroscopic conservation of thermal energy and Fourier's law of conduction, weak and strong maximum/minimum principles, uniqueness and stability theorems, Fourier separation of variables under Dirichlet, Neumann, and Robin boundary conditions, Duhamel's principle for inhomogeneous source distributions, and the Gaussian fundamental solution (heat kernel) on infinite domains.",
        "simulations": ["sim_pde_heat_diffusion_kernel"],
        "sections": [
            {
                "secNumber": "5.1",
                "title": "Physical Derivation of the Diffusion Equation & Fourier's Law",
                "content": r"""### 1. Thermodynamic Conservation of Thermal Energy

Consider an arbitrary, bounded, smooth spatial domain $V \subset \mathbb{R}^3$ filled with a rigid isotropic conducting material of mass density $\rho(\mathbf{x})$, specific heat capacity $c_p(\mathbf{x})$, and thermal conductivity $k(\mathbf{x})$.
Let $u(\mathbf{x}, t)$ denote the absolute temperature field at position $\mathbf{x} = (x, y, z)$ and time $t$.

The total thermal energy contained in the volume $V$ is:
$$E(t) = \int_V \rho c_p u(\mathbf{x}, t)\,dV$$
By the First Law of Thermodynamics, the rate of increase of internal thermal energy equals the net rate of heat conducted inward across the boundary surface $\partial V$ plus the rate of heat generated by internal volumetric sources $Q(\mathbf{x}, t)$:
$$\frac{d}{dt} \int_V \rho c_p u\,dV = - \int_{\partial V} \mathbf{q} \cdot \mathbf{n}\,dA + \int_V Q\,dV$$
where $\mathbf{q}(\mathbf{x}, t)$ is the **heat flux vector** (energy per unit area per unit time) and $\mathbf{n}$ is the outward unit normal.

Applying the **Divergence Theorem** to the surface flux integral:
$$\int_{\partial V} \mathbf{q} \cdot \mathbf{n}\,dA = \int_V \nabla \cdot \mathbf{q}\,dV$$
Combining all terms under a single volume integral:
$$\int_V \left[ \rho c_p \frac{\partial u}{\partial t} + \nabla \cdot \mathbf{q} - Q \right] dV = 0$$
Since this integral vanishes for every arbitrary subvolume $V \subset \mathbb{R}^3$, the integrand must vanish identically, yielding the **continuity equation for heat energy**:
$$\rho c_p \frac{\partial u}{\partial t} + \nabla \cdot \mathbf{q} = Q$$

---

### 2. Fourier's Law of Heat Conduction

In 1822, Joseph Fourier established the empirical constitutive law: heat flows in the direction of the steepest decrease in temperature at a rate proportional to the temperature gradient:
$$\mathbf{q} = -k \nabla u$$
where $k > 0$ is the thermal conductivity of the medium.
Substituting Fourier's law into the continuity equation:
$$\rho c_p \frac{\partial u}{\partial t} - \nabla \cdot (k \nabla u) = Q$$
For a homogeneous, isotropic medium where $\rho, c_p,$ and $k$ are uniform constants:
$$\rho c_p \frac{\partial u}{\partial t} = k \nabla^2 u + Q \implies \frac{\partial u}{\partial t} = \frac{k}{\rho c_p} \nabla^2 u + \frac{Q}{\rho c_p}$$
Defining the **thermal diffusivity** $\alpha = \frac{k}{\rho c_p} > 0$ (with physical dimensions $[L^2 T^{-1}]$), we obtain in the absence of internal sources ($Q = 0$):
$$\frac{\partial u}{\partial t} = \alpha \nabla^2 u$$
In one spatial dimension ($x \in \mathbb{R}$), this simplifies to the **1D heat equation**:
$$\frac{\partial u}{\partial t} = \alpha \frac{\partial^2 u}{\partial x^2}$$"""
            },
            {
                "secNumber": "5.2",
                "title": "The Weak & Strong Maximum Principles & Uniqueness Theorems",
                "content": r"""### 1. The Parabolic Cylinder and Maximum Principle

Let $\Omega \subset \mathbb{R}^n$ be an open, bounded spatial domain, and let $T > 0$ be a fixed time horizon.
Define the **spacetime cylinder**:
$$Q_T = \Omega \times (0, T]$$
and the **parabolic boundary** $\Gamma_T$ consisting of the base at $t = 0$ and the lateral spatial boundary:
$$\Gamma_T = (\bar{\Omega} \times \{0\}) \cup (\partial \Omega \times [0, T])$$
Notice that the top lid $\Omega \times \{t = T\}$ is part of $Q_T$, not $\Gamma_T$.

> **Theorem 5.1 (Weak Maximum Principle for the Heat Equation):**
> Let $u \in C^2(Q_T) \cap C(\bar{Q}_T)$ satisfy the heat equation:
> $$u_t - \alpha \nabla^2 u = 0 \quad \text{in } Q_T$$
> Then the maximum and minimum of $u$ on the closed cylinder $\bar{Q}_T$ are attained on the parabolic boundary $\Gamma_T$:
> $$\max_{\bar{Q}_T} u(\mathbf{x}, t) = \max_{\Gamma_T} u(\mathbf{x}, t), \qquad \min_{\bar{Q}_T} u(\mathbf{x}, t) = \min_{\Gamma_T} u(\mathbf{x}, t)$$

*Proof:*
Let $M = \max_{\Gamma_T} u$. We must show that $u(\mathbf{x}, t) \le M$ for all $(\mathbf{x}, t) \in Q_T$.
Assume for contradiction that there exists a point $(\mathbf{x}_0, t_0) \in Q_T$ such that $u(\mathbf{x}_0, t_0) = M + \epsilon$ with $\epsilon > 0$.
For any $\delta > 0$, construct the auxiliary perturbation function:
$$v(\mathbf{x}, t) = u(\mathbf{x}, t) - \delta t$$
Choose $\delta = \frac{\epsilon}{2T} > 0$.
Then on $\Gamma_T$:
$$v(\mathbf{x}, t) \le u(\mathbf{x}, t) \le M$$
While at $(\mathbf{x}_0, t_0)$:
$$v(\mathbf{x}_0, t_0) = u(\mathbf{x}_0, t_0) - \delta t_0 \ge M + \epsilon - \frac{\epsilon}{2T} t_0 \ge M + \epsilon - \frac{\epsilon}{2} = M + \frac{\epsilon}{2} > M$$
Since $\bar{Q}_T$ is compact and $v$ is continuous, $v$ must attain its global maximum on $\bar{Q}_T$ at some point $(\mathbf{x}^*, t^*) \in Q_T$ (in the interior or on the top lid $t^* = T$).
At this internal maximum point:
1. Spatial first derivatives vanish: $\nabla v(\mathbf{x}^*, t^*) = \mathbf{0}$.
2. Spatial second derivatives satisfy the negative semi-definite Hessian condition: $\nabla^2 v(\mathbf{x}^*, t^*) \le 0$.
3. The time derivative must satisfy: $v_t(\mathbf{x}^*, t^*) \ge 0$ (if $t^* < T$, $v_t = 0$; if $t^* = T$, $v_t \ge 0$ from below).

Now compute the heat operator applied to $v$:
$$v_t - \alpha \nabla^2 v = (u_t - \delta) - \alpha \nabla^2 u = (u_t - \alpha \nabla^2 u) - \delta = 0 - \delta = -\delta < 0$$
However, using the derivative conditions at the maximum point:
$$v_t(\mathbf{x}^*, t^*) - \alpha \nabla^2 v(\mathbf{x}^*, t^*) \ge 0 - \alpha(0) = 0$$
This yields the strict contradiction:
$$0 \le v_t(\mathbf{x}^*, t^*) - \alpha \nabla^2 v(\mathbf{x}^*, t^*) = -\delta < 0$$
Therefore, no such point $(\mathbf{x}_0, t_0)$ can exist, proving $u(\mathbf{x}, t) \le M$ throughout $\bar{Q}_T$.
Applying the same argument to $-u$ yields the minimum principle. $\blacksquare$

---

### 2. Uniqueness and Continuous Dependence

> **Theorem 5.2 (Uniqueness of Initial-Boundary Value Problem):**
> There exists at most one classical solution to the Dirichlet problem:
> $$\begin{cases} u_t - \alpha \nabla^2 u = f(\mathbf{x}, t) & \text{in } Q_T \\ u(\mathbf{x}, 0) = g(\mathbf{x}) & \text{on } \Omega \\ u(\mathbf{x}, t) = h(\mathbf{x}, t) & \text{on } \partial \Omega \times [0, T] \end{cases}$$

*Proof:*
Let $u_1$ and $u_2$ be two solutions, and let $w = u_1 - u_2$.
Then $w_t - \alpha \nabla^2 w = 0$ in $Q_T$, and $w = 0$ on $\Gamma_T$.
By the Weak Maximum and Minimum Principles:
$$0 = \min_{\Gamma_T} w \le w(\mathbf{x}, t) \le \max_{\Gamma_T} w = 0 \quad \forall (\mathbf{x}, t) \in \bar{Q}_T$$
Thus $w(\mathbf{x}, t) \equiv 0$, which proves $u_1 \equiv u_2$. $\blacksquare$"""
            },
            {
                "secNumber": "5.3",
                "title": "Separation of Variables: Dirichlet, Neumann & Robin Boundaries",
                "content": r"""### 1. Homogeneous Dirichlet Conditions on a Finite Rod $[0, L]$

Consider the heat conduction on $[0, L]$ with both ends kept at zero temperature:
$$\begin{cases} u_t = \alpha u_{xx}, & 0 < x < L, \quad t > 0 \\ u(0, t) = 0, \quad u(L, t) = 0, & t \ge 0 \\ u(x, 0) = f(x), & 0 \le x \le L \end{cases}$$
Separating variables $u(x, t) = X(x) T(t)$:
$$\frac{T'(t)}{\alpha T(t)} = \frac{X''(x)}{X(x)} = -\lambda$$
1. Spatial Sturm-Liouville problem: $X'' + \lambda X = 0, X(0) = X(L) = 0$.
   Eigenvalues: $\lambda_n = \left(\frac{n\pi}{L}\right)^2$, Eigenfunctions: $X_n(x) = \sin\left(\frac{n\pi x}{L}\right)$ for $n \in \mathbb{N}$.
2. Temporal ODE: $T_n'(t) + \alpha \lambda_n T_n(t) = 0 \implies T_n(t) = e^{-\alpha (n\pi/L)^2 t}$.
General solution:
$$u(x, t) = \sum_{n=1}^\infty b_n \sin\left(\frac{n\pi x}{L}\right) \exp\left( -\alpha \left(\frac{n\pi}{L}\right)^2 t \right)$$
where the Fourier sine coefficients are:
$$b_n = \frac{2}{L}\int_0^L f(x) \sin\left(\frac{n\pi x}{L}\right)\,dx$$
Notice the exponential decay factor: higher Fourier harmonics damp out drastically faster ($n^2$), smoothing out initial irregularities instantly!

---

### 2. Homogeneous Neumann Conditions (Insulated Rod)

When both ends of the rod are perfectly thermally insulated:
$$u_x(0, t) = 0, \qquad u_x(L, t) = 0$$
The spatial eigenfunctions are $X_0(x) = 1$ (for $\lambda_0 = 0$) and $X_n(x) = \cos\left(\frac{n\pi x}{L}\right)$.
The general solution is:
$$u(x, t) = \frac{a_0}{2} + \sum_{n=1}^\infty a_n \cos\left(\frac{n\pi x}{L}\right) \exp\left( -\alpha \left(\frac{n\pi}{L}\right)^2 t \right)$$
where:
$$a_0 = \frac{2}{L}\int_0^L f(x)\,dx, \qquad a_n = \frac{2}{L}\int_0^L f(x) \cos\left(\frac{n\pi x}{L}\right)\,dx$$
As $t \to \infty$, all decaying exponential terms vanish:
$$\lim_{t \to \infty} u(x, t) = \frac{a_0}{2} = \frac{1}{L}\int_0^L f(x)\,dx = \bar{u}_{\text{initial}}$$
The temperature asymptotically equilibrates to the **exact average initial temperature** of the rod, demonstrating total thermal energy conservation in an insulated system."""
            },
            {
                "secNumber": "5.4",
                "title": "Inhomogeneous Heat Equations & Duhamel's Principle",
                "content": r"""### 1. Inhomogeneous Initial-Boundary Value Problems

Consider the heat equation with an external heat source $f(x, t)$:
$$\begin{cases}
u_t - \alpha u_{xx} = f(x, t), & 0 < x < L, \quad t > 0 \\
u(0, t) = 0, \quad u(L, t) = 0, & t \ge 0 \\
u(x, 0) = 0, & 0 \le x \le L
\end{cases}$$

---

### 2. Duhamel's Principle

Jean-Marie Duhamel (1837) proved that the solution to an inhomogeneous PDE driven by a continuous source $f(x, t)$ can be constructed by integrating a family of solutions to **homogeneous** initial value problems.

> **Theorem 5.3 (Duhamel's Principle for Parabolic Equations):**
> For each fixed parameter $\tau \ge 0$, let $w(x, t; \tau)$ be the unique solution to the homogeneous heat problem for $t > \tau$:
> $$\begin{cases}
> w_t - \alpha w_{xx} = 0, & 0 < x < L, \quad t > \tau \\
> w(0, t; \tau) = 0, \quad w(L, t; \tau) = 0, & t \ge \tau \\
> w(x, \tau; \tau) = f(x, \tau), & 0 \le x \le L
> \end{cases}$$
> Then the solution $u(x, t)$ to the inhomogeneous problem with zero initial condition is given by the integral:
> $$u(x, t) = \int_0^t w(x, t; \tau)\,d\tau$$

*Proof:*
Differentiating $u(x, t)$ with respect to $t$ via Leibniz's rule for differentiating under the integral sign:
$$u_t(x, t) = \frac{\partial}{\partial t} \int_0^t w(x, t; \tau)\,d\tau = w(x, t; t) + \int_0^t w_t(x, t; \tau)\,d\tau$$
By the initial condition of the family $w$, $w(x, t; t) = f(x, t)$.
Next, compute the spatial derivative:
$$u_{xx}(x, t) = \int_0^t w_{xx}(x, t; \tau)\,d\tau$$
Now evaluate the heat operator on $u$:
$$u_t - \alpha u_{xx} = f(x, t) + \int_0^t [w_t(x, t; \tau) - \alpha w_{xx}(x, t; \tau)]\,d\tau$$
Since $w$ satisfies the homogeneous heat equation $w_t - \alpha w_{xx} = 0$, the integral vanishes identically:
$$u_t - \alpha u_{xx} = f(x, t) + 0 = f(x, t)$$
Furthermore, at $t = 0$:
$$u(x, 0) = \int_0^0 w(x, 0; \tau)\,d\tau = 0$$
And along the boundaries $x = 0, L$, since $w(0, t; \tau) = w(L, t; \tau) = 0$, $u(0, t) = u(L, t) = 0$. $\blacksquare$"""
            },
            {
                "secNumber": "5.5",
                "title": "Infinite Domain Diffusion: The Gaussian Fundamental Solution",
                "content": r"""### 1. Derivation of the Heat Kernel via Similarity Variables

Consider the heat equation on the unbounded line $\mathbb{R}$:
$$u_t = \alpha u_{xx}, \qquad x \in \mathbb{R}, \quad t > 0$$
subject to a unit point source concentrated at the origin at $t = 0$:
$$u(x, 0) = \delta(x)$$
where $\delta(x)$ is the Dirac delta distribution.

The PDE and total heat content $\int_{-\infty}^\infty u(x, t)\,dx = 1$ are invariant under the parabolic scaling transformation:
$$x \mapsto \lambda x, \qquad t \mapsto \lambda^2 t, \qquad u \mapsto \lambda^{-1} u$$
This scaling symmetry dictates that $u(x, t)$ must take the self-similar form:
$$u(x, t) = \frac{1}{\sqrt{t}} \phi(\xi), \qquad \text{where } \xi = \frac{x}{\sqrt{\alpha t}}$$

Compute partial derivatives:
$$u_t = -\frac{1}{2t^{3/2}} \phi(\xi) + \frac{1}{\sqrt{t}} \phi'(\xi) \left(-\frac{x}{2\alpha^{1/2} t^{3/2}}\right) = -\frac{1}{2t^{3/2}} [\phi(\xi) + \xi \phi'(\xi)] = -\frac{1}{2t^{3/2}} (\xi \phi)'$$
$$u_x = \frac{1}{\sqrt{\alpha} t} \phi'(\xi), \qquad u_{xx} = \frac{1}{\alpha t^{3/2}} \phi''(\xi)$$
Substituting into $u_t = \alpha u_{xx}$:
$$-\frac{1}{2t^{3/2}} (\xi \phi)' = \frac{1}{t^{3/2}} \phi'' \implies \phi'' + \frac{1}{2}(\xi \phi)' = 0$$
Integrating once with respect to $\xi$:
$$\phi' + \frac{1}{2}\xi \phi = C$$
Since $u \to 0$ and $u_x \to 0$ as $|x| \to \infty$, the constant $C = 0$:
$$\frac{\phi'}{\phi} = -\frac{1}{2}\xi \implies \ln \phi = -\frac{1}{4}\xi^2 + \ln A \implies \phi(\xi) = A e^{-\xi^2 / 4}$$
Substituting $\xi = \frac{x}{\sqrt{\alpha t}}$:
$$u(x, t) = \frac{A}{\sqrt{t}} \exp\left( -\frac{x^2}{4\alpha t} \right)$$
To determine the normalization constant $A$, enforce $\int_{-\infty}^\infty u(x, t)\,dx = 1$:
$$\int_{-\infty}^\infty \frac{A}{\sqrt{t}} e^{-x^2 / (4\alpha t)}\,dx = A \sqrt{4\alpha} \int_{-\infty}^\infty e^{-z^2}\,dz = A \sqrt{4\alpha} \sqrt{\pi} = 2 A \sqrt{\pi \alpha} = 1 \implies A = \frac{1}{\sqrt{4\pi \alpha}}$$

> **Definition 5.1 (The Gaussian Heat Kernel):**
> The **fundamental solution** (or **heat kernel**) of the 1D diffusion equation is:
> $$K(x, t) = \frac{1}{\sqrt{4\pi \alpha t}} \exp\left( -\frac{x^2}{4\alpha t} \right), \qquad x \in \mathbb{R}, \quad t > 0$$
> For an arbitrary bounded initial temperature distribution $u(x, 0) = f(x)$, the solution is given by the convolution:
> $$u(x, t) = (K * f)(x, t) = \frac{1}{\sqrt{4\pi \alpha t}} \int_{-\infty}^\infty \exp\left( -\frac{(x - y)^2}{4\alpha t} \right) f(y)\,dy$$"""
            }
        ],
        "problems": [
            {
                "tier": "Foundational",
                "title": "Fourier Series Solution of 1D Rod with Homogeneous Dirichlet Ends",
                "statement": r"""A uniform metal rod of length $L = \pi$ and thermal diffusivity $\alpha = 1$ has its ends held at zero temperature:
$$u(0, t) = 0, \qquad u(\pi, t) = 0, \qquad t \ge 0$$
The initial temperature distribution is given by:
$$f(x) = \sin(x) - 2\sin(3x) + 5\sin(4x), \qquad 0 \le x \le \pi$$
1. Find the exact solution $u(x, t)$ for all $t > 0$.
2. Compute the decay rate of each component and explain which mode dominates as $t \to \infty$.""",
                "solution": r"""### 1. General Fourier Sine Expansion
For $L = \pi$ and $\alpha = 1$, the eigenfunctions are $X_n(x) = \sin(nx)$ and the eigenvalues are $\lambda_n = n^2$.
The general solution is:
$$u(x, t) = \sum_{n=1}^\infty b_n \sin(nx) e^{-n^2 t}$$
At $t = 0$:
$$u(x, 0) = \sum_{n=1}^\infty b_n \sin(nx) = \sin(x) - 2\sin(3x) + 5\sin(4x)$$

---

### 2. Identifying Fourier Coefficients
By the orthogonality of the sine basis on $[0, \pi]$, we read off the coefficients directly:
- $b_1 = 1$
- $b_2 = 0$
- $b_3 = -2$
- $b_4 = 5$
- $b_n = 0$ for all other $n \ge 5$.

Therefore, the exact solution is:
$$u(x, t) = e^{-t} \sin(x) - 2 e^{-9t} \sin(3x) + 5 e^{-16t} \sin(4x)$$

---

### 3. Asymptotic Analysis
The three components decay with exponential rates:
- $n = 1$: $e^{-t}$ (decay rate 1)
- $n = 3$: $e^{-9t}$ (decay rate 9)
- $n = 4$: $e^{-16t}$ (decay rate 16)

The $n = 4$ mode damps 16 times faster than the fundamental mode!
For even moderately small times (e.g. $t = 1$), $e^{-16} \approx 1.1 \times 10^{-7}$ and $e^{-9} \approx 1.2 \times 10^{-4}$, whereas $e^{-1} \approx 0.368$.
Thus, as $t \to \infty$:
$$u(x, t) \sim e^{-t} \sin(x)$$
The fundamental harmonic $\sin(x)$ dominates the entire thermal profile asymptotically. $\blacksquare$"""
            },
            {
                "tier": "Advanced",
                "title": "Insulated Rod with Asymmetric Parabolic Initial Profile",
                "statement": r"""A rod of length $L$ and diffusivity $\alpha$ is thermally insulated at both ends:
$$u_x(0, t) = 0, \qquad u_x(L, t) = 0, \qquad t \ge 0$$
The initial temperature profile is parabolic:
$$u(x, 0) = x(L - x), \qquad 0 \le x \le L$$
1. Find the complete Fourier cosine series solution $u(x, t)$.
2. Calculate the steady-state equilibrium temperature as $t \to \infty$.
3. Show that total thermal energy is conserved for all $t \ge 0$.""",
                "solution": r"""### 1. General Fourier Cosine Series
For insulated boundaries, the solution is:
$$u(x, t) = \frac{a_0}{2} + \sum_{n=1}^\infty a_n \cos\left(\frac{n\pi x}{L}\right) \exp\left( -\alpha \left(\frac{n\pi}{L}\right)^2 t \right)$$

---

### 2. Computation of Fourier Coefficients
1. **Constant Term $a_0$:**
   $$\frac{a_0}{2} = \frac{1}{L}\int_0^L x(L - x)\,dx = \frac{1}{L}\left[ \frac{L x^2}{2} - \frac{x^3}{3} \right]_0^L = \frac{1}{L}\left( \frac{L^3}{2} - \frac{L^3}{3} \right) = \frac{1}{L}\left(\frac{L^3}{6}\right) = \frac{L^2}{6}$$
   So $a_0 = \frac{L^2}{3}$.

2. **Higher Coefficients $a_n$ for $n \ge 1$:**
   $$a_n = \frac{2}{L}\int_0^L (L x - x^2) \cos\left(\frac{n\pi x}{L}\right)\,dx$$
   Using integration by parts twice:
   Let $u = Lx - x^2 \implies u' = L - 2x \implies u'' = -2$.
   $dv = \cos(k x)\,dx \implies v = \frac{\sin(k x)}{k} \implies \int v = -\frac{\cos(k x)}{k^2}$, where $k = \frac{n\pi}{L}$.
   $$\int_0^L (Lx - x^2) \cos(kx)\,dx = \left[ (Lx - x^2) \frac{\sin(kx)}{k} \right]_0^L - \int_0^L (L - 2x) \frac{\sin(kx)}{k}\,dx$$
   The boundary term vanishes since $Lx - x^2 = 0$ at $x = 0, L$.
   Integrating the remaining term by parts:
   $$\int_0^L (L - 2x) \frac{\sin(kx)}{k}\,dx = \left[ -(L - 2x) \frac{\cos(kx)}{k^2} \right]_0^L - \int_0^L (-2)\left(-\frac{\cos(kx)}{k^2}\right)dx$$
   The integral of $\cos(kx)$ from $0$ to $L$ is $\frac{\sin(kL)}{k} = 0$.
   Evaluating the boundary term:
   $$\left[ -(L - 2x) \frac{\cos(kx)}{k^2} \right]_0^L = -\frac{1}{k^2} \left[ (L - 2L)\cos(kL) - (L - 0)\cos(0) \right] = -\frac{1}{k^2} \left[ -L (-1)^n - L \right] = \frac{L}{k^2}[(-1)^n + 1]$$
   Therefore:
   $$\int_0^L (Lx - x^2)\cos(kx)\,dx = - \frac{L}{k^2}[(-1)^n + 1] = -\frac{L^3}{n^2 \pi^2}[(-1)^n + 1]$$
   Multiplying by $\frac{2}{L}$:
   $$a_n = -\frac{2L^2}{n^2 \pi^2} [1 + (-1)^n]$$
   - If $n$ is odd: $1 + (-1)^n = 0 \implies a_n = 0$.
   - If $n$ is even ($n = 2m$): $1 + (-1)^n = 2 \implies a_{2m} = -\frac{4L^2}{(2m)^2 \pi^2} = -\frac{L^2}{m^2 \pi^2}$.

The complete series solution is:
$$u(x, t) = \frac{L^2}{6} - \frac{L^2}{\pi^2} \sum_{m=1}^\infty \frac{1}{m^2} \cos\left(\frac{2m\pi x}{L}\right) \exp\left( -\alpha \left(\frac{2m\pi}{L}\right)^2 t \right)$$

---

### 3. Steady-State Equilibrium and Energy Conservation
As $t \to \infty$, all exponential terms decay to zero:
$$u_{\text{steady}} = \lim_{t \to \infty} u(x, t) = \frac{L^2}{6}$$
The total thermal energy in the rod at any time $t$ is:
$$E(t) = \int_0^L u(x, t)\,dx = \int_0^L \frac{L^2}{6}\,dx - \sum_{m=1}^\infty \frac{L^2}{m^2 \pi^2} e^{-\alpha (2m\pi/L)^2 t} \int_0^L \cos\left(\frac{2m\pi x}{L}\right)\,dx$$
Since $\int_0^L \cos(2m\pi x/L)\,dx = 0$ for all $m \ge 1$:
$$E(t) = \frac{L^3}{6} = E(0) \quad \forall t \ge 0$$
Total thermal energy is strictly invariant. $\blacksquare$"""
            },
            {
                "tier": "Honors Challenge",
                "title": "Energy Method Proof of Uniqueness and Continuous Data Dependence",
                "statement": r"""Consider the initial-boundary value problem for the 1D heat equation with Robin boundary conditions:
$$\begin{cases}
u_t - \alpha u_{xx} = f(x, t), & 0 < x < L, \quad t > 0 \\
u_x(0, t) - h_0 u(0, t) = g_0(t), & t \ge 0 \quad (h_0 > 0) \\
u_x(L, t) + h_L u(L, t) = g_L(t), & t \ge 0 \quad (h_L > 0) \\
u(x, 0) = \phi(x), & 0 \le x \le L
\end{cases}$$
1. Use the energy integral method to prove that this problem has at most one $C^2$ solution.
2. Establish continuous dependence on the initial data in the $L^2$-norm.""",
                "solution": r"""### 1. Homogeneous Difference System
Let $u$ and $v$ be two classical solutions, and define $w(x, t) = u(x, t) - v(x, t)$.
Then $w$ satisfies:
$$\begin{cases}
w_t - \alpha w_{xx} = 0, & 0 < x < L, \quad t > 0 \\
w_x(0, t) - h_0 w(0, t) = 0 \implies w_x(0, t) = h_0 w(0, t), & t \ge 0 \\
w_x(L, t) + h_L w(L, t) = 0 \implies w_x(L, t) = -h_L w(L, t), & t \ge 0 \\
w(x, 0) = 0, & 0 \le x \le L
\end{cases}$$

---

### 2. Time Evolution of the $L^2$ Energy Functional
Define the total $L^2$ energy of the error:
$$E(t) = \frac{1}{2}\int_0^L [w(x, t)]^2\,dx$$
Differentiate with respect to time:
$$\frac{dE}{dt} = \int_0^L w w_t\,dx = \int_0^L w (\alpha w_{xx})\,dx = \alpha \int_0^L w w_{xx}\,dx$$
Integrate by parts:
$$\int_0^L w w_{xx}\,dx = \left[ w(x, t) w_x(x, t) \right]_0^L - \int_0^L [w_x(x, t)]^2\,dx$$
Substitute the Robin boundary conditions:
- At $x = L$: $w(L, t) w_x(L, t) = w(L, t) [-h_L w(L, t)] = -h_L [w(L, t)]^2$
- At $x = 0$: $w(0, t) w_x(0, t) = w(0, t) [h_0 w(0, t)] = h_0 [w(0, t)]^2$

Thus:
$$\left[ w w_x \right]_0^L = -h_L [w(L, t)]^2 - h_0 [w(0, t)]^2$$
Substituting back into $dE/dt$:
$$\frac{dE}{dt} = -\alpha \left( \int_0^L [w_x(x, t)]^2\,dx + h_0 [w(0, t)]^2 + h_L [w(L, t)]^2 \right)$$
Since $\alpha > 0, h_0 > 0, h_L > 0$, every term inside the parentheses is strictly non-negative:
$$\frac{dE}{dt} \le 0 \quad \forall t \ge 0$$

---

### 3. Conclusion of Uniqueness
Integrating from $0$ to $t$:
$$E(t) \le E(0)$$
At $t = 0$:
$$E(0) = \frac{1}{2}\int_0^L [w(x, 0)]^2\,dx = \frac{1}{2}\int_0^L 0\,dx = 0$$
Since $E(t) = \frac{1}{2}\int_0^L w^2\,dx \ge 0$, we have:
$$0 \le E(t) \le 0 \implies E(t) \equiv 0 \quad \forall t \ge 0$$
Because $w^2$ is continuous and non-negative:
$$w(x, t) \equiv 0 \implies u(x, t) \equiv v(x, t)$$
The solution is strictly unique.

---

### 4. Continuous Dependence on Initial Data
If initial data $\phi_1, \phi_2$ satisfy $\|\phi_1 - \phi_2\|_{L^2} < \epsilon$, then:
$$E(0) = \frac{1}{2}\|\phi_1 - \phi_2\|_{L^2}^2 < \frac{\epsilon^2}{2}$$
Since $E(t) \le E(0)$:
$$\|u(\cdot, t) - v(\cdot, t)\|_{L^2}^2 = 2 E(t) \le 2 E(0) < \epsilon^2 \implies \|u(\cdot, t) - v(\cdot, t)\|_{L^2} < \epsilon \quad \forall t \ge 0$$
The solution depends continuously on initial perturbations in the $L^2$-norm. $\blacksquare$"""
            }
        ]
    }
    return u5

if __name__ == "__main__":
    u5 = get_unit5()
    print(f"Loaded Unit 5: {u5['title']} with {len(u5['sections'])} sections and {len(u5['problems'])} problems.")
