# -*- coding: utf-8 -*-
"""
build_aa_unit8.py
Constructs Unit 8: Polynomial Rings, Irreducibility Criteria & Field Extensions
"""

def get_unit8():
    u8 = {
        "number": 8,
        "title": "Polynomial Rings, Irreducibility Criteria & Field Extensions",
        "leadSummary": "Comprehensive theory of polynomial rings R[x], division algorithm in F[x], Euclidean domain and PID structures, Gauss's Lemma, Eisenstein's Irreducibility Criterion with complete proof, cyclotomic polynomials, field extensions K/F, minimal polynomials, algebraic elements, and the Tower Law with classical geometric impossibility applications.",
        "simulations": ["sim_aa_polynomial_roots"],
        "sections": [
            {
                "secNumber": "8.1",
                "title": "Polynomial Rings $R[x]$, Division Algorithm & The PID Structure of $F[x]$",
                "content": r"""### 1. Polynomial Rings over a Commutative Ring

Let $R$ be a commutative ring with unity $1_R$.

> **Definition 8.1 (Polynomial Ring $R[x]$):**
> The **polynomial ring** in one indeterminate $x$ over $R$, denoted $R[x]$, is the set of all formal expressions:
> $$f(x) = a_n x^n + a_{n-1} x^{n-1} + \dots + a_1 x + a_0 = \sum_{i=0}^n a_i x^i$$
> where $a_i \in R$ and $n \ge 0$.
> If $a_n \ne 0$, then $n$ is called the **degree** of $f(x)$, denoted $\deg(f) = n$, and $a_n$ is the **leading coefficient**.
> If $a_n = 1$, $f(x)$ is called **monic**.
> The zero polynomial $0$ has $\deg(0) = -\infty$.

#### Degree Properties in an Integral Domain:
If $R$ is an integral domain, then for any non-zero $f, g \in R[x]$:
$$\deg(f \cdot g) = \deg(f) + \deg(g)$$
$$\deg(f + g) \le \max(\deg(f), \deg(g))$$
Moreover, the units of $R[x]$ are precisely the units of the coefficient ring: $R[x]^\times = R^\times$.

---

### 2. The Division Algorithm in $F[x]$ over a Field

When the coefficient ring is a **field** $F$, every non-zero element has a multiplicative inverse. This guarantees that long division of polynomials can always be performed without fractions in the coefficients.

> **Theorem 8.1 (Division Algorithm for Polynomials):**
> Let $F$ be a field, and let $f(x), g(x) \in F[x]$ with $g(x) \ne 0$.
> There exist unique polynomials $q(x), r(x) \in F[x]$ (quotient and remainder) such that:
> $$f(x) = q(x) g(x) + r(x), \quad \text{where either } r(x) = 0 \text{ or } \deg(r) < \deg(g)$$

#### Complete Proof:
1. **Existence:**
   Consider the set of all remainders:
   $$S = \{ f(x) - k(x) g(x) : k(x) \in F[x] \}$$
   - If $0 \in S$, then $f(x) = q(x) g(x)$ with $r(x) = 0$.
   - Otherwise, consider the non-negative integer degrees of non-zero elements in $S$:
     $$\Delta = \{ \deg(p(x)) : p(x) \in S \setminus \{0\} \} \subseteq \mathbb{Z}_{\ge 0}$$
     By the Well-Ordering Principle of $\mathbb{Z}_{\ge 0}$, $\Delta$ has a minimal element.
     Let $r(x) = f(x) - q(x) g(x) \in S$ have minimal degree.
     We claim $\deg(r) < \deg(g)$.
     Suppose for contradiction that $\deg(r) = m \ge n = \deg(g)$.
     Let $r(x) = a_m x^m + \dots + a_0$ and $g(x) = b_n x^n + \dots + b_0$ (with $b_n \ne 0$).
     Because $F$ is a field, $b_n^{-1} \in F$.
     Construct the polynomial:
     $$r_1(x) = r(x) - (a_m b_n^{-1} x^{m-n}) g(x)$$
     The leading term of $(a_m b_n^{-1} x^{m-n}) g(x)$ is precisely $a_m b_n^{-1} b_n x^m = a_m x^m$, which cancels the leading term of $r(x)$!
     Thus $\deg(r_1) < m = \deg(r)$.
     Notice $r_1(x) = f(x) - [q(x) + a_m b_n^{-1} x^{m-n}] g(x) \in S$, which contradicts the minimality of $\deg(r)$!
     Therefore, $\deg(r) < \deg(g)$.
2. **Uniqueness:**
   Suppose $f(x) = q_1(x) g(x) + r_1(x) = q_2(x) g(x) + r_2(x)$.
   Then:
   $$(q_1(x) - q_2(x)) g(x) = r_2(x) - r_1(x)$$
   If $q_1(x) \ne q_2(x)$, the left side has degree:
   $$\deg((q_1 - q_2) g) = \deg(q_1 - q_2) + \deg(g) \ge \deg(g)$$
   However, the right side has $\deg(r_2 - r_1) \le \max(\deg(r_2), \deg(r_1)) < \deg(g)$, which is impossible!
   Therefore, $q_1(x) = q_2(x)$, which forces $r_1(x) = r_2(x)$. $\blacksquare$

---

### 3. $F[x]$ is a Euclidean Domain and a PID

> **Theorem 8.2 ($F[x]$ is an ED, PID, and UFD):**
> For any field $F$:
> 1. $F[x]$ is a Euclidean Domain with norm $d(f) = \deg(f)$.
> 2. $F[x]$ is a Principal Ideal Domain (PID). Every ideal is generated by a unique monic polynomial.
> 3. $F[x]$ is a Unique Factorization Domain (UFD). Every non-zero polynomial factors uniquely into irreducible polynomials up to non-zero constant multiples."""
            },
            {
                "secNumber": "8.2",
                "title": "Roots of Polynomials, Factor Theorem & Remainder Theorem",
                "content": r"""### 1. Evaluation Homomorphism and Roots

Let $F$ be a field and let $\alpha \in F$. The map:
$$\text{ev}_\alpha: F[x] \to F, \quad \text{ev}_\alpha(f(x)) = f(\alpha)$$
is a surjective ring homomorphism called the **evaluation homomorphism at $\alpha$**.

> **Definition 8.2 (Root):**
> An element $\alpha \in F$ is called a **root** (or zero) of $f(x) \in F[x]$ if $f(\alpha) = 0$, or equivalently, $f(x) \in \ker(\text{ev}_\alpha)$.

---

### 2. Remainder and Factor Theorems

> **Theorem 8.3 (Polynomial Remainder Theorem):**
> If $f(x) \in F[x]$ is divided by the linear polynomial $(x - \alpha)$, the remainder is the constant $f(\alpha)$:
> $$f(x) = q(x)(x - \alpha) + f(\alpha)$$

#### Proof:
By the Division Algorithm (Theorem 8.1), divide $f(x)$ by $(x - \alpha)$:
$$f(x) = q(x)(x - \alpha) + r(x)$$
where $\deg(r) < \deg(x - \alpha) = 1$.
Thus $r(x)$ is a constant $c \in F$.
Evaluating both sides at $x = \alpha$:
$$f(\alpha) = q(\alpha)(\alpha - \alpha) + c = q(\alpha) \cdot 0 + c = c$$
Thus $r(x) = f(\alpha)$. $\blacksquare$

> **Corollary 8.3.1 (Factor Theorem):**
> An element $\alpha \in F$ is a root of $f(x) \in F[x]$ if and only if $(x - \alpha)$ divides $f(x)$ in $F[x]$:
> $$f(\alpha) = 0 \iff (x - \alpha) \mid f(x)$$

---

### 3. Bound on the Number of Roots

> **Theorem 8.4 (Number of Roots Bound):**
> Let $F$ be a field, and let $f(x) \in F[x]$ be a non-zero polynomial of degree $n = \deg(f) \ge 0$.
> Then $f(x)$ has at most $n$ distinct roots in $F$.

#### Complete Proof (by induction on $n$):
- **Base Case ($n = 0$):** $f(x) = c \ne 0$ is a non-zero constant. It has $0$ roots. Since $0 \le 0$, the base case holds.
- **Inductive Step:** Assume the theorem holds for all polynomials of degree $n - 1$.
  Let $\deg(f) = n \ge 1$.
  - If $f(x)$ has no roots in $F$, then $0 \le n$ holds trivially.
  - If $f(x)$ has a root $\alpha \in F$, then by the Factor Theorem:
    $$f(x) = (x - \alpha) q(x), \quad \text{where } \deg(q) = n - 1$$
    Let $\beta \in F$ be any root of $f(x)$ distinct from $\alpha$ ($\beta \ne \alpha$).
    Then:
    $$0 = f(\beta) = (\beta - \alpha) q(\beta)$$
    Because $F$ is a field (no zero divisors) and $\beta - \alpha \ne 0$, we must have:
    $$q(\beta) = 0$$
    Thus, every root of $f(x)$ other than $\alpha$ must be a root of $q(x)$.
    By our induction hypothesis, $q(x)$ has at most $n - 1$ roots in $F$.
    Therefore, the total number of roots of $f(x)$ is at most $1 + (n - 1) = n$. $\blacksquare$"""
            },
            {
                "secNumber": "8.3",
                "title": "Gauss's Lemma & Irreducibility over $\\mathbb{Z}[x]$ vs $\\mathbb{Q}[x]$",
                "content": r"""### 1. Primitive Polynomials and Content

Let $f(x) = a_n x^n + \dots + a_1 x + a_0 \in \mathbb{Z}[x]$ be a polynomial with integer coefficients.

> **Definition 8.3 (Content):**
> The **content** of $f(x)$, denoted $C(f)$, is the greatest common divisor of all its coefficients:
> $$C(f) = \gcd(a_n, a_{n-1}, \dots, a_1, a_0)$$
> If $C(f) = 1$, $f(x)$ is called a **primitive polynomial**.

Every non-zero polynomial $f(x) \in \mathbb{Z}[x]$ can be factored uniquely as:
$$f(x) = C(f) \cdot f^*(x)$$
where $f^*(x)$ is primitive.

---

### 2. Gauss's Lemma

> **Theorem 8.5 (Gauss's Lemma):**
> The product of two primitive polynomials in $\mathbb{Z}[x]$ is primitive:
> $$C(f) = 1 \quad \text{and} \quad C(g) = 1 \implies C(f \cdot g) = 1$$

#### Complete Proof:
Let $f(x) = \sum_{i=0}^n a_i x^i$ and $g(x) = \sum_{j=0}^m b_j x^j$ be primitive polynomials.
Suppose for contradiction that $f(x) g(x)$ is NOT primitive.
Then there exists a prime number $p$ such that $p \mid C(fg)$, meaning $p$ divides every coefficient of $fg$.
Consider the canonical reduction homomorphism modulo $p$:
$$\pi_p: \mathbb{Z}[x] \to \mathbb{Z}_p[x], \quad \pi_p\left(\sum c_k x^k\right) = \sum [c_k] x^k$$
Since $p$ divides every coefficient of $f(x) g(x)$:
$$\pi_p(f(x) g(x)) = 0 \in \mathbb{Z}_p[x]$$
Since $\pi_p$ is a ring homomorphism:
$$\pi_p(f(x)) \cdot \pi_p(g(x)) = 0$$
Now, $\mathbb{Z}_p$ is a field (since $p$ is prime), so $\mathbb{Z}_p[x]$ is an **integral domain**!
An integral domain has no zero divisors!
Therefore:
$$\pi_p(f(x)) = 0 \quad \text{or} \quad \pi_p(g(x)) = 0$$
- If $\pi_p(f(x)) = 0$, then $p \mid a_i$ for all $i$, meaning $p \mid C(f) = 1$, a contradiction!
- If $\pi_p(g(x)) = 0$, then $p \mid b_j$ for all $j$, meaning $p \mid C(g) = 1$, a contradiction!
Therefore, no such prime $p$ can divide all coefficients of $f(x) g(x)$.
Hence $C(f \cdot g) = 1$. $\blacksquare$

---

### 3. The Equivalence of Irreducibility over $\mathbb{Z}$ and $\mathbb{Q}$

> **Theorem 8.6 (Gauss's Irreducibility Equivalence):**
> Let $f(x) \in \mathbb{Z}[x]$ be a primitive polynomial.
> Then $f(x)$ is irreducible in $\mathbb{Z}[x]$ if and only if $f(x)$ is irreducible in $\mathbb{Q}[x]$.

#### Complete Proof:
- $(\impliedby)$ If $f(x)$ is irreducible in $\mathbb{Q}[x]$, any non-trivial factorization in $\mathbb{Z}[x]$ would also be a factorization in $\mathbb{Q}[x]$, which is impossible.
- $(\implies)$ Suppose $f(x)$ is reducible in $\mathbb{Q}[x]$.
  Then $f(x) = A(x) B(x)$ with $A(x), B(x) \in \mathbb{Q}[x]$ and $\deg(A), \deg(B) \ge 1$.
  Clear denominators by writing $A(x) = \frac{a}{b} A_0(x)$ and $B(x) = \frac{c}{d} B_0(x)$ where $A_0, B_0 \in \mathbb{Z}[x]$ are primitive, and $a, b, c, d \in \mathbb{Z}^+$.
  Then:
  $$f(x) = \frac{ac}{bd} A_0(x) B_0(x) \implies bd \cdot f(x) = ac \cdot [A_0(x) B_0(x)]$$
  Take the content of both sides:
  $$C(bd \cdot f) = bd \cdot C(f) = bd \cdot 1 = bd$$
  $$C(ac \cdot [A_0 B_0]) = ac \cdot C(A_0 B_0) = ac \cdot 1 = ac \quad (\text{by Gauss's Lemma!})$$
  Therefore, $bd = ac$, which means $\frac{ac}{bd} = 1$!
  Substituting back:
  $$f(x) = A_0(x) B_0(x)$$
  with $A_0(x), B_0(x) \in \mathbb{Z}[x]$ and $\deg(A_0), \deg(B_0) \ge 1$.
  Thus $f(x)$ is reducible in $\mathbb{Z}[x]$.
Taking the contrapositive yields the theorem. $\blacksquare$"""
            },
            {
                "secNumber": "8.4",
                "title": "Eisenstein's Irreducibility Criterion & Cyclotomic Polynomials",
                "content": r"""### 1. Statement of Eisenstein's Criterion

Ferdinand Eisenstein published this celebrated irreducibility test in 1850.

> **Theorem 8.7 (Eisenstein's Irreducibility Criterion):**
> Let $f(x) = a_n x^n + a_{n-1} x^{n-1} + \dots + a_1 x + a_0 \in \mathbb{Z}[x]$ with $n \ge 1$.
> If there exists a prime number $p$ such that:
> 1. $p \nmid a_n$ ($p$ does not divide the leading coefficient),
> 2. $p \mid a_i$ for all $0 \le i \le n - 1$ ($p$ divides every other coefficient),
> 3. $p^2 \nmid a_0$ ($p^2$ does not divide the constant term),
>
> then $f(x)$ is **irreducible** over the field of rational numbers $\mathbb{Q}[x]$.
> (If $f(x)$ is also primitive, it is irreducible in $\mathbb{Z}[x]$.)

---

### 2. Complete Rigorous Proof

Assume for contradiction that $f(x)$ is reducible in $\mathbb{Q}[x]$.
By Theorem 8.6 (Gauss's Theorem), $f(x)$ must factor in $\mathbb{Z}[x]$ into polynomials of lower degree:
$$f(x) = g(x) \cdot h(x)$$
where:
$$g(x) = b_r x^r + \dots + b_1 x + b_0 \in \mathbb{Z}[x], \quad (r \ge 1, \; b_r \ne 0)$$
$$h(x) = c_s x^s + \dots + c_1 x + c_0 \in \mathbb{Z}[x], \quad (s \ge 1, \; c_s \ne 0)$$
with $r + s = n$.

1. **Constant Term Analysis:**
   The constant term of $f(x)$ is $a_0 = b_0 \cdot c_0$.
   By condition (2), $p \mid a_0$. Thus $p \mid (b_0 c_0)$.
   Since $p$ is prime, $p \mid b_0$ or $p \mid c_0$.
   However, by condition (3), $p^2 \nmid a_0$.
   Therefore, $p$ **cannot divide both** $b_0$ and $c_0$!
   Without loss of generality, assume:
   $$p \mid b_0 \quad \text{and} \quad p \nmid c_0$$
2. **Leading Coefficient Analysis:**
   The leading coefficient of $f(x)$ is $a_n = b_r \cdot c_s$.
   By condition (1), $p \nmid a_n$, so $p \nmid b_r$ and $p \nmid c_s$.
3. **The Minimal Index of Non-Divisibility:**
   Since $p \mid b_0$ and $p \nmid b_r$, there must exist a smallest index $k \in \{1, 2, \dots, r\}$ such that:
   $$p \nmid b_k \quad \text{and} \quad p \mid b_j \text{ for all } j < k$$
   Notice $k \le r < n$.
4. **Examine the Coefficient $a_k$:**
   By polynomial multiplication, the coefficient of $x^k$ in $g(x) h(x)$ is:
   $$a_k = b_k c_0 + b_{k-1} c_1 + b_{k-2} c_2 + \dots + b_0 c_k$$
   Rearranging for $b_k c_0$:
   $$b_k c_0 = a_k - [b_{k-1} c_1 + b_{k-2} c_2 + \dots + b_0 c_k]$$
   Now evaluate divisibility by $p$:
   - Since $k < n$, condition (2) states that $p \mid a_k$.
   - By our choice of $k$, $p \mid b_j$ for all $j < k$, so $p$ divides every term in the bracketed sum:
     $$p \mid (b_{k-1} c_1 + \dots + b_0 c_k)$$
   Therefore, $p$ must divide the right-hand side, which implies:
   $$p \mid (b_k c_0)$$
   Since $p$ is prime, this requires $p \mid b_k$ or $p \mid c_0$.
   However, by definition of $k$, $p \nmid b_k$, and by Step 1, $p \nmid c_0$!
   This is a complete contradiction!

Therefore, $f(x)$ cannot be factored into polynomials of lower degree.
Hence $f(x)$ is **irreducible in $\mathbb{Q}[x]$**. $\blacksquare$

---

### 3. Application to Cyclotomic Polynomials

For any prime $p$, the $p$-th cyclotomic polynomial is:
$$\Phi_p(x) = \frac{x^p - 1}{x - 1} = x^{p-1} + x^{p-2} + \dots + x + 1$$

> **Theorem 8.8 (Irreducibility of $\Phi_p(x)$):**
> For every prime number $p$, the cyclotomic polynomial $\Phi_p(x)$ is irreducible over $\mathbb{Q}$.

#### Proof (via the shift $x \mapsto x + 1$):
Substitute $x = y + 1$:
$$\Phi_p(y + 1) = \frac{(y + 1)^p - 1}{(y + 1) - 1} = \frac{(y + 1)^p - 1}{y}$$
Expanding $(y + 1)^p$ using the Binomial Theorem:
$$(y + 1)^p - 1 = y^p + \binom{p}{1} y^{p-1} + \binom{p}{2} y^{p-2} + \dots + \binom{p}{p-1} y$$
Dividing by $y$:
$$\Phi_p(y + 1) = y^{p-1} + \binom{p}{1} y^{p-2} + \binom{p}{2} y^{p-3} + \dots + \binom{p}{p-1}$$
Now apply Eisenstein's Criterion with the prime $p$:
1. Leading coefficient is $1$, and $p \nmid 1$.
2. For all $1 \le k \le p - 1$, the binomial coefficients $\binom{p}{k} = \frac{p!}{k!(p-k)!}$ are divisible by $p$.
3. Constant term is $\binom{p}{p-1} = p$. Clearly $p^2 \nmid p$.
By Theorem 8.7, $\Phi_p(y + 1)$ is irreducible over $\mathbb{Q}$.
Since the substitution $x \mapsto y+1$ is an invertible ring automorphism of $\mathbb{Q}[x]$, $\Phi_p(x)$ is irreducible over $\mathbb{Q}$. $\blacksquare$"""
            },
            {
                "secNumber": "8.5",
                "title": "Field Extensions, Minimal Polynomials & The Tower Law",
                "content": r"""### 1. Field Extensions and Degree

> **Definition 8.4 (Field Extension):**
> If $F$ and $K$ are fields with $F \subseteq K$, we say $K$ is an **extension field** of $F$ (written $K/F$).
> The larger field $K$ can be viewed as a **vector space** over the smaller field $F$, where addition is addition in $K$ and scalar multiplication is multiplication by elements of $F$.
> The dimension of $K$ as an $F$-vector space is called the **degree of the extension**, denoted:
> $$[K : F] = \dim_F(K)$$
> If $[K : F] < \infty$, the extension is called **finite**.

---

### 2. Algebraic vs. Transcendental Elements

> **Definition 8.5 (Algebraic Element):**
> Let $K/F$ be an extension and $\alpha \in K$.
> 1. $\alpha$ is **algebraic** over $F$ if there exists a non-zero polynomial $f(x) \in F[x]$ such that $f(\alpha) = 0$.
> 2. Otherwise, $\alpha$ is **transcendental** over $F$ (e.g., $\pi$ and $e$ over $\mathbb{Q}$).

> **Definition 8.6 (Minimal Polynomial):**
> If $\alpha \in K$ is algebraic over $F$, the unique monic polynomial $m_{\alpha, F}(x) \in F[x]$ of minimal degree having $\alpha$ as a root is called the **minimal polynomial** of $\alpha$ over $F$.
> - $m_{\alpha, F}(x)$ is irreducible over $F$.
> - For any $g(x) \in F[x]$, $g(\alpha) = 0 \iff m_{\alpha, F}(x) \mid g(x)$.
> - The simple extension field is isomorphic to:
>   $$F(\alpha) \cong \frac{F[x]}{\langle m_{\alpha, F}(x) \rangle}$$
>   and its degree is $[F(\alpha) : F] = \deg(m_{\alpha, F})$. A basis is $\{1, \alpha, \alpha^2, \dots, \alpha^{n-1}\}$.

---

### 3. The Tower Law (Degree Multiplication Formula)

The Tower Law is the field-theoretic analogue of Lagrange's Theorem for groups.

> **Theorem 8.9 (The Tower Law):**
> Let $F \subseteq L \subseteq K$ be a tower of field extensions.
> Then $K/F$ is finite if and only if both $K/L$ and $L/F$ are finite, and in that case:
> $$[K : F] = [K : L] \cdot [L : F]$$

```
      K
      |  [K : L] = n
      L
      |  [L : F] = m
      F
  ----------------
   [K : F] = m * n
```

#### Complete Constructive Proof:
Let $[L : F] = m$ and $[K : L] = n$.
Let $\mathcal{B}_L = \{u_1, u_2, \dots, u_m\}$ be a basis of $L$ as an $F$-vector space.
Let $\mathcal{B}_K = \{v_1, v_2, \dots, v_n\}$ be a basis of $K$ as an $L$-vector space.
Consider the set of all $m \cdot n$ products:
$$\mathcal{S} = \{ u_i v_j : 1 \le i \le m, \; 1 \le j \le n \} \subset K$$
We will prove that $\mathcal{S}$ is a basis of $K$ over $F$.

#### Step 1: $\mathcal{S}$ spans $K$ over $F$
Let $\theta \in K$. Since $\mathcal{B}_K$ is a basis for $K$ over $L$, there exist coefficients $\lambda_j \in L$ such that:
$$\theta = \sum_{j=1}^n \lambda_j v_j$$
Since each $\lambda_j \in L$ and $\mathcal{B}_L$ is a basis for $L$ over $F$, each $\lambda_j$ can be written as:
$$\lambda_j = \sum_{i=1}^m a_{ij} u_i, \quad \text{where } a_{ij} \in F$$
Substituting this back into $\theta$:
$$\theta = \sum_{j=1}^n \left( \sum_{i=1}^m a_{ij} u_i \right) v_j = \sum_{j=1}^n \sum_{i=1}^m a_{ij} (u_i v_j)$$
Since $a_{ij} \in F$, this proves that $\theta$ is an $F$-linear combination of the elements in $\mathcal{S}$.
Thus $\text{span}_F(\mathcal{S}) = K$.

#### Step 2: $\mathcal{S}$ is linearly independent over $F$
Suppose there exist scalars $c_{ij} \in F$ such that:
$$\sum_{j=1}^n \sum_{i=1}^m c_{ij} (u_i v_j) = 0$$
Regrouping terms:
$$\sum_{j=1}^n \left( \sum_{i=1}^m c_{ij} u_i \right) v_j = 0$$
Let $\mu_j = \sum_{i=1}^m c_{ij} u_i \in L$.
Then $\sum_{j=1}^n \mu_j v_j = 0$.
Since the set $\{v_1, \dots, v_n\}$ is linearly independent over $L$, all coefficients $\mu_j$ must be zero:
$$\mu_j = \sum_{i=1}^m c_{ij} u_i = 0, \quad \forall j \in \{1, \dots, n\}$$
Now, each equation $\sum_{i=1}^m c_{ij} u_i = 0$ is a linear combination of $\{u_1, \dots, u_m\}$ with coefficients $c_{ij} \in F$.
Since $\{u_1, \dots, u_m\}$ is linearly independent over $F$, all coefficients must be zero:
$$c_{ij} = 0, \quad \forall i \in \{1, \dots, m\}, \; \forall j \in \{1, \dots, n\}$$
Therefore, $\mathcal{S}$ is linearly independent over $F$.

Since $\mathcal{S}$ spans $K$ over $F$ and is linearly independent over $F$, it is a basis for $K$ over $F$.
The number of elements in $\mathcal{S}$ is $m \cdot n$.
Therefore:
$$[K : F] = m \cdot n = [L : F] \cdot [K : L] \quad \blacksquare$$"""
            }
        ],
        "problems": [
            {
                "tier": "Foundational",
                "title": "Irreducibility over $\\mathbb{Q}[x]$ via Eisenstein & Modular Reduction",
                "statement": r"1. Prove that the polynomial $f(x) = 2x^5 - 10x^3 + 15 \in \mathbb{Q}[x]$ is irreducible over $\mathbb{Q}$. 2. Prove that the polynomial $g(x) = x^4 + 1 \in \mathbb{Q}[x]$ is irreducible over $\mathbb{Q}$ using the substitution $x \mapsto x + 1$ and Eisenstein's criterion. 3. Show that $h(x) = x^3 - x + 1$ is irreducible over $\mathbb{Q}$ using reduction modulo 2.",
                "hints": [
                    "For Part 1, check the prime $p = 5$ with Eisenstein's criterion.",
                    "For Part 2, compute $g(x+1) = (x+1)^4 + 1 = x^4 + 4x^3 + 6x^2 + 4x + 2$, and apply Eisenstein with prime $p=2$.",
                    "For Part 3, a degree 3 polynomial is reducible iff it has a root. Test $0$ and $1$ in $\\mathbb{Z}_2$."
                ],
                "solution": r"""**Step 1: Irreducibility of $f(x) = 2x^5 - 10x^3 + 15$**

$f(x) = 2x^5 + 0x^4 - 10x^3 + 0x^2 + 0x + 15 \in \mathbb{Z}[x]$.
Choose the prime $p = 5$:
1. $5 \nmid 2$ ($p$ does not divide the leading coefficient $a_5 = 2$).
2. $5 \mid 0, \; 5 \mid -10, \; 5 \mid 0, \; 5 \mid 0, \; 5 \mid 15$ ($p$ divides all lower coefficients).
3. $5^2 = 25 \nmid 15$ ($p^2$ does not divide the constant term $a_0 = 15$).
All three conditions of Eisenstein's Criterion (Theorem 8.7) are satisfied for $p = 5$.
Therefore, $f(x)$ is **irreducible over $\mathbb{Q}$**.

---

**Step 2: Irreducibility of $g(x) = x^4 + 1$**

Notice $g(x)$ does not immediately satisfy Eisenstein for any prime.
Perform the variable substitution $x = y + 1$:
$$\begin{aligned}
g(y + 1) &= (y + 1)^4 + 1 \\
&= (y^4 + 4y^3 + 6y^2 + 4y + 1) + 1 \\
&= y^4 + 4y^3 + 6y^2 + 4y + 2
\end{aligned}$$
Examine the prime $p = 2$:
1. $2 \nmid 1$ (leading coefficient is 1).
2. $2 \mid 4, \; 2 \mid 6, \; 2 \mid 4, \; 2 \mid 2$ (divides all lower coefficients).
3. $2^2 = 4 \nmid 2$ ($p^2$ does not divide the constant term 2).
By Eisenstein's Criterion with $p = 2$, $g(y + 1)$ is irreducible over $\mathbb{Q}$.
Since the substitution $x \mapsto y+1$ preserves irreducibility, $g(x) = x^4 + 1$ is **irreducible over $\mathbb{Q}$**.

---

**Step 3: Irreducibility of $h(x) = x^3 - x + 1$ via Modular Reduction**

Consider the reduction map modulo $2$: $\pi_2: \mathbb{Z}[x] \to \mathbb{Z}_2[x]$.
$$\bar{h}(x) = x^3 - x + 1 \equiv x^3 + x + 1 \pmod 2$$
Since $\deg(\bar{h}) = 3$, $\bar{h}(x)$ is reducible in $\mathbb{Z}_2[x]$ if and only if it has a root in $\mathbb{Z}_2 = \{0, 1\}$.
Test both values:
- $\bar{h}(0) = 0^3 + 0 + 1 = 1 \ne 0 \pmod 2$
- $\bar{h}(1) = 1^3 + 1 + 1 = 3 \equiv 1 \ne 0 \pmod 2$
Since $\bar{h}(x)$ has no roots in $\mathbb{Z}_2$, it has no linear factors, so it is irreducible in $\mathbb{Z}_2[x]$.
Since the leading coefficient of $h(x)$ is $1 \not\equiv 0 \pmod 2$ and $\bar{h}(x)$ is irreducible in $\mathbb{Z}_2[x]$, $h(x)$ must be **irreducible in $\mathbb{Q}[x]$**. $\blacksquare$"""
            },
            {
                "tier": "Advanced",
                "title": "Minimal Polynomial and Primitive Element of $\\mathbb{Q}(\\sqrt{2}, \\sqrt{3})$",
                "statement": r"1. Determine the degree $[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}]$, write down an explicit vector space basis over $\mathbb{Q}$, and find the minimal polynomial of $\alpha = \sqrt{2} + \sqrt{3}$ over $\mathbb{Q}$. 2. Prove that $\mathbb{Q}(\sqrt{2}, \sqrt{3}) = \mathbb{Q}(\sqrt{2} + \sqrt{3})$ (i.e., $\alpha$ is a primitive element for the extension).",
                "hints": [
                    "Consider the tower $\\mathbb{Q} \\subseteq \\mathbb{Q}(\\sqrt{2}) \\subseteq \\mathbb{Q}(\\sqrt{2}, \\sqrt{3})$. Show $\\sqrt{3} \\notin \\mathbb{Q}(\\sqrt{2})$.",
                    "To find the minimal polynomial, compute $\\alpha^2 = 5 + 2\\sqrt{6}$, isolate $\\sqrt{6}$, and square again.",
                    "To show $\\mathbb{Q}(\\alpha) = \\mathbb{Q}(\\sqrt{2}, \\sqrt{3})$, express $\\sqrt{2}$ and $\\sqrt{3}$ as polynomials in $\\alpha$."
                ],
                "solution": r"""**Step 1: Degree and Basis of $\mathbb{Q}(\sqrt{2}, \sqrt{3})/\mathbb{Q}$**

Consider the field tower:
$$\mathbb{Q} \subset \mathbb{Q}(\sqrt{2}) \subset \mathbb{Q}(\sqrt{2}, \sqrt{3})$$
1. **$[\mathbb{Q}(\sqrt{2}) : \mathbb{Q}]$:**
   The minimal polynomial of $\sqrt{2}$ over $\mathbb{Q}$ is $x^2 - 2$ (irreducible by Eisenstein with $p=2$).
   Thus $[\mathbb{Q}(\sqrt{2}) : \mathbb{Q}] = 2$, with basis $\{1, \sqrt{2}\}$.
2. **$[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}(\sqrt{2})]$:**
   $\sqrt{3}$ satisfies $x^2 - 3 \in \mathbb{Q}(\sqrt{2})[x]$.
   Does $\sqrt{3} \in \mathbb{Q}(\sqrt{2})$?
   Suppose $\sqrt{3} = a + b\sqrt{2}$ for $a, b \in \mathbb{Q}$.
   Squaring both sides:
   $$3 = a^2 + 2b^2 + 2ab\sqrt{2}$$
   If $ab \ne 0$, then $\sqrt{2} = \frac{3 - a^2 - 2b^2}{2ab} \in \mathbb{Q}$, a contradiction!
   If $b = 0$, then $a^2 = 3$, impossible in $\mathbb{Q}$.
   If $a = 0$, then $2b^2 = 3 \implies b^2 = 3/2$, impossible in $\mathbb{Q}$.
   Thus $\sqrt{3} \notin \mathbb{Q}(\sqrt{2})$.
   Therefore, $x^2 - 3$ is irreducible over $\mathbb{Q}(\sqrt{2})$, so:
   $$[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}(\sqrt{2})] = 2$$
3. **Application of Tower Law:**
   $$[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}] = [\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}(\sqrt{2})] \cdot [\mathbb{Q}(\sqrt{2}) : \mathbb{Q}] = 2 \cdot 2 = 4$$
   By the proof of the Tower Law, an explicit basis over $\mathbb{Q}$ is the product of bases:
   $$\mathcal{B} = \{1 \cdot 1, \; \sqrt{2} \cdot 1, \; 1 \cdot \sqrt{3}, \; \sqrt{2} \cdot \sqrt{3}\} = \{1, \sqrt{2}, \sqrt{3}, \sqrt{6}\}$$

---

**Step 2: Minimal Polynomial of $\alpha = \sqrt{2} + \sqrt{3}$**

Compute powers of $\alpha$:
$$\alpha = \sqrt{2} + \sqrt{3}$$
$$\alpha^2 = (\sqrt{2} + \sqrt{3})^2 = 2 + 2\sqrt{6} + 3 = 5 + 2\sqrt{6}$$
Isolate $\sqrt{6}$:
$$\alpha^2 - 5 = 2\sqrt{6}$$
Square both sides:
$$(\alpha^2 - 5)^2 = (2\sqrt{6})^2 \implies \alpha^4 - 10\alpha^2 + 25 = 24$$
$$\alpha^4 - 10\alpha^2 + 1 = 0$$
Let $m(x) = x^4 - 10x^2 + 1 \in \mathbb{Q}[x]$.
The roots of $m(x)$ are $\pm \sqrt{2} \pm \sqrt{3}$.
None of these roots are rational, so $m(x)$ has no linear factors.
Could it factor into two quadratics $(x^2 + ax + b)(x^2 + cx + d)$?
Grouping roots: $(\alpha - (\sqrt{2}+\sqrt{3}))(\alpha - (-\sqrt{2}-\sqrt{3})) = \alpha^2 - (5 + 2\sqrt{6}) \notin \mathbb{Q}[\alpha]$.
All combinations of quadratic factors have irrational coefficients.
Thus $m(x) = x^4 - 10x^2 + 1$ is irreducible over $\mathbb{Q}$.
Therefore, $m(x)$ is the **minimal polynomial** of $\alpha$ over $\mathbb{Q}$, and $[\mathbb{Q}(\alpha) : \mathbb{Q}] = 4$.

---

**Step 3: Proof that $\mathbb{Q}(\sqrt{2}, \sqrt{3}) = \mathbb{Q}(\sqrt{2} + \sqrt{3})$**

Clearly $\alpha = \sqrt{2} + \sqrt{3} \in \mathbb{Q}(\sqrt{2}, \sqrt{3})$, so:
$$\mathbb{Q}(\alpha) \subseteq \mathbb{Q}(\sqrt{2}, \sqrt{3})$$
Since $[\mathbb{Q}(\alpha) : \mathbb{Q}] = 4$ and $[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}] = 4$:
$$[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}(\alpha)] = \frac{[\mathbb{Q}(\sqrt{2}, \sqrt{3}) : \mathbb{Q}]}{[\mathbb{Q}(\alpha) : \mathbb{Q}]} = \frac{4}{4} = 1$$
Therefore:
$$\mathbb{Q}(\sqrt{2}, \sqrt{3}) = \mathbb{Q}(\sqrt{2} + \sqrt{3})$$

Alternatively, we can express $\sqrt{2}$ and $\sqrt{3}$ directly as polynomials in $\alpha$:
From $\alpha^2 - 5 = 2\sqrt{6}$, multiply by $\alpha$:
$$\alpha(\alpha^2 - 5) = (\sqrt{2} + \sqrt{3})(2\sqrt{6}) = 2\sqrt{12} + 2\sqrt{18} = 4\sqrt{3} + 6\sqrt{2}$$
We have the system of linear equations:
$$\begin{aligned}
\alpha^3 - 5\alpha &= 6\sqrt{2} + 4\sqrt{3} \\
9\alpha &= 9\sqrt{2} + 9\sqrt{3}
\end{aligned}$$
Subtracting $9\alpha - (\alpha^3 - 5\alpha)$:
$$14\alpha - \alpha^3 = 3\sqrt{2} + 5\sqrt{3}$$
Solving for $\sqrt{2}$:
$$\sqrt{2} = \frac{\alpha^3 - 9\alpha}{2} \in \mathbb{Q}(\alpha)$$
$$\sqrt{3} = \alpha - \sqrt{2} = \frac{11\alpha - \alpha^3}{2} \in \mathbb{Q}(\alpha)$$
Thus both generators belong to $\mathbb{Q}(\alpha)$. $\blacksquare$"""
            },
            {
                "tier": "Honors / Proof Challenge",
                "title": "Classical Impossibility Proofs: Doubling the Cube & Trisecting the Angle",
                "statement": r"1. Let $F_0 = \mathbb{Q}$, and let $F_0 \subset F_1 \subset \dots \subset F_k = K$ be a sequence of field extensions obtained by straightedge and compass constructions (where each step corresponds to the intersection of lines and circles). Prove that $[K : \mathbb{Q}] = 2^k$ for some non-negative integer $k$, and deduce that any constructible real number $\gamma$ must have degree $[\mathbb{Q}(\gamma) : \mathbb{Q}] = 2^m$ for some $m \le k$. 2. Use this criterion to prove the impossibility of Doubling the Cube (Delian problem). 3. Prove the impossibility of Trisecting an arbitrary angle (specifically, trisecting $60^\circ$ to construct $\cos(20^\circ)$).",
                "hints": [
                    "Intersections of lines and circles involve at most quadratic equations, so $[F_{i+1} : F_i] \\in \\{1, 2\\}$. Apply the Tower Law.",
                    "Doubling a unit cube requires constructing a side length of $\\sqrt[3]{2}$. What is the degree of $\\sqrt[3]{2}$ over $\\mathbb{Q}$?",
                    "Recall the triple-angle identity $\\cos(3\\theta) = 4\\cos^3(\\theta) - 3\\cos(\\theta)$. For $\\theta = 20^\\circ$, setting $x = 2\\cos(20^\\circ)$ yields $x^3 - 3x - 1 = 0$."
                ],
                "solution": r"""**Part 1: The Degree of Constructible Numbers**

In Euclidean geometry with straightedge and compass:
- A line is determined by two points $(x_1, y_1), (x_2, y_2)$ in a field $F$. Its equation is linear: $ax + by + c = 0$ with $a, b, c \in F$.
- A circle is determined by a center and a radius squared in $F$. Its equation is quadratic: $(x - x_0)^2 + (y - y_0)^2 = r^2$ with $x_0, y_0, r^2 \in F$.

New points are formed by three types of geometric intersections:
1. **Intersection of two lines:** Solved via linear systems. The intersection coordinates belong to $F$, so $[F_{new} : F] = 1$.
2. **Intersection of a line and a circle:** Substituting the linear equation into the circle yields a single quadratic equation in one variable: $A x^2 + B x + C = 0$ with coefficients in $F$. The solutions lie in a quadratic extension $F(\sqrt{D})$, so $[F_{new} : F] \in \{1, 2\}$.
3. **Intersection of two circles:** Subtracting the two circle equations cancels the quadratic terms $x^2 + y^2$, reducing to the intersection of a line with a circle. Thus $[F_{new} : F] \in \{1, 2\}$.

Therefore, any sequence of straightedge and compass constructions corresponds to a tower of field extensions:
$$\mathbb{Q} = F_0 \subseteq F_1 \subseteq F_2 \subseteq \dots \subseteq F_k$$
where $[F_{i+1} : F_i] \in \{1, 2\}$ for all $i = 0, \dots, k-1$.
By repeated application of the **Tower Law** (Theorem 8.9):
$$[F_k : \mathbb{Q}] = [F_k : F_{k-1}][F_{k-1} : F_{k-2}] \cdots [F_1 : F_0] = 2^k$$
If a real number $\gamma$ is constructible, then $\gamma \in F_k$ for some such construction tower.
Considering the subfield $\mathbb{Q}(\gamma)$:
$$[F_k : \mathbb{Q}] = [F_k : \mathbb{Q}(\gamma)] \cdot [\mathbb{Q}(\gamma) : \mathbb{Q}]$$
Since $[F_k : \mathbb{Q}] = 2^k$, $[\mathbb{Q}(\gamma) : \mathbb{Q}]$ must divide $2^k$.
Therefore:
$$[\mathbb{Q}(\gamma) : \mathbb{Q}] = 2^m \quad \text{for some integer } m \ge 0$$
**Constructibility Criterion:** A real number $\gamma$ can be constructed with straightedge and compass only if its degree over $\mathbb{Q}$ is a power of 2!

---

**Part 2: Impossibility of Doubling the Cube**

The original cube has volume $V_1 = 1^3 = 1$.
A cube of double the volume must have volume $V_2 = 2$.
Its side length is:
$$s = \sqrt[3]{2}$$
The minimal polynomial of $s$ over $\mathbb{Q}$ is $f(x) = x^3 - 2$.
By Eisenstein's Criterion (Theorem 8.7) with prime $p = 2$:
- $2 \nmid 1$
- $2 \mid 0, \; 2 \mid 0, \; 2 \mid -2$
- $2^2 = 4 \nmid -2$
Thus $x^3 - 2$ is irreducible over $\mathbb{Q}$.
The degree of $\sqrt[3]{2}$ over $\mathbb{Q}$ is:
$$[\mathbb{Q}(\sqrt[3]{2}) : \mathbb{Q}] = \deg(x^3 - 2) = 3$$
Since $3$ is **NOT a power of 2** ($3 \ne 2^m$ for any $m \in \mathbb{Z}_{\ge 0}$), $\sqrt[3]{2}$ fails the Constructibility Criterion.
Therefore, it is impossible to double the cube with straightedge and compass. $\blacksquare$

---

**Part 3: Impossibility of Trisecting an Arbitrary Angle**

An angle $\theta$ is constructible if and only if $\cos(\theta)$ is a constructible number.
The angle $60^\circ$ is easily constructible (from an equilateral triangle), with $\cos(60^\circ) = 1/2$.
If all angles could be trisected, then $60^\circ$ could be trisected to produce $20^\circ$.
We test whether $\cos(20^\circ)$ is constructible.

Recall the triple-angle trigonometric identity:
$$\cos(3\theta) = 4\cos^3(\theta) - 3\cos(\theta)$$
Setting $\theta = 20^\circ$, so $3\theta = 60^\circ$:
$$\cos(60^\circ) = 4\cos^3(20^\circ) - 3\cos(20^\circ) \implies \frac{1}{2} = 4\cos^3(20^\circ) - 3\cos(20^\circ)$$
Multiply by 2:
$$8\cos^3(20^\circ) - 6\cos(20^\circ) - 1 = 0$$
Let $u = 2\cos(20^\circ)$. Then $(2\cos(20^\circ))^3 - 3(2\cos(20^\circ)) - 1 = 0$:
$$u^3 - 3u - 1 = 0$$
Let $p(x) = x^3 - 3x - 1 \in \mathbb{Z}[x]$.
By the Rational Root Theorem, the only possible rational roots of $p(x)$ are $\pm 1$:
- $p(1) = 1^3 - 3(1) - 1 = -3 \ne 0$
- $p(-1) = (-1)^3 - 3(-1) - 1 = 1 \ne 0$
Since $p(x)$ has degree 3 and no rational roots, it is **irreducible over $\mathbb{Q}$**.
Therefore, $p(x)$ is the minimal polynomial of $u = 2\cos(20^\circ)$ over $\mathbb{Q}$.
Thus:
$$[\mathbb{Q}(u) : \mathbb{Q}] = \deg(p) = 3$$
Since $3$ is **NOT a power of 2**, $u = 2\cos(20^\circ)$ is not constructible, which implies $\cos(20^\circ)$ is not constructible.
Therefore, the angle $60^\circ$ cannot be trisected with straightedge and compass.
Consequently, general angle trisection is impossible. $\blacksquare$"""
            }
        ]
    }
    return u8

if __name__ == "__main__":
    u = get_unit8()
    print("Unit 8 generated successfully:", u["title"])
    print("Sections:", len(u["sections"]))
    print("Problems:", len(u["problems"]))
