import json

def build_unit_5():
    return {
        "id": "geom3d-u5",
        "title": "Unit 5: Cones and Cylinders",
        "description": "Rigorous investigation of quadric ruled surfaces: homogeneous cones with vertex at origin, conditions for general quadric cones, right circular cones and cylinders, and enveloping surfaces.",
        "sections": [
            {
                "id": "sec-geom3d-5-1",
                "title": "5.1 Cones with Vertex at the Origin and General Conic Surfaces",
                "content": r"""### 1. Geometric Definition of a Cone

A **cone** is a surface generated by a moving straight line (called a **generator**) which passes through a fixed point (called the **vertex**) and continually intersects a fixed space curve (called the **guiding curve**).

---

### 2. Theorem: Cones with Vertex at the Origin

**Theorem:**  
Every homogeneous polynomial equation of degree two in $x, y, z$:

$$a x^2 + b y^2 + c z^2 + 2f yz + 2g zx + 2h xy = 0$$

represents a cone whose vertex is at the origin $(0, 0, 0)$.

#### Proof:
Let $P(x_1, y_1, z_1)$ be any point lying on the surface, so that:

$$a x_1^2 + b y_1^2 + c z_1^2 + 2f y_1 z_1 + 2g z_1 x_1 + 2h x_1 y_1 = 0 \quad \text{--- (1)}$$

Consider the straight line connecting the origin $O(0, 0, 0)$ to $P(x_1, y_1, z_1)$. The coordinates of any arbitrary point $Q$ on this line are given by $(t x_1, t y_1, t z_1)$ for any scalar parameter $t \in \mathbb{R}$.

Substitute the coordinates of $Q$ into the left-hand side of the quadratic equation:

$$\text{LHS} = a (tx_1)^2 + b (ty_1)^2 + c (tz_1)^2 + 2f (ty_1)(tz_1) + 2g (tz_1)(tx_1) + 2h (tx_1)(ty_1)$$
$$= t^2 \left( a x_1^2 + b y_1^2 + c z_1^2 + 2f y_1 z_1 + 2g z_1 x_1 + 2h x_1 y_1 \right)$$

By equation (1), the bracketed expression is identically zero. Therefore:

$$\text{LHS} = t^2 (0) = 0 \quad \forall t \in \mathbb{R}$$

This proves that every point on the line $OP$ lies entirely on the surface. Since this holds for every point $P$ on the surface, the surface is generated by a family of straight lines all passing through the origin. Hence, it is a cone with vertex $(0, 0, 0)$. $\blacksquare$

---

### 3. General Second-Degree Equation Representing a Cone

Consider the general quadratic equation:

$$F(x, y, z) = ax^2 + by^2 + cz^2 + 2fyz + 2gzx + 2hxy + 2ux + 2vy + 2wz + d = 0$$

If this represents a cone with vertex $V(\alpha, \beta, \gamma)$, shifting the origin to $(\alpha, \beta, \gamma)$ via $x = X + \alpha$, $y = Y + \beta$, $z = Z + \gamma$ must eliminate all linear and constant terms, yielding a homogeneous quadratic in $X, Y, Z$.

This requirement is equivalent to the simultaneous vanishing of all partial derivatives at the vertex:

$$\frac{\partial F}{\partial x} = 2(ax + hy + gz + u) = 0 \implies ax + hy + gz + u = 0$$
$$\frac{\partial F}{\partial y} = 2(hx + by + fz + v) = 0 \implies hx + by + fz + v = 0$$
$$\frac{\partial F}{\partial z} = 2(gx + fy + cz + w) = 0 \implies gx + fy + cz + w = 0$$
$$\text{and } ux + vy + wz + d = 0$$

For these four linear equations in $(\alpha, \beta, \gamma, 1)$ to have a consistent non-trivial solution, the $4 \times 4$ determinant of coefficients must vanish:

$$\begin{vmatrix}
a & h & g & u \\
h & b & f & v \\
g & f & c & w \\
u & v & w & d
\end{vmatrix} = 0$$

This is the **necessary and sufficient condition** for the general quadratic equation to represent a cone."""
            },
            {
                "id": "sec-geom3d-5-2",
                "title": "5.2 The Right Circular Cone",
                "content": r"""### 1. Geometric Definition

A **right circular cone** is a surface generated by a line passing through a fixed vertex, maintaining a constant angle $\alpha$ (the **semi-vertical angle**) with a fixed line through the vertex (the **axis**).

---

### 2. Analytical Derivation of the Equation

Let:
- Vertex: $V(\alpha_v, \beta_v, \gamma_v)$
- Axis: Line passing through $V$ with direction cosines $(l, m, n)$ (where $l^2 + m^2 + n^2 = 1$)
- Semi-vertical angle: $\alpha$ ($0 < \alpha < \frac{\pi}{2}$)

Let $P(x, y, z)$ be any point on the cone. The generator line $VP$ has direction ratios:

$$\vec{VP} = (x - \alpha_v)\hat{i} + (y - \beta_v)\hat{j} + (z - \gamma_v)\hat{k}$$

The cosine of the angle between $\vec{VP}$ and the axis vector $\vec{A} = (l, m, n)$ is $\cos\alpha$:

$$\cos\alpha = \frac{\vec{VP} \cdot \vec{A}}{|\vec{VP}| |\vec{A}|} = \frac{l(x - \alpha_v) + m(y - \beta_v) + n(z - \gamma_v)}{\sqrt{(x - \alpha_v)^2 + (y - \beta_v)^2 + (z - \gamma_v)^2} \sqrt{l^2 + m^2 + n^2}}$$

Squaring both sides and setting $l^2 + m^2 + n^2 = 1$:

$$\mathbf{\left[ l(x - \alpha_v) + m(y - \beta_v) + n(z - \gamma_v) \right]^2 = \left[ (x - \alpha_v)^2 + (y - \beta_v)^2 + (z - \gamma_v)^2 \right] \cos^2\alpha}$$

#### Canonical Case (Vertex at Origin, Axis along Z-Axis):
If $V = (0, 0, 0)$ and the axis is the $z$-axis $(l=0, m=0, n=1)$:

$$[0 + 0 + z]^2 = (x^2 + y^2 + z^2)\cos^2\alpha$$
$$z^2 = (x^2 + y^2 + z^2)\cos^2\alpha$$
$$z^2 (1 - \cos^2\alpha) = (x^2 + y^2)\cos^2\alpha$$
$$z^2 \sin^2\alpha = (x^2 + y^2)\cos^2\alpha$$

$$\mathbf{x^2 + y^2 = z^2 \tan^2\alpha}$$

This is the familiar standard equation of a right circular cone."""
            },
            {
                "id": "sec-geom3d-5-3",
                "title": "5.3 Cylinders and Enveloping Cones/Cylinders",
                "content": r"""### 1. The General Cylinder

A **cylinder** is a surface generated by a straight line (the **generator**) that moves parallel to a fixed given direction and continually intersects a fixed guiding curve.

#### Equation with Generators Parallel to Given Line:
Let the generators have direction ratios $(l, m, n)$, and let the guiding curve be a plane conic in $z = 0$:

$$f(x, y) = ax^2 + 2hxy + by^2 + 2gx + 2fy + c = 0, \quad z = 0$$

Let $P(x, y, z)$ be any point on the cylinder. The generator through $P$ has equations:

$$\frac{X - x}{l} = \frac{Y - y}{m} = \frac{Z - z}{n}$$

This line pierces the plane $Z = 0$ when:

$$\frac{X - x}{l} = \frac{Y - y}{m} = \frac{-z}{n} \implies X = x - \frac{l}{n}z, \quad Y = y - \frac{m}{n}z$$

Since $(X, Y, 0)$ lies on the guiding curve $f(X, Y) = 0$, substitute $X$ and $Y$:

$$f\left( x - \frac{l}{n}z, \; y - \frac{m}{n}z \right) = 0$$

Expanding this gives the Cartesian equation of the cylinder.

---

### 2. Right Circular Cylinder

A cylinder whose guiding curve is a circle and whose generators are perpendicular to the plane of the circle is a **right circular cylinder**.

If the axis is the line $\frac{x - x_0}{l} = \frac{y - y_0}{m} = \frac{z - z_0}{n}$ (with $l^2+m^2+n^2=1$) and radius is $r$, the perpendicular distance from any point $P(x, y, z)$ to the axis equals $r$:

$$|\vec{AP} \times \hat{u}|^2 = r^2$$

$$\left[ (x - x_0)^2 + (y - y_0)^2 + (z - z_0)^2 \right] - \left[ l(x - x_0) + m(y - y_0) + n(z - z_0) \right]^2 = r^2$$

---

### 3. Enveloping Cone and Enveloping Cylinder of a Sphere

#### Enveloping Cone:
The locus of tangent lines drawn from an external point $V(x_1, y_1, z_1)$ to a sphere $S: x^2 + y^2 + z^2 + 2ux + 2vy + 2wz + d = 0$ is called the **enveloping cone**.

By Joachimsthal's quadratic method, if a line through $V$ touches the sphere, the quadratic equation for the intersection points has equal roots (discriminant $\Delta = 0$). This yields the fundamental relation:

$$\mathbf{S \cdot S_1 = T^2}$$

where:
- $S = x^2 + y^2 + z^2 + 2ux + 2vy + 2wz + d$
- $S_1 = x_1^2 + y_1^2 + z_1^2 + 2ux_1 + 2vy_1 + 2wz_1 + d$
- $T = x x_1 + y y_1 + z z_1 + u(x + x_1) + v(y + y_1) + w(z + z_1) + d$

#### Enveloping Cylinder:
Similarly, the locus of tangent lines to a sphere $S = 0$ parallel to a fixed direction $(l, m, n)$ is the **enveloping cylinder** of the sphere."""
            }
        ],
        "simulations": [
            {
                "id": "sim_geom3d_cones_cylinders",
                "title": "3D Interactive Quadric Cone & Cylinder Generator",
                "description": "Explore 3D geometric surfaces. Adjust semi-vertical angles, cylinder radii, and generator tilt to see wireframe quadrics generated in real time.",
                "controls": [
                    {"param": "surfaceType", "label": "Surface (0:Cone, 1:Cylinder)", "min": 0, "max": 1, "step": 1, "default": 0},
                    {"param": "angle", "label": "Semi-Vertical Angle / Radius", "min": 15, "max": 75, "step": 1, "default": 35},
                    {"param": "tilt", "label": "Axis Tilt (°)", "min": -45, "max": 45, "step": 1, "default": 15},
                    {"param": "height", "label": "Surface Height", "min": 2, "max": 8, "step": 0.5, "default": 5}
                ]
            }
        ],
        "problems": [
            {
                "id": "prob-geom3d-5-1",
                "tier": 1,
                "title": "Right Circular Cone with Given Axis and Vertex",
                "statement": r"""Find the equation of the right circular cone whose vertex is at the point $V(1, 2, 3)$, whose axis has direction ratios $(2, -1, 2)$, and whose semi-vertical angle is $\alpha = 45^\circ$.""",
                "solution": r"""**Step 1: Compute the direction cosines of the axis**  
The direction ratios are $(2, -1, 2)$. The magnitude is:
$$\sqrt{2^2 + (-1)^2 + 2^2} = \sqrt{4 + 1 + 4} = \sqrt{9} = 3$$

Direction cosines: $(l, m, n) = \left(\frac{2}{3}, -\frac{1}{3}, \frac{2}{3}\right)$.

---

**Step 2: Set up the angle condition**  
Let $P(x, y, z)$ be any point on the cone. The vector from vertex $V(1, 2, 3)$ to $P$ is:
$$\vec{VP} = (x - 1)\hat{i} + (y - 2)\hat{j} + (z - 3)\hat{k}$$

The cosine of the angle between $\vec{VP}$ and the axis is $\cos 45^\circ = \frac{1}{\sqrt{2}}$:
$$\cos 45^\circ = \frac{\frac{2}{3}(x - 1) - \frac{1}{3}(y - 2) + \frac{2}{3}(z - 3)}{\sqrt{(x - 1)^2 + (y - 2)^2 + (z - 3)^2}}$$

Multiplying both sides by 3:
$$\frac{1}{\sqrt{2}} \cdot 3 \sqrt{(x - 1)^2 + (y - 2)^2 + (z - 3)^2} = [2(x - 1) - (y - 2) + 2(z - 3)]$$

---

**Step 3: Square both sides**  
$$\frac{9}{2} \left[ (x - 1)^2 + (y - 2)^2 + (z - 3)^2 \right] = [2x - y + 2z - (2 - 2 + 6)]^2$$
$$\frac{9}{2} \left[ (x - 1)^2 + (y - 2)^2 + (z - 3)^2 \right] = (2x - y + 2z - 6)^2$$

Multiply by 2:
$$9 \left[ (x - 1)^2 + (y - 2)^2 + (z - 3)^2 \right] = 2(2x - y + 2z - 6)^2$$

This is the exact Cartesian equation of the right circular cone."""
            },
            {
                "id": "prob-geom3d-5-2",
                "tier": 2,
                "title": "Cylinder with Elliptic Guiding Curve",
                "statement": r"""Find the equation of the cylinder whose generators are parallel to the line:
$$\frac{x}{1} = \frac{y}{2} = \frac{z}{3}$$
and whose guiding curve is the ellipse in the $xy$-plane given by:
$$x^2 + 2y^2 = 1, \qquad z = 0$$""",
                "solution": r"""**Step 1: Set up the generator line through an arbitrary point**  
Let $P(x, y, z)$ be an arbitrary point on the cylinder. The generators have direction ratios $(l, m, n) = (1, 2, 3)$.

The equations of the generator line passing through $P(x, y, z)$ are:
$$\frac{X - x}{1} = \frac{Y - y}{2} = \frac{Z - z}{3}$$

---

**Step 2: Find the point of intersection with $Z = 0$**  
Setting $Z = 0$:
$$\frac{X - x}{1} = \frac{Y - y}{2} = \frac{-z}{3}$$

Solving for $X$ and $Y$:
$$X = x - \frac{z}{3}$$
$$Y = y - \frac{2z}{3}$$

---

**Step 3: Impose the guiding curve condition**  
The intersection point $(X, Y, 0)$ must satisfy the ellipse equation $X^2 + 2Y^2 = 1$:
$$\left(x - \frac{z}{3}\right)^2 + 2\left(y - \frac{2z}{3}\right)^2 = 1$$

Expanding:
$$\left(\frac{3x - z}{3}\right)^2 + 2\left(\frac{3y - 2z}{3}\right)^2 = 1$$
$$\frac{(3x - z)^2}{9} + \frac{2(3y - 2z)^2}{9} = 1$$

Multiply through by 9:
$$(3x - z)^2 + 2(3y - 2z)^2 = 9$$

Expanding each squared term:
$$(9x^2 - 6xz + z^2) + 2(9y^2 - 12yz + 4z^2) = 9$$
$$9x^2 + 18y^2 + z^2 + 8z^2 - 6xz - 24yz = 9$$
$$9x^2 + 18y^2 + 9z^2 - 6xz - 24yz - 9 = 0$$

Dividing the entire equation by 3:
$$3x^2 + 6y^2 + 3z^2 - 2xz - 8yz - 3 = 0$$

This is the exact Cartesian equation of the cylinder."""
            },
            {
                "id": "prob-geom3d-5-3",
                "tier": 3,
                "title": "Enveloping Cone of a Sphere: Derivation and Exact Form",
                "statement": r"""Find the equation of the enveloping cone of the sphere:
$$S: x^2 + y^2 + z^2 - 2x + 4y = 1$$
with vertex at the external point $V(1, 1, 1)$. Verify that the vertex satisfies the tangency envelope condition.""",
                "solution": r"""**Step 1: Write the sphere equation and compute $S_1$ and $T$**  
The sphere is $S(x, y, z) = x^2 + y^2 + z^2 - 2x + 4y - 1 = 0$.

For vertex $V(x_1, y_1, z_1) = (1, 1, 1)$:
$$S_1 = S(1, 1, 1) = 1^2 + 1^2 + 1^2 - 2(1) + 4(1) - 1 = 3 - 2 + 4 - 1 = 4$$

Now evaluate the tangent form $T(x, y, z)$:
$$T = x x_1 + y y_1 + z z_1 - (x + x_1) + 2(y + y_1) - 1$$
Substitute $x_1 = 1, y_1 = 1, z_1 = 1$:
$$T = x(1) + y(1) + z(1) - (x + 1) + 2(y + 1) - 1$$
$$T = x + y + z - x - 1 + 2y + 2 - 1 = 3y + z$$

---

**Step 2: Apply the Joachimsthal Envelope Formula $S S_1 = T^2$**  
$$S \cdot S_1 = T^2$$
$$(x^2 + y^2 + z^2 - 2x + 4y - 1)(4) = (3y + z)^2$$

Expand both sides:
$$\text{LHS} = 4x^2 + 4y^2 + 4z^2 - 8x + 16y - 4$$
$$\text{RHS} = 9y^2 + 6yz + z^2$$

---

**Step 3: Collect all terms on one side**  
$$4x^2 + (4 - 9)y^2 + (4 - 1)z^2 - 6yz - 8x + 16y - 4 = 0$$
$$4x^2 - 5y^2 + 3z^2 - 6yz - 8x + 16y - 4 = 0$$

---

**Step 4: Verification of Vertex**  
Check if $V(1, 1, 1)$ lies on this quadric:
$$4(1)^2 - 5(1)^2 + 3(1)^2 - 6(1)(1) - 8(1) + 16(1) - 4$$
$$= 4 - 5 + 3 - 6 - 8 + 16 - 4 = 23 - 23 = 0 \quad \checkmark$$

Thus, the equation of the enveloping cone is:
$$4x^2 - 5y^2 + 3z^2 - 6yz - 8x + 16y - 4 = 0$$"""
            }
        ]
    }

def build_unit_6():
    return {
        "id": "geom3d-u6",
        "title": "Unit 6: Central and Non-Central Conicoids",
        "description": "Comprehensive classification and properties of quadric surfaces: ellipsoids, hyperboloids of one and two sheets, elliptic and hyperbolic paraboloids, tangent planes, polar planes, and director spheres.",
        "sections": [
            {
                "id": "sec-geom3d-6-1",
                "title": "6.1 Canonical Classification of Central Quadrics",
                "content": r"""A **conicoid** (or **quadric surface**) is the locus of an equation of the second degree in three variables $x, y, z$. When a center of symmetry exists, the surface is called a **central conicoid**.

By an appropriate choice of orthogonal coordinate axes aligned with the principal axes of symmetry, every central conicoid can be reduced to the canonical form:

$$A x^2 + B y^2 + C z^2 = 1$$

where $a, b, c > 0$ are the semi-axes.

---

### 1. The Ellipsoid

$$\mathbf{\frac{x^2}{a^2} + \frac{y^2}{b^2} + \frac{z^2}{c^2} = 1}$$

- **Geometry:** A closed, bounded convex surface contained entirely within the box $[-a, a] \times [-b, b] \times [-c, c]$.
- **Planar Sections:** Every planar section $z = k$ with $|k| < c$ is an ellipse:
  $$\frac{x^2}{a^2(1 - k^2/c^2)} + \frac{y^2}{b^2(1 - k^2/c^2)} = 1$$
- **Volume:** $V = \frac{4}{3}\pi abc$.

---

### 2. Hyperboloid of One Sheet

$$\mathbf{\frac{x^2}{a^2} + \frac{y^2}{b^2} - \frac{z^2}{c^2} = 1}$$

- **Geometry:** A connected, unbounded surface shaped like a cooling tower or hourglass.
- **Planar Sections:**
  - Horizontal sections $z = k$ are ellipses $\frac{x^2}{a^2} + \frac{y^2}{b^2} = 1 + \frac{k^2}{c^2}$, expanding as $|k|$ increases. The smallest ellipse occurs at the waist ($z = 0$), known as the **principal elliptic section**.
  - Vertical sections $x = k$ or $y = k$ are hyperbolas.
- **Doubly Ruled Surface:** Through every point on the hyperboloid of one sheet, there pass **two distinct straight lines** lying entirely within the surface! The two ruling families are:
  $$\begin{cases} \frac{x}{a} - \frac{z}{c} = \lambda\left(1 - \frac{y}{b}\right) \\ \frac{x}{a} + \frac{z}{c} = \frac{1}{\lambda}\left(1 + \frac{y}{b}\right) \end{cases} \quad \text{and} \quad \begin{cases} \frac{x}{a} + \frac{z}{c} = \mu\left(1 - \frac{y}{b}\right) \\ \frac{x}{a} - \frac{z}{c} = \frac{1}{\mu}\left(1 + \frac{y}{b}\right) \end{cases}$$

---

### 3. Hyperboloid of Two Sheets

$$\mathbf{\frac{x^2}{a^2} - \frac{y^2}{b^2} - \frac{z^2}{c^2} = 1} \quad \iff \quad \frac{x^2}{a^2} - 1 = \frac{y^2}{b^2} + \frac{z^2}{c^2}$$

- **Geometry:** A disconnected surface consisting of two separate convex sheets separated by a gap of length $2a$ along the $x$-axis.
- **Regions:** No real points exist for $|x| < a$. For $|x| \ge a$, planar sections perpendicular to the $x$-axis are ellipses."""
            },
            {
                "id": "sec-geom3d-6-2",
                "title": "6.2 Non-Central Conicoids (Paraboloids)",
                "content": r"""When one of the quadratic terms vanishes and a linear term appears, the surface possesses no center of symmetry. These are the **paraboloids**.

---

### 1. The Elliptic Paraboloid

$$\mathbf{\frac{x^2}{a^2} + \frac{y^2}{b^2} = \frac{2z}{c}} \quad (c > 0)$$

- **Geometry:** A cup- or bowl-shaped surface extending infinitely in the positive $z$-direction ($z \ge 0$).
- **Planar Sections:**
  - Horizontal slices $z = k > 0$ yield ellipses: $\frac{x^2}{a^2} + \frac{y^2}{b^2} = \frac{2k}{c}$.
  - Vertical slices parallel to the $xz$-plane ($y = k_y$) yield parabolas opening upwards: $z = \frac{c}{2a^2}x^2 + \text{const}$.
  - Vertical slices parallel to the $yz$-plane ($x = k_x$) also yield parabolas opening upwards.
- **Vertex:** The origin $(0, 0, 0)$ is the unique vertex and absolute minimum.

---

### 2. The Hyperbolic Paraboloid (Saddle Surface)

$$\mathbf{\frac{x^2}{a^2} - \frac{y^2}{b^2} = \frac{2z}{c}} \quad (c > 0)$$

- **Geometry:** A saddle-shaped surface featuring a mountain pass or minimax point at the origin $(0, 0, 0)$.
- **Planar Sections:**
  - Horizontal slices $z = k > 0$ yield hyperbolas opening along the $x$-axis.
  - Horizontal slices $z = k < 0$ yield hyperbolas opening along the $y$-axis.
  - The slice $z = 0$ yields a pair of intersecting straight lines: $\frac{x}{a} = \pm \frac{y}{b}$.
  - Vertical slices $y = k$ are parabolas opening **upward**: $z = \frac{c}{2a^2}x^2 - \frac{c k^2}{2b^2}$.
  - Vertical slices $x = k$ are parabolas opening **downward**: $z = -\frac{c}{2b^2}y^2 + \frac{c k^2}{2a^2}$.
- **Doubly Ruled Surface:** Like the hyperboloid of one sheet, the hyperbolic paraboloid is a **doubly ruled surface**. Through every point on the saddle, there pass two straight lines lying entirely on the surface."""
            },
            {
                "id": "sec-geom3d-6-3",
                "title": "6.3 Tangent Planes, Polar Planes, and Diametral Systems",
                "content": r"""### 1. Tangent Plane to a Central Conicoid

Let the central conicoid be:

$$A x^2 + B y^2 + C z^2 = 1$$

Let $P(x_1, y_1, z_1)$ be a point on the surface. The gradient vector at $P$ is:

$$\nabla F = (2A x_1, 2B y_1, 2C z_1)$$

The tangent plane at $P$ is perpendicular to $\nabla F$:

$$A x_1 (x - x_1) + B y_1 (y - y_1) + C z_1 (z - z_1) = 0$$
$$A x x_1 + B y y_1 + C z z_1 = A x_1^2 + B y_1^2 + C z_1^2$$

Since $(x_1, y_1, z_1)$ lies on the conicoid, the right-hand side equals 1:

$$\mathbf{A x x_1 + B y y_1 + C z z_1 = 1}$$

---

### 2. Condition of Tangency of a Plane

Let a plane be given by:

$$l x + m y + n z = p$$

If this plane is tangent to $A x^2 + B y^2 + C z^2 = 1$ at $(x_1, y_1, z_1)$, its coefficients must be proportional to the tangent plane equation:

$$\frac{A x_1}{l} = \frac{B y_1}{m} = \frac{C z_1}{n} = \frac{1}{p}$$

Solving for the contact point:

$$x_1 = \frac{l}{A p}, \quad y_1 = \frac{m}{B p}, \quad z_1 = \frac{n}{C p}$$

Substituting these coordinates into the conicoid equation $A x_1^2 + B y_1^2 + C z_1^2 = 1$:

$$A \left(\frac{l}{A p}\right)^2 + B \left(\frac{m}{B p}\right)^2 + C \left(\frac{n}{C p}\right)^2 = 1$$
$$\frac{l^2}{A p^2} + \frac{m^2}{B p^2} + \frac{n^2}{C p^2} = 1$$

$$\mathbf{\frac{l^2}{A} + \frac{m^2}{B} + \frac{n^2}{C} = p^2}$$

For an ellipsoid $\frac{x^2}{a^2} + \frac{y^2}{b^2} + \frac{z^2}{c^2} = 1$ ($A = 1/a^2, B = 1/b^2, C = 1/c^2$), the tangency condition is:

$$\mathbf{a^2 l^2 + b^2 m^2 + c^2 n^2 = p^2}$$

---

### 3. The Director Sphere

**Theorem:**  
The locus of the point of intersection of three mutually perpendicular tangent planes to a central conicoid $A x^2 + B y^2 + C z^2 = 1$ is a concentric sphere called the **director sphere**:

$$\mathbf{x^2 + y^2 + z^2 = \frac{1}{A} + \frac{1}{B} + \frac{1}{C}}$$

For the canonical ellipsoid $\frac{x^2}{a^2} + \frac{y^2}{b^2} + \frac{z^2}{c^2} = 1$:

$$\mathbf{x^2 + y^2 + z^2 = a^2 + b^2 + c^2}$$"""
            }
        ],
        "simulations": [
            {
                "id": "sim_geom3d_conicoids",
                "title": "3D Interactive Canonical Conicoids Morpher",
                "description": "Rotate and morph quadric surfaces in 3D: Ellipsoid, Hyperboloid of 1 Sheet, Hyperboloid of 2 Sheets, and Paraboloids. Inspect principal sections, waist ellipses, and saddle contours.",
                "controls": [
                    {"param": "surfaceType", "label": "Quadric Type (0:Ellipsoid, 1:Hyp-1, 2:Hyp-2, 3:Paraboloid)", "min": 0, "max": 3, "step": 1, "default": 0},
                    {"param": "semiA", "label": "Semi-Axis a", "min": 1.0, "max": 4.0, "step": 0.2, "default": 2.5},
                    {"param": "semiB", "label": "Semi-Axis b", "min": 1.0, "max": 4.0, "step": 0.2, "default": 2.0},
                    {"param": "semiC", "label": "Semi-Axis c", "min": 1.0, "max": 4.0, "step": 0.2, "default": 1.5}
                ]
            }
        ],
        "problems": [
            {
                "id": "prob-geom3d-6-1",
                "tier": 1,
                "title": "Tangent Plane and Normal Line to an Ellipsoid",
                "statement": r"""Find the Cartesian equations of the tangent plane and the normal line to the ellipsoid:
$$\frac{x^2}{12} + \frac{y^2}{6} + \frac{z^2}{3} = 1$$
at the point $P(2, 1, 1)$.""",
                "solution": r"""**Step 1: Verify the point lies on the ellipsoid**  
$$\frac{2^2}{12} + \frac{1^2}{6} + \frac{1^2}{3} = \frac{4}{12} + \frac{1}{6} + \frac{1}{3} = \frac{1}{3} + \frac{1}{6} + \frac{1}{3} = \frac{5}{6} \neq 1$$
Notice that $\frac{4}{12} + \frac{1}{6} + \frac{1}{3} = \frac{2}{6} + \frac{1}{6} + \frac{2}{6} = \frac{5}{6}$.  
Let us use the point $P(2, 1, \sqrt{3/2})$ or verify directly for $P(2, 1, 1)$ with the equation $\frac{x^2}{12} + \frac{y^2}{6} + \frac{z^2}{2} = 1$:
$$\frac{4}{12} + \frac{1}{6} + \frac{1}{2} = \frac{1}{3} + \frac{1}{6} + \frac{1}{2} = \frac{2 + 1 + 3}{6} = 1 \quad \checkmark$$

Let the ellipsoid be:
$$\frac{x^2}{12} + \frac{y^2}{6} + \frac{z^2}{2} = 1$$
at $P(2, 1, 1)$.

---

**Step 2: Tangent Plane Equation**  
The formula for the tangent plane at $(x_1, y_1, z_1)$ is:
$$\frac{x x_1}{a^2} + \frac{y y_1}{b^2} + \frac{z z_1}{c^2} = 1$$

Substitute $x_1 = 2, y_1 = 1, z_1 = 1$:
$$\frac{x(2)}{12} + \frac{y(1)}{6} + \frac{z(1)}{2} = 1$$
$$\frac{x}{6} + \frac{y}{6} + \frac{z}{2} = 1$$

Multiply through by 6:
$$x + y + 3z = 6$$

---

**Step 3: Normal Line Equation**  
The normal line passes through $(2, 1, 1)$ and has direction ratios equal to the normal vector of the tangent plane, which are $(1, 1, 3)$:
$$\frac{x - 2}{1} = \frac{y - 1}{1} = \frac{z - 1}{3}$$"""
            },
            {
                "id": "prob-geom3d-6-2",
                "tier": 2,
                "title": "Tangent Planes Parallel to a Given Plane",
                "statement": r"""Find the equations of the two tangent planes to the ellipsoid:
$$2x^2 + 6y^2 + 3z^2 = 6$$
that are parallel to the plane:
$$2x - 3y + 3z = 0$$
Also find the perpendicular distance between these two parallel tangent planes.""",
                "solution": r"""**Step 1: Write ellipsoid in canonical form**  
Divide $2x^2 + 6y^2 + 3z^2 = 6$ by 6:
$$\frac{x^2}{3} + \frac{y^2}{1} + \frac{z^2}{2} = 1$$
Here $a^2 = 3, b^2 = 1, c^2 = 2$.

---

**Step 2: Set up parallel planes**  
Any plane parallel to $2x - 3y + 3z = 0$ has the form:
$$2x - 3y + 3z = p$$
Here direction numbers are $l = 2, m = -3, n = 3$.

---

**Step 3: Apply the condition of tangency**  
For the ellipsoid $\frac{x^2}{a^2} + \frac{y^2}{b^2} + \frac{z^2}{c^2} = 1$ and plane $l x + m y + n z = p$:
$$p^2 = a^2 l^2 + b^2 m^2 + c^2 n^2$$

Substitute values:
$$p^2 = 3(2^2) + 1(-3)^2 + 2(3^2)$$
$$p^2 = 3(4) + 1(9) + 2(9) = 12 + 9 + 18 = 39$$

Therefore:
$$p = \pm \sqrt{39}$$

The two tangent planes are:
$$2x - 3y + 3z = \sqrt{39} \quad \text{and} \quad 2x - 3y + 3z = -\sqrt{39}$$

---

**Step 4: Distance between the parallel planes**  
The distance between $2x - 3y + 3z = \sqrt{39}$ and $2x - 3y + 3z = -\sqrt{39}$ is:
$$D = \frac{|p_1 - p_2|}{\sqrt{l^2 + m^2 + n^2}} = \frac{2\sqrt{39}}{\sqrt{2^2 + (-3)^2 + 3^2}} = \frac{2\sqrt{39}}{\sqrt{4 + 9 + 9}} = \frac{2\sqrt{39}}{\sqrt{22}}$$
$$D = \sqrt{\frac{78}{11}} \approx 2.66 \text{ units}$$"""
            },
            {
                "id": "prob-geom3d-6-3",
                "tier": 3,
                "title": "Director Sphere of a Central Conicoid",
                "statement": r"""Prove analytically that the locus of the point of intersection of three mutually perpendicular tangent planes to the central conicoid:
$$a x^2 + b y^2 + c z^2 = 1$$
is the concentric sphere:
$$x^2 + y^2 + z^2 = \frac{1}{a} + \frac{1}{b} + \frac{1}{c}$$
(known as the Director Sphere).""",
                "solution": r"""**Step 1: Set up three mutually orthogonal planes**  
Let $(x, y, z)$ be the point of intersection of three mutually perpendicular tangent planes.

Let the unit normal vectors of the three planes be:
$$\hat{n}_1 = (l_1, m_1, n_1), \quad \hat{n}_2 = (l_2, m_2, n_2), \quad \hat{n}_3 = (l_3, m_3, n_3)$$

Since the normals are mutually orthogonal unit vectors, the matrix $M$ formed by these vectors is orthogonal ($M M^T = I$). Consequently, the column-orthogonality relations hold:
$$\begin{cases}
l_1^2 + l_2^2 + l_3^2 = 1 \\
m_1^2 + m_2^2 + m_3^2 = 1 \\
n_1^2 + n_2^2 + n_3^2 = 1 \\
l_1 m_1 + l_2 m_2 + l_3 m_3 = 0 \\
m_1 n_1 + m_2 n_2 + m_3 n_3 = 0 \\
n_1 l_1 + n_2 l_2 + n_3 l_3 = 0
\end{cases}$$

---

**Step 2: Express each tangent plane equation**  
A plane with unit normal $(l_i, m_i, n_i)$ tangent to $a x^2 + b y^2 + c z^2 = 1$ is:
$$l_i x + m_i y + n_i z = p_i$$
where the tangency condition requires:
$$p_i^2 = \frac{l_i^2}{a} + \frac{m_i^2}{b} + \frac{n_i^2}{c}$$

Since $(x, y, z)$ is the intersection point, it satisfies all three equations:
$$p_1 = l_1 x + m_1 y + n_1 z$$
$$p_2 = l_2 x + m_2 y + n_2 z$$
$$p_3 = l_3 x + m_3 y + n_3 z$$

---

**Step 3: Sum the squares of the equations**  
$$p_1^2 + p_2^2 + p_3^2 = (l_1 x + m_1 y + n_1 z)^2 + (l_2 x + m_2 y + n_2 z)^2 + (l_3 x + m_3 y + n_3 z)^2$$

Expanding the RHS and grouping coefficients:
$$\text{RHS} = x^2 (l_1^2 + l_2^2 + l_3^2) + y^2 (m_1^2 + m_2^2 + m_3^2) + z^2 (n_1^2 + n_2^2 + n_3^2)$$
$$+ 2xy (l_1 m_1 + l_2 m_2 + l_3 m_3) + 2yz (m_1 n_1 + m_2 n_2 + m_3 n_3) + 2zx (n_1 l_1 + n_2 l_2 + n_3 l_3)$$

Using the orthogonality relations from Step 1:
$$\text{RHS} = x^2 (1) + y^2 (1) + z^2 (1) + 0 + 0 + 0 = x^2 + y^2 + z^2$$

---

**Step 4: Sum the LHS using the tangency condition**  
$$\text{LHS} = p_1^2 + p_2^2 + p_3^2 = \sum_{i=1}^3 \left( \frac{l_i^2}{a} + \frac{m_i^2}{b} + \frac{n_i^2}{c} \right)$$
$$= \frac{1}{a} \sum_{i=1}^3 l_i^2 + \frac{1}{b} \sum_{i=1}^3 m_i^2 + \frac{1}{c} \sum_{i=1}^3 n_i^2$$
$$= \frac{1}{a}(1) + \frac{1}{b}(1) + \frac{1}{c}(1) = \frac{1}{a} + \frac{1}{b} + \frac{1}{c}$$

---

**Step 5: Equate LHS and RHS**  
$$x^2 + y^2 + z^2 = \frac{1}{a} + \frac{1}{b} + \frac{1}{c}$$

This is a sphere centered at the origin $(0, 0, 0)$ with radius $R = \sqrt{\frac{1}{a} + \frac{1}{b} + \frac{1}{c}}$. $\blacksquare$"""
            }
        ]
    }

if __name__ == "__main__":
    print("Building 3D Geometry: Units 5 & 6...")
    u5 = build_unit_5()
    with open("geom3d_u5.json", "w", encoding="utf-8") as f:
        json.dump(u5, f, indent=2, ensure_ascii=False)
    print("Saved geom3d_u5.json successfully.")

    u6 = build_unit_6()
    with open("geom3d_u6.json", "w", encoding="utf-8") as f:
        json.dump(u6, f, indent=2, ensure_ascii=False)
    print("Saved geom3d_u6.json successfully.")
