# -*- coding: utf-8 -*-
"""
Environmental Chemistry - Unit 9 Content Generator
Unit 9: Solid Waste Management, Hazardous Wastes & Circular Economy
Strictly no marks, no course codes, pure Unix line endings.
"""

import json

def get_unit_9():
    unit = {
        "id": "unit_9",
        "title": "Solid Waste Management, Hazardous Wastes & Circular Economy",
        "badge": "Unit 09",
        "summary": "Solid waste characterization, Dulong combustion thermochemistry, and engineered sanitary landfills; LandGEM methane kinetics and leachate geochemistry; hazardous waste classification (RCRA/TCLP) and cementitious solidification/stabilization; thermochemical conversion (gasification/pyrolysis), e-waste hydrometallurgy, and circular material flow analysis.",
        "simulation": {
            "id": "sim_env_landfill_methane_leachate",
            "title": "Sanitary Landfill Biogas & Leachate Generation Simulator",
            "type": "canvas",
            "description": "Multi-year sanitary landfill simulator modeling anaerobic waste biodegradation phases (aerobic, acidogenic, methanogenic, maturation), LandGEM methane evolution curves, and hydrologic leachate percolation."
        },
        "sections": [
            {
                "id": "sec_9_1",
                "title": "Municipal Solid Waste (MSW): Composition, Proximate & Ultimate Analysis",
                "content": """Municipal Solid Waste (MSW) comprises the heterogeneous refuse generated by residential, commercial, and institutional activities. Designing effective resource recovery or thermal conversion facilities requires rigorous thermodynamic and chemical characterization.

### Proximate Analysis
Proximate analysis quantifies the physical-chemical combustion fractions of the waste material:
1. **Moisture Content ($M$)**: Determined by oven drying at $105^\\circ\\text{C}$ to constant weight:
   \\[
   M (\\%) = \\frac{m_{wet} - m_{dry}}{m_{wet}} \\times 100
   \\]
2. **Volatile Combustible Matter (VCM)**: Mass lost when dry sample is heated in a closed crucible at $950^\\circ\\text{C}$ in the absence of oxygen for 7 minutes.
3. **Fixed Carbon (FC)**: Combustible solid carbon residue remaining after volatile expulsion.
4. **Ash Content ($A$)**: Non-combustible inorganic mineral residue remaining after complete oxidation at $750^\\circ\\text{C}$.
\\[
M + VCM + FC + A = 100\\%
\\]

### Ultimate (Elemental) Analysis
Ultimate analysis quantifies the fundamental elemental stoichiometry of dry, ash-free organic matter: carbon ($C$), hydrogen ($H$), oxygen ($O$), nitrogen ($N$), and sulfur ($S$), yielding the generalized chemical formula:
\\[
C_a H_b O_c N_d S_e
\\]

### Energy Content: Higher and Lower Heating Values
The Higher Heating Value (HHV) represents the enthalpy of complete combustion assuming all product water condenses to liquid at $25^\\circ\\text{C}$, estimated via the Modified Dulong Formula:
\\[
\\text{HHV} (\\text{MJ}/\\text{kg}) = 0.338 C + 1.428 \\left( H - \\frac{O}{8} \\right) + 0.095 S
\\]
where $C, H, O, S$ are mass percentages on a dry basis.
The Lower Heating Value (LHV) accounts for the latent heat of vaporization of water ($2.44\\ \\text{MJ}/\\text{kg}$ at $25^\\circ\\text{C}$), reflecting practical net usable energy:
\\[
\\text{LHV} = \\text{HHV} - 2.44 \\left( \\frac{9 H + M}{100} \\right)
\\]"""
            },
            {
                "id": "sec_9_2",
                "title": "Engineered Sanitary Landfills: Geosynthetic Composite Liners & Drainage",
                "content": """Open dumping exposes groundwater aquifers and ecosystems to toxic contamination. Engineered sanitary landfills isolate solid waste within an impermeable containment cell engineered to prevent subterranean environmental migration.

### Subtitle D / European Standard Composite Liner Systems
Modern landfill basal containment utilizes a redundant multi-barrier composite liner system:
1. **Sub-base Foundation**: Compacted, re-graded native soil providing uniform structural stability.
2. **Geosynthetic Clay Liner (GCL)**: Sodium bentonite clay sandwiched between geotextiles, or a minimum $60 - 90\\ \\text{cm}$ compacted clay liner (CCL) achieving hydraulic conductivity:
   \\[
   k \\le 1.0 \\times 10^{-9}\\ \\text{m}/\\text{s} \\quad (1.0 \\times 10^{-7}\\ \\text{cm}/\\text{s})
   \\]
3. **Geomembrane Barrier**: High-Density Polyethylene (HDPE) flexible membrane liner of minimum thickness $1.5 - 2.0\\ \\text{mm}$ (60 - 80 mils), possessing exceptional chemical resistance to organic solvents and acids.
4. **Cushion Geotextile**: Non-woven needle-punched polypropylene geotextile protecting the geomembrane against puncture from angular gravel.
5. **Leachate Collection and Removal System (LCRS)**: A $30\\ \\text{cm}$ layer of permeable rounded gravel ($k > 1.0 \\times 10^{-3}\\ \\text{m}/\\text{s}$) with perforated HDPE collector pipes sloped at $\\ge 1 - 2\\%$ toward sumps. The LCRS maintains hydraulic head above the liner strictly below $30\\ \\text{cm}$ ($h_{max} \\le 0.30\\ \\text{m}$) to minimize advective leak fluxes through accidental geomembrane pinholes."""
            },
            {
                "id": "sec_9_3",
                "title": "Landfill Gas (LFG) Generation Kinetics & The LandGEM Model",
                "content": """Anaerobic decomposition of biodegradable organic matter (food waste, paper, cardboard, textiles) inside an enclosed landfill progresses through four distinct biochemical phases.

### Sequential Biochemical Degradation Phases
1. **Phase I (Aerobic Phase, Days to Weeks)**: Entrapped atmospheric oxygen is consumed by aerobic microorganisms, converting labile organics to $CO_2$ and $H_2O$.
2. **Phase II (Acidogenic / Hydrolytic Phase, Months)**: Facultative anaerobes hydrolyze cellulose and hemicellulose into volatile fatty acids (acetic, propionic, butyric). Leachate pH plummets to $5.0 - 6.0$, dissolving heavy metals; gas is primarily $CO_2$ and $H_2$.
3. **Phase III (Methanogenic Unsteady Phase, 1 - 3 Years)**: Methanogenic archaea establish colonies, consuming VFAs and hydrogen. Methane concentration climbs steadily toward $50 - 60\\%$.
4. **Phase IV (Steady-State Methanogenic Phase, Decades)**: Stable production of landfill biogas composed of $50 - 55\\%\\ CH_4$, $40 - 45\\%\\ CO_2$, and trace non-methane organic compounds (NMOCs: benzene, toluene, vinyl chloride, siloxanes).

### The US EPA LandGEM First-Order Decay Model
Cumulative and instantaneous methane generation rates are computed via the LandGEM first-order kinematic differential model:
\\[
Q_{CH_4} = \\sum_{i=1}^{n} 2 k L_0 \\left( \\frac{M_i}{10} \\right) e^{-k t_{i}}
\\]
where:
- $Q_{CH_4}$: Methane generation rate in year of inventory calculation ($\\text{m}^3/\\text{year}$).
- $k$: Methane generation rate constant ($\\text{year}^{-1}$), ranging from $0.02\\ \\text{year}^{-1}$ in arid climates to $0.05 - 0.08\\ \\text{year}^{-1}$ in wet tropical climates.
- $L_0$: Potential methane generation capacity ($\\text{m}^3/\\text{metric ton of waste}$), typically $100 - 170\\ \\text{m}^3/\\text{ton}$.
- $M_i$: Mass of waste accepted in the $i$-th year (metric tons).
- $t_{i}$: Age of the $i$-th waste section ($\\text{years}$)."""
            },
            {
                "id": "sec_9_4",
                "title": "Landfill Leachate Geochemistry: Young vs Mature & Advanced Treatment",
                "content": """Leachate is generated when external precipitation, surface runoff, and waste consolidation porewater percolate through the decomposing solid waste mass, dissolving organic metabolites and inorganic minerals.

### Geochemical Evolution: Young vs Mature Leachate
The chemical characteristics of leachate evolve dramatically over landfill lifespan:
- **Young (Acetogenic) Leachate (< 5 years old)**:
  - Characterized by high $\\text{BOD}_5$ ($10,000 - 30,000\\ \\text{mg}/\\text{L}$) and extreme COD ($15,000 - 50,000\\ \\text{mg}/\\text{L}$).
  - High biodegradability ratio: $\\text{BOD}_5 / \\text{COD} > 0.4 - 0.7$.
  - Acidic pH ($5.5 - 6.5$), high free volatile fatty acids, and high concentrations of dissolved heavy metals mobilized by low pH.
- **Mature (Stabilized / Methanogenic) Leachate (> 10 years old)**:
  - Moderate to low $\\text{BOD}_5$ ($< 200 - 500\\ \\text{mg}/\\text{L}$) and moderate COD ($1,000 - 5,000\\ \\text{mg}/\\text{L}$).
  - Refractory, non-biodegradable ratio: $\\text{BOD}_5 / \\text{COD} < 0.10$.
  - Alkaline pH ($7.5 - 8.5$), high ammonia-nitrogen ($NH_3-N: 1,000 - 3,000\\ \\text{mg}/\\text{L}$), and dark brown humic and fulvic macromolecules that resist biological oxidation.

### Treatment Train Architecture
Because mature leachate resists biological degradation, advanced integrated treatment is necessary:
\\[
\\text{Stripping Tower (De-ammonification)} \\rightarrow \\text{Fenton Oxidation} \\rightarrow \\text{MBR} \\rightarrow \\text{Nanofiltration / Reverse Osmosis}
\\]"""
            },
            {
                "id": "sec_9_5",
                "title": "Thermal Conversion: Incineration Thermochemistry & Flue Gas Cleaning",
                "content": """Mass-burn waste-to-energy (WtE) incineration reduces waste volume by $90\\%$ and mass by $70 - 75\\%$ while generating high-pressure superheated steam for electrical turbogenerators.

### Combustion Thermodynamics & The 3T Principle
Complete thermal oxidation of solid waste requires satisfying the fundamental **3T Principle**:
1. **Temperature**: Flue gases must reach a minimum furnace temperature of $\\ge 850^\\circ\\text{C}$ (or $\\ge 1100^\\circ\\text{C}$ for hazardous/halogenated wastes) to thermally crack hazardous organics.
2. **Time**: Residence time of flue gases in the high-temperature zone must exceed **2.0 seconds** in the presence of $\\ge 6\\%$ excess oxygen ($O_2$).
3. **Turbulence**: Intense aerodynamic mixing between secondary air injection jets and volatile combustion gases prevents localized cold spots and unburned hydrocarbons.

### Air Pollution Control (APC) Engineering
Incineration generates hazardous acidic gases, heavy metal vapors, and persistent organohalogens requiring multi-barrier flue gas cleaning:
1. **Selective Non-Catalytic Reduction (SNCR) / Selective Catalytic Reduction (SCR)**: Urea or ammonia injection reduces nitrogen oxides:
   \\[
   4\\text{NO} + 4\\text{NH}_3 + \\text{O}_2 \\xrightarrow{\\text{SCR Catalyst}} 4\\text{N}_2 + 6\\text{H}_2\\text{O}
   \\]
2. **Dry / Semi-Dry Acid Gas Scrubbing**: Hydrated lime ($\\text{Ca(OH)}_2$) or sodium bicarbonate ($\\text{NaHCO}_3$) neutralizes acid gases:
   \\[
   \\text{Ca(OH)}_2 + 2\\text{HCl} \\rightarrow \\text{CaCl}_2 + 2\\text{H}_2\\text{O}
   \\]
   \\[
   \\text{Ca(OH)}_2 + \\text{SO}_2 + \\frac{1}{2}\\text{O}_2 \\rightarrow \\text{CaSO}_4 + \\text{H}_2\\text{O}
   \\]
3. **Powdered Activated Carbon (PAC) Injection**: Continuously dosed into the flue gas duct upstream of fabric baghouse filters to adsorb gaseous mercury vapor ($Hg^0, HgCl_2$) and dioxins/furans (PCDD/Fs).
4. **Fabric Baghouse Filters**: Woven or felted fabric filter bags capture particulate fly ash with $> 99.9\\%$ efficiency."""
            },
            {
                "id": "sec_9_6",
                "title": "Pyrolysis & Gasification of Polymer and Biomass Wastes",
                "content": """Thermochemical conversion under sub-stoichiometric oxygen conditions converts solid carbonaceous polymers into high-value chemical feedstocks and synthesis gas.

### Fundamental Thermochemical Regimes
- **Pyrolysis**:
  - Thermal decomposition of organic matter in the **complete absence of oxygen** ($O_2 = 0$) at moderate temperatures ($400 - 800^\\circ\\text{C}$).
  - Endothermic cleavage of covalent polymer bonds produces three distinct product phases:
    1. *Pyrolysis Bio-oil / Liquid Condensate*: Complex mixture of oxygenated aromatics, furans, and oligomers.
    2. *Non-condensable Syngas*: Rich in methane ($CH_4$), ethylene ($C_2H_4$), ethane, $CO$, and $H_2$.
    3. *Solid Char (Biochar)*: Porous, high-surface-area carbonaceous matrix useful for soil amendment and water filtration.
- **Gasification**:
  - Partial oxidation of carbonaceous matter under **sub-stoichiometric oxygen or steam** (Equivalence Ratio $\\phi \\approx 0.25 - 0.40$) at high temperatures ($800 - 1300^\\circ\\text{C}$).
  - Promotes heterogeneous gas-solid reforming equilibria:
    - *Boudouard Reaction*:
      \\[
      \\text{C} + \\text{CO}_2 \\rightleftharpoons 2\\text{CO}, \\quad \\Delta H^\\circ = +172.5\\ \\text{kJ}/\\text{mol}
      \\]
    - *Water-Gas Reaction*:
      \\[
      \\text{C} + \\text{H}_2\\text{O} \\rightleftharpoons \\text{CO} + \\text{H}_2, \\quad \\Delta H^\\circ = +131.3\\ \\text{kJ}/\\text{mol}
      \\]
    - *Water-Gas Shift Reaction*:
      \\[
      \\text{CO} + \\text{H}_2\\text{O} \\rightleftharpoons \\text{CO}_2 + \\text{H}_2, \\quad \\Delta H^\\circ = -41.2\\ \\text{kJ}/\\text{mol}
      \\]
  - Primary product is high-purity synthesis gas (Syngas: $CO + H_2$), an essential building block for Fischer-Tropsch synthetic fuels and methanol synthesis."""
            },
            {
                "id": "sec_9_7",
                "title": "Hazardous Wastes & The Basel Convention: TCLP & Solidification",
                "content": """Hazardous wastes pose substantial present or potential hazards to human health or the environment when improperly treated, stored, transported, or disposed of.

### Regulatory Definition & The RCRA Characteristic Criteria
Under the US Resource Conservation and Recovery Act (RCRA) and global environmental statutes, a solid waste is hazardous if it displays any of four core characteristics:
1. **Ignitability ($D001$)**: Liquid with flash point $< 60^\\circ\\text{C}$ ($140^\\circ\\text{F}$), or non-liquid capable of causing fire through friction or absorption of moisture.
2. **Corrosivity ($D002$)**: Aqueous solution with $\\text{pH} \\le 2.0$ or $\\text{pH} \\ge 12.5$.
3. **Reactivity ($D003$)**: Unstable, violently reactive with water, explosive, or releasing toxic hydrogen cyanide ($HCN$) or hydrogen sulfide ($H_2S$) gases.
4. **Toxicity ($D004 - D043$)**: Leaches hazardous constituents exceeding regulatory limits in the Toxicity Characteristic Leaching Procedure (TCLP, EPA Method 1311).

### Toxicity Characteristic Leaching Procedure (TCLP)
TCLP simulates the aggressive leaching behavior of hazardous waste co-disposed in an acidic, municipal anaerobic landfill:
- The solid waste is extracted for $18 \\pm 2\\ \\text{hours}$ at $30\\ \\text{rpm}$ with a dilute sodium acetate / acetic acid buffer solution ($pH = 4.93$ or $2.88$) at a $20:1$ liquid-to-solid ratio.
- Regulatory maximum concentration thresholds for toxic heavy metals:
  \\[
  As: 5.0\\ \\text{mg}/\\text{L}, \\quad Ba: 100.0\\ \\text{mg}/\\text{L}, \\quad Cd: 1.0\\ \\text{mg}/\\text{L}, \\quad Cr: 5.0\\ \\text{mg}/\\text{L}, \\quad Pb: 5.0\\ \\text{mg}/\\text{L}, \\quad Hg: 0.2\\ \\text{mg}/\\text{L}
  \\]

### Solidification / Stabilization (S/S) Engineering
Hazardous industrial sludges and electric arc furnace dusts are immobilized using Ordinary Portland Cement (OPC), fly ash, and pozzolanic binders:
- **Stabilization**: Chemical transformation of toxic metals into insoluble crystalline minerals (e.g., incorporating $Cr^{3+}$ into ettringite or calcium silicate hydrate, C-S-H gel lattices).
- **Solidification**: Physical encapsulation of waste within a dense, monolithic solid matrix with low permeability ($k < 10^{-10}\\ \\text{m}/\\text{s}$) and compressive strength $> 0.35 - 1.0\\ \\text{MPa}$."""
            },
            {
                "id": "sec_9_8",
                "title": "E-Waste Metallurgy, Critical Raw Material Recovery & Circular Economy MFA",
                "content": """Electronic waste (E-waste) represents the fastest growing domestic waste stream globally, containing both toxic heavy metals ($Pb, Cd, Hg, brominated flame retardants$) and highly concentrated precious and critical raw materials ($Au, Ag, Pd, Cu, Li, Co, Nd$).

### Urban Mining: Printed Circuit Board (PCB) Hydrometallurgy
A metric ton of discarded smartphone printed circuit boards contains up to $250 - 350\\ \\text{g}$ of gold ($Au$) and $100 - 130\\ \\text{kg}$ of copper ($Cu$), concentrations 10 to 50 times richer than primary ore bodies:
1. **Mechanical Pre-processing**: Comminution, magnetic separation of ferrous metals, eddy-current separation of aluminum, and electrostatic corona-roll separation of metallics from epoxy-fiberglass substrates.
2. **Hydrometallurgical Base Metal Stripping**: Copper, nickel, and zinc are selectively dissolved using oxidative sulfuric acid leaching:
   \\[
   \\text{Cu} + \\text{H}_2\\text{SO}_4 + \\text{H}_2\\text{O}_2 \\rightarrow \\text{CuSO}_4 + 2\\text{H}_2\\text{O}
   \\]
3. **Precious Metal Leaching**: Gold and palladium are extracted using eco-friendly non-cyanide lixiviants such as acidified thiourea ($SC(NH_2)_2$) or thiosulfate ($S_2O_3^{2-}$):
   \\[
   \\text{Au} + 2\\text{CS(NH}_2)_2 + \\text{Fe}^{3+} \\rightarrow [\\text{Au(CS(NH}_2)_2)_2]^+ + \\text{Fe}^{2+}
   \\]

### Circular Economy: Material Flow Analysis (MFA)
The circular economy replaces the linear 'take-make-dispose' model with closed material loops. **Material Flow Analysis (MFA)** tracks mass balances across societal stocks and flows governed by the law of conservation of mass:
\\[
\\sum \\dot{m}_{in} = \\sum \\dot{m}_{out} + \\frac{d(\\text{Stock})}{dt}
\\]
The Circular Material Use Rate ($CMUR$) measures circularity performance:
\\[
CMUR (\\%) = \\frac{M_{recycled}}{M_{virgin} + M_{recycled}} \\times 100
\\]"""
            }
        ],
        "problems": [
            {
                "id": "prob_9_1",
                "tier": "Foundational",
                "title": "Modified Dulong Formula: Higher and Lower Heating Value of MSW",
                "statement": "An ultimate elemental analysis of a dried municipal solid waste sample yields the following mass percentages on a dry basis: Carbon ($C$) = $46.5\\%$, Hydrogen ($H$) = $6.2\\%$, Oxygen ($O$) = $35.8\\%$, Nitrogen ($N$) = $1.8\\%$, Sulfur ($S$) = $0.4\\%$, and inorganic Ash ($A$) = $9.3\\%$. The as-received raw municipal waste has a field moisture content of $M = 28.0\\%$. (a) Using the Modified Dulong Formula $\\text{HHV}_{dry} (\\text{MJ}/\\text{kg}) = 0.338 C + 1.428 \\left( H - \\frac{O}{8} \\right) + 0.095 S$, calculate the Higher Heating Value of the dry solid waste in $\\text{MJ}/\\text{kg}$. (b) Calculate the Lower Heating Value on the as-received wet basis ($\\text{LHV}_{wet}$) in $\\text{MJ}/\\text{kg}$, accounting for moisture dilution and the latent heat of vaporization of water ($2.44\\ \\text{MJ}/\\text{kg}$).",
                "hints": [
                    "Evaluate dry net available hydrogen: $H_{net} = H - O / 8$.",
                    "Compute $\\text{HHV}_{dry}$.",
                    "Convert to as-received basis: $\\text{HHV}_{wet} = \\text{HHV}_{dry} \\times (1 - M/100)$.",
                    "Deduct latent heat: $\\text{LHV}_{wet} = \\text{HHV}_{wet} - 2.44 \\times \\left( \\frac{9 H_{wet} + M}{100} \\right)$, where $H_{wet} = H_{dry} \\times (1 - M/100)$."
                ],
                "solution": """**Step 1: Calculate $\\text{HHV}_{dry}$ via Modified Dulong Formula**
Given dry percentages:
- $C = 46.5\\%$
- $H = 6.2\\%$
- $O = 35.8\\%$
- $S = 0.4\\%$

Net available combustible hydrogen:
\\[
H - \\frac{O}{8} = 6.2 - \\frac{35.8}{8} = 6.2 - 4.475 = 1.725\\%
\\]
Applying Dulong's formula:
\\[
\\text{HHV}_{dry} = 0.338(46.5) + 1.428(1.725) + 0.095(0.4)
\\]
\\[
\\text{HHV}_{dry} = 15.717 + 2.4633 + 0.038 = 18.2183\\ \\text{MJ}/\\text{kg} \\approx 18.22\\ \\text{MJ}/\\text{kg}
\\]

**Step 2: Convert to as-received wet Higher Heating Value**
With moisture content $M = 28.0\\%$, the dry mass fraction is $1 - 0.280 = 0.720$:
\\[
\\text{HHV}_{wet} = \\text{HHV}_{dry} \\times (1 - 0.280) = 18.2183 \\times 0.720 = 13.1172\\ \\text{MJ}/\\text{kg}
\\]

**Step 3: Calculate Lower Heating Value on as-received wet basis**
Wet hydrogen mass percentage:
\\[
H_{wet} = H_{dry} \\times (1 - 0.280) = 6.2\\% \\times 0.720 = 4.464\\%
\\]
Total water vaporized upon combustion per $100\\ \\text{kg}$ of wet waste:
\\[
m_{H_2O} = 9 H_{wet} + M = 9(4.464) + 28.0 = 40.176 + 28.0 = 68.176\\ \\text{kg H}_2\\text{O} / 100\\ \\text{kg waste}
\\]
Per kilogram of wet waste: $0.68176\\ \\text{kg H}_2\\text{O}/\\text{kg waste}$.
Deducting latent heat of vaporization ($2.44\\ \\text{MJ}/\\text{kg}$):
\\[
\\Delta H_{vap} = 2.44\\ \\text{MJ}/\\text{kg} \\times 0.68176\\ \\text{kg} = 1.6635\\ \\text{MJ}/\\text{kg}
\\]
The Lower Heating Value:
\\[
\\text{LHV}_{wet} = \\text{HHV}_{wet} - \\Delta H_{vap} = 13.1172 - 1.6635 = 11.4537\\ \\text{MJ}/\\text{kg} \\approx 11.45\\ \\text{MJ}/\\text{kg}
\\]

**Conclusion**:
The dry Higher Heating Value is **$18.22\\ \\text{MJ}/\\text{kg}$**, and the as-received Lower Heating Value is **$11.45\\ \\text{MJ}/\\text{kg}$** (well above the self-sustaining combustion limit of $7.0\\ \\text{MJ}/\\text{kg}$ for grate incinerators)."""
            },
            {
                "id": "prob_9_2",
                "tier": "Foundational",
                "title": "Sanitary Landfill Leachate Generation Estimation via Hydrologic Water Balance",
                "statement": "An engineered landfill cell in Gazipur covers an active operating footprint area of $A = 50,000\\ \\text{m}^2$ ($5.0\\ \\text{hectares}$). Annual meteorological and soil data are: total annual precipitation $P = 2100\\ \\text{mm}/\\text{year}$, surface runoff fraction $C_r = 0.15$ ($15\\%$ of rainfall runs off), actual evapotranspiration $ET = 1150\\ \\text{mm}/\\text{year}$, and soil waste field capacity absorptive moisture storage retention $\\Delta S = 50\\ \\text{mm}/\\text{year}$. (a) Using the hydrologic water balance equation $L = P - R - ET - \\Delta S$, calculate the annual leachate percolation depth $L$ in millimeters per year. (b) Calculate the total annual volumetric leachate generation rate in cubic meters per year ($\\text{m}^3/\\text{year}$) and the average daily leachate flow rate in cubic meters per day ($\\text{m}^3/\\text{day}$).",
                "hints": [
                    "Surface runoff: $R = C_r \\times P = 0.15 \\times 2100\\ \\text{mm}$.",
                    "Net percolation depth: $L = P - R - ET - \\Delta S$.",
                    "Total volume: $V = L (\\text{in meters}) \\times A (\\text{in } \\text{m}^2)$."
                ],
                "solution": """**Step 1: Calculate surface runoff and net percolation depth $L$**
Given:
- Annual precipitation: $P = 2100\\ \\text{mm}$
- Runoff coefficient: $C_r = 0.15$
- Surface runoff: $R = C_r \\times P = 0.15 \\times 2100\\ \\text{mm} = 315\\ \\text{mm}$
- Actual evapotranspiration: $ET = 1150\\ \\text{mm}$
- Waste moisture storage change: $\\Delta S = 50\\ \\text{mm}$

The net leachate percolation depth:
\\[
L = P - R - ET - \\Delta S = 2100 - 315 - 1150 - 50 = 585\\ \\text{mm}/\\text{year}
\\]
Converting to meters:
\\[
L = 0.585\\ \\text{m}/\\text{year}
\\]

**Step 2: Calculate annual and daily leachate generation volume**
Landfill surface area: $A = 50,000\\ \\text{m}^2$.
Total annual leachate volume:
\\[
V_{annual} = A \\times L = 50,000\\ \\text{m}^2 \\times 0.585\\ \\text{m}/\\text{year} = 29,250\\ \\text{m}^3/\\text{year}
\\]
Average daily leachate flow rate ($1\\ \\text{year} = 365.25\\ \\text{days}$):
\\[
Q_{daily} = \\frac{29,250\\ \\text{m}^3/\\text{year}}{365.25\\ \\text{days}} = 80.08\\ \\text{m}^3/\\text{day} \\approx 80.1\\ \\text{m}^3/\\text{day}
\\]

**Conclusion**:
The site generates **$585\\ \\text{mm}$** of percolation depth annually, yielding **$29,250\\ \\text{m}^3/\\text{year}$** of raw leachate, requiring a dedicated treatment facility designed for **$80.1\\ \\text{m}^3/\\text{day}$**."""
            },
            {
                "id": "prob_9_3",
                "tier": "Foundational",
                "title": "Basel Convention Hazardous Waste Classification & TCLP Metal Leaching",
                "statement": "An industrial galvanic electroplating sludge cake is analyzed for RCRA Toxicity Characteristic classification via EPA Method 1311 (TCLP). A dry solid sample of $m_s = 100.0\\ \\text{g}$ is extracted in $V_{ext} = 2000.0\\ \\text{mL}$ of standard acetic acid extraction fluid ($20:1$ liquid-to-solid ratio). ICP-OES analysis of the filtered leachate extracts yields the following heavy metal concentrations: Cadmium ($Cd$) = $1.85\\ \\text{mg}/\\text{L}$, Total Chromium ($Cr$) = $3.40\\ \\text{mg}/\\text{L}$, and Lead ($Pb$) = $8.50\\ \\text{mg}/\\text{L}$. The regulatory TCLP toxicity thresholds are: $Cd \\le 1.0\\ \\text{mg}/\\text{L}$, $Cr \\le 5.0\\ \\text{mg}/\\text{L}$, and $Pb \\le 5.0\\ \\text{mg}/\\text{L}$. (a) Determine which metal contaminants fail compliance and assign the appropriate RCRA hazardous waste identification numbers (D006 for Cd, D007 for Cr, D008 for Pb). (b) Calculate the total milligrams of lead ($Pb$) leached per kilogram of dry solid waste. (c) State the legal disposal restrictions imposed by the Basel Convention on this material.",
                "hints": [
                    "Compare measured values against the respective thresholds: $Cd: 1.85$ vs $1.0$; $Cr: 3.40$ vs $5.0$; $Pb: 8.50$ vs $5.0$.",
                    "Mass of metal leached per kg solid: $C (\\text{mg}/\\text{L}) \\times 20\\ \\text{L}/\\text{kg}$."
                ],
                "solution": """**Step 1: Evaluate compliance against regulatory TCLP thresholds**
Comparing analytical concentrations with US EPA / Basel standards:
1. **Cadmium ($Cd$)**:
   - Measured: $1.85\\ \\text{mg}/\\text{L}$
   - Regulatory Limit: $1.00\\ \\text{mg}/\\text{L}$
   - Status: **NON-COMPLIANT (FAILED)** $\\implies$ Classified as **Hazardous Waste D006**.
2. **Total Chromium ($Cr$)**:
   - Measured: $3.40\\ \\text{mg}/\\text{L}$
   - Regulatory Limit: $5.00\\ \\text{mg}/\\text{L}$
   - Status: **COMPLIANT (PASSED)**.
3. **Lead ($Pb$)**:
   - Measured: $8.50\\ \\text{mg}/\\text{L}$
   - Regulatory Limit: $5.00\\ \\text{mg}/\\text{L}$
   - Status: **NON-COMPLIANT (FAILED)** $\\implies$ Classified as **Hazardous Waste D008**.

**Step 2: Calculate total lead leached per kg of dry waste**
With a liquid-to-solid ratio of $20:1$ ($2.0\\ \\text{L}$ fluid per $0.100\\ \\text{kg}$ solid = $20.0\\ \\text{L}/\\text{kg}$):
\\[
\\text{Leached Pb} = 8.50\\ \\text{mg}/\\text{L} \\times 20.0\\ \\text{L}/\\text{kg} = 170.0\\ \\text{mg Pb}/\\text{kg dry waste}
\\]

**Step 3: Basel Convention Regulatory Implications**
Under Annex I (Y31 for Lead, Y26 for Cadmium) and Annex III (Hazard Characteristic H11: Toxic / Delayed or Chronic), this sludge is classified as **Hazardous Waste**.
*Restrictions*:
1. Transboundary movement across international borders is strictly prohibited without Prior Informed Consent (PIC) and bilateral bilateral agreements.
2. Direct disposal into municipal sanitary landfills is prohibited; the waste must undergo chemical stabilization and solidification (S/S) or pyrometallurgical metal recovery in an authorized hazardous waste treatment facility."""
            },
            {
                "id": "prob_9_4",
                "tier": "Intermediate",
                "title": "EPA LandGEM First-Order Model: Multi-Year Landfill Methane Evolution",
                "statement": "A regional sanitary landfill opened in 2020 receives a constant municipal waste acceptance rate of $M = 150,000\\ \\text{metric tons}/\\text{year}$ for 4 consecutive years (Years 2020, 2021, 2022, 2023). Model parameters are: methane generation rate constant $k = 0.050\\ \\text{year}^{-1}$ and potential methane generation capacity $L_0 = 120.0\\ \\text{m}^3/\\text{metric ton}$. Waste accepted in year $i$ begins decomposing after a 1-year lag time ($t_i = \\text{Year}_{eval} - \\text{Year}_i$). Using the LandGEM summation formula $Q_{CH4}(t) = \\sum_{i} 2 k L_0 M_i e^{-k t_i}$: (a) Calculate the constant pre-exponential factor $2 k L_0 M$ in $\\text{m}^3/\\text{year}$. (b) Calculate the total methane generation rate $Q_{CH4}$ in year 2024 (where waste ages are $t = 4, 3, 2, 1\\ \\text{years}$). (c) If a landfill gas collection system operates at $75.0\\%$ capture efficiency and the methane has an energy density of $36.0\\ \\text{MJ}/\\text{m}^3$, calculate the electrical power generating capacity in megawatts (MW) at a $38.0\\%$ gas engine electrical efficiency.",
                "hints": [
                    "Compute prefactor: $A = 2 \\times 0.050 \\times 120.0 \\times 150,000$.",
                    "Compute sum of exponential decay terms: $\\sum e^{-0.050 t_i}$ for $t_i \\in \\{1, 2, 3, 4\\}$.",
                    "Total capture rate $= 0.75 Q_{CH4}$. Electrical power $P_{elec} = \\frac{Q_{captured} \\times 36.0 \\times 10^6 \\times 0.38}{365.25 \\times 86400}$."
                ],
                "solution": """**Step 1: Calculate the pre-exponential factor**
Given:
- $k = 0.050\\ \\text{year}^{-1}$
- $L_0 = 120.0\\ \\text{m}^3/\\text{ton}$
- $M = 150,000\\ \\text{tons}$
\\[
A = 2 k L_0 M = 2 \\times (0.050) \\times (120.0) \\times (150,000) = 1,800,000\\ \\text{m}^3/\\text{year}
\\]
*(Note: The LandGEM formulation uses $2 k L_0 M$ when assuming 50% methane in total biogas).*

**Step 2: Calculate methane generation in year 2024**
Waste ages in 2024:
- 2020 waste: $t_1 = 2024 - 2020 = 4\\ \\text{years} \\implies e^{-0.050(4)} = e^{-0.20} = 0.81873$
- 2021 waste: $t_2 = 2024 - 2021 = 3\\ \\text{years} \\implies e^{-0.050(3)} = e^{-0.15} = 0.86071$
- 2022 waste: $t_3 = 2024 - 2022 = 2\\ \\text{years} \\implies e^{-0.050(2)} = e^{-0.10} = 0.90484$
- 2023 waste: $t_4 = 2024 - 2023 = 1\\ \\text{year} \\implies e^{-0.050(1)} = e^{-0.05} = 0.95123$

Sum of exponentials:
\\[
\\sum_{i=1}^4 e^{-k t_i} = 0.81873 + 0.86071 + 0.90484 + 0.95123 = 3.53551
\\]
Total methane generated in 2024:
\\[
Q_{CH4} = 1,800,000\\ \\text{m}^3/\\text{year} \\times 3.53551 = 6,363,918\\ \\text{m}^3/\\text{year} \\approx 6.364 \\times 10^6\\ \\text{m}^3/\\text{year}
\\]

**Step 3: Calculate electrical power generation capacity**
Methane captured at $75.0\\%$ collection efficiency:
\\[
Q_{cap} = 6,363,918\\ \\text{m}^3/\\text{year} \\times 0.75 = 4,772,938.5\\ \\text{m}^3/\\text{year}
\\]
Annual thermal energy available ($36.0\\ \\text{MJ}/\\text{m}^3$):
\\[
E_{th} = 4,772,938.5\\ \\text{m}^3/\\text{year} \\times 36.0\\ \\text{MJ}/\\text{m}^3 = 1.71826 \\times 10^8\\ \\text{MJ}/\\text{year} = 1.71826 \\times 10^{14}\\ \\text{J}/\\text{year}
\\]
Continuous thermal power:
\\[
P_{th} = \\frac{1.71826 \\times 10^{14}\\ \\text{J}}{365.25 \\times 86,400\\ \\text{s}} = \\frac{1.71826 \\times 10^{14}}{3.15576 \\times 10^7\\ \\text{s}} = 5.4448 \\times 10^6\\ \\text{W} = 5.445\\ \\text{MW}_{th}
\\]
Electrical power output at $38.0\\%$ efficiency:
\\[
P_{elec} = 5.445\\ \\text{MW}_{th} \\times 0.380 = 2.069\\ \\text{MW}_{e} \\approx 2.07\\ \\text{MW}
\\]

**Conclusion**:
In 2024, the landfill generates **$6.36 \\times 10^6\\ \\text{m}^3/\\text{year}$ of methane**, sustaining a continuous electrical power generation of **$2.07\\ \\text{MW}$**."""
            },
            {
                "id": "prob_9_5",
                "tier": "Intermediate",
                "title": "Incineration Flue Gas Neutralization: Wet Scrubbing Stoichiometry",
                "statement": "A mass-burn MSW waste-to-energy plant combusts $500.0\\ \\text{metric tons}/\\text{day}$ of waste, generating a normalized flue gas volume of $V_{gas} = 2.50 \\times 10^6\\ \\text{Nm}^3/\\text{day}$. Raw flue gas exiting the boiler contains hydrogen chloride $[HCl] = 850.0\\ \\text{mg}/\\text{Nm}^3$ and sulfur dioxide $[SO_2] = 420.0\\ \\text{mg}/\\text{Nm}^3$. Neutralization in a spray dryer scrubber uses dry hydrated lime ($\\text{Ca(OH)}_2$, $92.0\\%$ purity, molar mass $74.09\\ \\text{g}/\\text{mol}$). The stoichiometric reactions are: (1) $\\text{Ca(OH)}_2 + 2\\text{HCl} \\rightarrow \\text{CaCl}_2 + 2\\text{H}_2\\text{O}$, and (2) $\\text{Ca(OH)}_2 + \\text{SO}_2 + \\frac{1}{2}\\text{O}_2 \\rightarrow \\text{CaSO}_4 + \\text{H}_2\\text{O}$. (a) Calculate the daily emission mass of $HCl$ (molar mass $36.46\\ \\text{g}/\\text{mol}$) and $SO_2$ (molar mass $64.06\\ \\text{g}/\\text{mol}$) in kilograms. (b) Determine the stoichiometric mass of pure $\\text{Ca(OH)}_2$ required per day. (c) If standard acid scrubbing requires a stoichiometric ratio of $\\text{SR} = 1.60$ to achieve $> 98\\%$ acid gas capture, calculate the daily mass of commercial $92.0\\%$ hydrated lime consumed in metric tons per day.",
                "hints": [
                    "Daily pollutant masses: $M = V_{gas} \\times C$.",
                    "Moles of pollutants: $n_{HCl} = M_{HCl} / 36.46$, $n_{SO2} = M_{SO2} / 64.06$.",
                    "Moles of $\\text{Ca(OH)}_2$ required: $n_{lime} = 0.5 n_{HCl} + n_{SO2}$.",
                    "Commercial mass: $M_{comm} = \\frac{M_{pure} \\times \\text{SR}}{\\text{Purity}}$."
                ],
                "solution": """**Step 1: Calculate daily mass of acid gas emissions**
Given $V_{gas} = 2.50 \\times 10^6\\ \\text{Nm}^3/\\text{day}$:
1. **Hydrogen Chloride ($HCl$)**:
   \\[
   M_{HCl} = (2.50 \\times 10^6\\ \\text{Nm}^3) \\times (850.0 \\times 10^{-6}\\ \\text{kg}/\\text{Nm}^3) = 2,125.0\\ \\text{kg HCl/day}
   \\]
   Moles of $HCl$:
   \\[
   n_{HCl} = \\frac{2,125.0\\ \\text{kg}}{36.461\\ \\text{kg}/\\text{kmol}} = 58.281\\ \\text{kmol HCl/day}
   \\]
2. **Sulfur Dioxide ($SO_2$)**:
   \\[
   M_{SO2} = (2.50 \\times 10^6\\ \\text{Nm}^3) \\times (420.0 \\times 10^{-6}\\ \\text{kg}/\\text{Nm}^3) = 1,050.0\\ \\text{kg SO}_2\\text{/day}
   \\]
   Moles of $SO_2$:
   \\[
   n_{SO2} = \\frac{1,050.0\\ \\text{kg}}{64.064\\ \\text{kg}/\\text{kmol}} = 16.390\\ \\text{kmol SO}_2\\text{/day}
   \\]

**Step 2: Determine stoichiometric mass of pure $\\text{Ca(OH)}_2$**
From the balanced reactions:
- $2\\ \\text{mol } HCl$ requires $1\\ \\text{mol } \\text{Ca(OH)}_2 \\implies n_{lime, HCl} = 0.5 \\times 58.281 = 29.141\\ \\text{kmol}$
- $1\\ \\text{mol } SO_2$ requires $1\\ \\text{mol } \\text{Ca(OH)}_2 \\implies n_{lime, SO2} = 16.390\\ \\text{kmol}$

Total stoichiometric moles of lime:
\\[
n_{lime, stoich} = 29.141 + 16.390 = 45.531\\ \\text{kmol/day}
\\]
Theoretical stoichiometric mass ($M = 74.093\\ \\text{g}/\\text{mol}$):
\\[
M_{lime, stoich} = 45.531\\ \\text{kmol} \\times 74.093\\ \\text{kg}/\\text{kmol} = 3,373.5\\ \\text{kg/day}
\\]

**Step 3: Calculate actual commercial lime requirement**
Applying the operating stoichiometric ratio $\\text{SR} = 1.60$ and $92.0\\%$ purity:
\\[
M_{comm} = \\frac{M_{lime, stoich} \\times \\text{SR}}{\\text{Purity}} = \\frac{3,373.5\\ \\text{kg/day} \\times 1.60}{0.920} = \\frac{5,397.6}{0.920} = 5,866.96\\ \\text{kg/day}
\\]
Converting to metric tons:
\\[
M_{comm} = 5.867\\ \\text{metric tons/day} \\approx 5.87\\ \\text{tons/day}
\\]

**Conclusion**:
Neutralizing daily emissions of **$2,125\\ \\text{kg of } HCl$** and **$1,050\\ \\text{kg of } SO_2$** requires **$5.87\\ \\text{metric tons/day}$** of commercial hydrated lime."""
            },
            {
                "id": "prob_9_6",
                "tier": "Intermediate",
                "title": "Solidification/Stabilization of Heavy Metal Sludge in Portland Cement",
                "statement": "An electroplating hydroxide filter cake containing $12.0\\ \\text{wt}\\%$ total chromium (as $Cr(OH)_3$) and $65.0\\ \\text{wt}\\%$ moisture is immobilized via cementitious solidification/stabilization (S/S). The mix design specifies: $1000\\ \\text{kg}$ wet sludge cake, $400\\ \\text{kg}$ Ordinary Portland Cement (OPC), $200\\ \\text{kg}$ Class F coal fly ash, and $150\\ \\text{kg}$ supplemental water. (a) Calculate the total mass of the fresh solidified grout mix and the waste loading ratio ($M_{wet\\ sludge} / M_{total}$). (b) Calculate the total mass of chromium metal in the block in kilograms, and its mass concentration in the cured solid block (in $\\text{mg Cr}/\\text{kg dry solids}$, assuming $15\\%$ of total mix water is lost to hydration/evaporation). (c) In an ANS 16.1 semi-dynamic leaching test, a cured cylindrical monolith ($V = 1000\\ \\text{cm}^3$, surface area $S = 550\\ \\text{cm}^2$) leaches a cumulative total of $m_{leached} = 2.40\\ \\text{mg}$ of chromium over 90 days. Calculate the cumulative fraction leached ($CFL = m_{leached} / m_{initial}$) and the effective diffusion coefficient $D_e$ using the short-term diffusion equation: $CFL = 2 \\left( \\frac{S}{V} \\right) \\sqrt{\\frac{D_e t}{\\pi}}$.",
                "hints": [
                    "Total mass: sum of all ingredients.",
                    "Chromium mass $= 1000\\ \\text{kg} \\times 0.12$.",
                    "Solve for $D_e$: $D_e = \\frac{\\pi}{t} \\left( \\frac{CFL}{2 (S/V)} \\right)^2$ with $t = 90 \\times 86400\\ \\text{s}$."
                ],
                "solution": """**Step 1: Calculate total batch mass and waste loading**
Batch constituents:
- Wet sludge cake: $1000\\ \\text{kg}$
- OPC cement: $400\\ \\text{kg}$
- Fly ash: $200\\ \\text{kg}$
- Supplemental water: $150\\ \\text{kg}$

Total initial mass:
\\[
M_{total} = 1000 + 400 + 200 + 150 = 1750\\ \\text{kg}
\\]
Waste loading ratio on a wet basis:
\\[
\\text{Waste Loading} = \\frac{1000\\ \\text{kg}}{1750\\ \\text{kg}} \\times 100 = 57.14\\%
\\]

**Step 2: Calculate total chromium and concentration in cured block**
Total mass of chromium metal:
\\[
m_{Cr} = 1000\\ \\text{kg sludge} \\times 0.120 = 120.0\\ \\text{kg of Cr}
\\]
Total initial water in mix:
\\[
m_{H2O} = (1000 \\times 0.65) + 150 = 650 + 150 = 800\\ \\text{kg}
\\]
Dry solid ingredients $= (1000 - 650) + 400 + 200 = 350 + 400 + 200 = 950\\ \\text{kg}$.
Assuming $15\\%$ water loss, retained bound water is $800 \\times 0.85 = 680\\ \\text{kg}$.
Cured block mass:
\\[
M_{cured} = 950 + 680 = 1630\\ \\text{kg}
\\]
Chromium concentration in the cured solid:
\\[
C_{Cr, block} = \\frac{120.0\\ \\text{kg}}{1630\\ \\text{kg}} \\times 10^6 = 73,619.6\\ \\text{mg}/\\text{kg} \\approx 7.36\\ \\text{wt}\\%
\\]

**Step 3: Calculate Cumulative Fraction Leached (CFL) and Effective Diffusion Coefficient $D_e$**
For the cylindrical test specimen ($V = 1000\\ \\text{cm}^3 = 1.00 \\times 10^{-3}\\ \\text{m}^3$, $S = 550\\ \\text{cm}^2 = 0.0550\\ \\text{m}^2$):
Ratio of surface area to volume:
\\[
\\frac{S}{V} = \\frac{0.0550\\ \\text{m}^2}{1.00 \\times 10^{-3}\\ \\text{m}^3} = 55.0\\ \\text{m}^{-1}
\\]
Specimen mass (assuming density $\\rho = 2000\\ \\text{kg}/\\text{m}^3$): $M_{spec} = 2.00\\ \\text{kg}$.
Initial chromium in specimen:
\\[
m_{initial} = 2.00\\ \\text{kg} \\times 0.07362 = 0.14724\\ \\text{kg} = 147,240\\ \\text{mg}
\\]
Cumulative fraction leached ($m_{leached} = 2.40\\ \\text{mg}$):
\\[
CFL = \\frac{2.40\\ \\text{mg}}{147,240\\ \\text{mg}} = 1.6300 \\times 10^{-5}
\\]
Diffusion time $t = 90\\ \\text{days} = 90 \\times 86,400\\ \\text{s} = 7,776,000\\ \\text{s}$.
From the semi-infinite solid diffusion model:
\\[
CFL = 2 \\left( \\frac{S}{V} \\right) \\sqrt{\\frac{D_e t}{\\pi}}
\\]
Solving for $D_e$:
\\[
\\sqrt{\\frac{D_e t}{\\pi}} = \\frac{CFL}{2 (S/V)} = \\frac{1.6300 \\times 10^{-5}}{2 \\times 55.0\\ \\text{m}^{-1}} = \\frac{1.6300 \\times 10^{-5}}{110.0} = 1.4818 \\times 10^{-7}\\ \\text{m}
\\]
Squaring both sides:
\\[
\\frac{D_e t}{\\pi} = (1.4818 \\times 10^{-7})^2 = 2.1958 \\times 10^{-14}\\ \\text{m}^2
\\]
\\[
D_e = \\frac{\\pi \\times 2.1958 \\times 10^{-14}\\ \\text{m}^2}{7,776,000\\ \\text{s}} = \\frac{6.8983 \\times 10^{-14}}{7,776,000} = 8.871 \\times 10^{-21}\\ \\text{m}^2/\\text{s}
\\]
The Leachability Index ($LI = -\\log_{10} D_e$ with $D_e$ in $\\text{cm}^2/\\text{s}$):
\\[
D_e = 8.871 \\times 10^{-17}\\ \\text{cm}^2/\\text{s} \\implies LI = -\\log_{10}(8.871 \\times 10^{-17}) = 16.05
\\]

**Conclusion**:
The effective diffusion coefficient is an extraordinarily low **$8.87 \\times 10^{-21}\\ \\text{m}^2/\\text{s}$** ($LI = 16.05 > 9.0$), proving complete cementitious encapsulation and permanent heavy metal immobilization."""
            },
            {
                "id": "prob_9_7",
                "tier": "Advanced",
                "title": "Pyrolysis Thermogravimetric Kinetics: Coats-Redfern Integral Method",
                "statement": "The non-isothermal pyrolysis of waste polypropylene plastic is analyzed via thermogravimetry (TGA) at a constant heating rate $\\beta = \\frac{dT}{dt} = 10.0\\ \\text{K}/\\text{min} = 0.1667\\ \\text{K}/\\text{s}$. Thermal decomposition follows a first-order reaction mechanism $g(\\alpha) = -\\ln(1 - \\alpha)$. According to the Coats-Redfern integral method: $\\ln\\left[ \\frac{-\\ln(1 - \\alpha)}{T^2} \\right] = \\ln\\left( \\frac{A R}{\\beta E_a} \\right) - \\frac{E_a}{R T}$, where $T$ is absolute temperature, $E_a$ is activation energy, and $A$ is pre-exponential factor ($R = 8.314\\ \\text{J}/(\\text{mol}\\cdot\\text{K})$). Experimental thermograms yield two points: Point 1: At $T_1 = 693.15\\ \\text{K}$ ($420^\\circ\\text{C}$), conversion $\\alpha_1 = 0.200$; Point 2: At $T_2 = 743.15\\ \\text{K}$ ($470^\\circ\\text{C}$), conversion $\\alpha_2 = 0.850$. (a) Evaluate the Coats-Redfern function $Y = \\ln\\left[ \\frac{-\\ln(1 - \\alpha)}{T^2} \\right]$ and $X = 1/T$ at both temperatures. (b) Determine the apparent activation energy $E_a$ in $\\text{kJ}/\\text{mol}$. (c) Calculate the pre-exponential frequency factor $A$ in $\\text{s}^{-1}$.",
                "hints": [
                    "Point 1: $-\\ln(1 - 0.20) = -\\ln(0.80) = 0.22314$. Compute $Y_1 = \\ln(0.22314 / 693.15^2)$.",
                    "Point 2: $-\\ln(1 - 0.85) = -\\ln(0.15) = 1.89712$. Compute $Y_2 = \\ln(1.89712 / 743.15^2)$.",
                    "Slope $= -E_a / R = \\frac{Y_2 - Y_1}{X_2 - X_1}$."
                ],
                "solution": """**Step 1: Evaluate $Y$ and $X$ values at both experimental points**
1. **At Point 1 ($T_1 = 693.15\\ \\text{K}$, $\\alpha_1 = 0.200$)**:
   \\[
   g(\\alpha_1) = -\\ln(1 - 0.200) = -\\ln(0.800) = 0.223144
   \\]
   \\[
   T_1^2 = (693.15)^2 = 480,456.9\\ \\text{K}^2
   \\]
   \\[
   \\frac{g(\\alpha_1)}{T_1^2} = \\frac{0.223144}{480,456.9} = 4.6444 \\times 10^{-7}\\ \\text{K}^{-2}
   \\]
   \\[
   Y_1 = \\ln(4.6444 \\times 10^{-7}) = -14.5823
   \\]
   \\[
   X_1 = \\frac{1}{T_1} = \\frac{1}{693.15} = 1.44269 \\times 10^{-3}\\ \\text{K}^{-1}
   \\]

2. **At Point 2 ($T_2 = 743.15\\ \\text{K}$, $\\alpha_2 = 0.850$)**:
   \\[
   g(\\alpha_2) = -\\ln(1 - 0.850) = -\\ln(0.150) = 1.897120
   \\]
   \\[
   T_2^2 = (743.15)^2 = 552,271.9\\ \\text{K}^2
   \\]
   \\[
   \\frac{g(\\alpha_2)}{T_2^2} = \\frac{1.897120}{552,271.9} = 3.43512 \\times 10^{-6}\\ \\text{K}^{-2}
   \\]
   \\[
   Y_2 = \\ln(3.43512 \\times 10^{-6}) = -12.5815
   \\]
   \\[
   X_2 = \\frac{1}{T_2} = \\frac{1}{743.15} = 1.34562 \\times 10^{-3}\\ \\text{K}^{-1}
   \\]

**Step 2: Calculate activation energy $E_a$**
The slope of the Coats-Redfern line:
\\[
\\text{Slope} = \\frac{Y_2 - Y_1}{X_2 - X_1} = \\frac{-12.5815 - (-14.5823)}{1.34562 \\times 10^{-3} - 1.44269 \\times 10^{-3}} = \\frac{+2.0008}{-9.707 \\times 10^{-5}} = -20,611.9\\ \\text{K}
\\]
Since $\\text{Slope} = -\\frac{E_a}{R}$:
\\[
E_a = -\\text{Slope} \\times R = -(-20,611.9\\ \\text{K}) \\times (8.3145\\ \\text{J}/(\\text{mol}\\cdot\\text{K})) = 171,378\\ \\text{J}/\\text{mol} = 171.38\\ \\text{kJ}/\\text{mol}
\\]

**Step 3: Calculate pre-exponential factor $A$**
The y-intercept:
\\[
\\text{Intercept} = Y_1 - \\text{Slope} \\times X_1 = -14.5823 - (-20,611.9 \\times 1.44269 \\times 10^{-3}) = -14.5823 + 29.7366 = +15.1543
\\]
Since $\\text{Intercept} = \\ln\\left( \\frac{A R}{\\beta E_a} \\right)$:
\\[
\\frac{A R}{\\beta E_a} = e^{15.1543} = 3,814,460
\\]
Given $\\beta = 0.16667\\ \\text{K}/\\text{s}$:
\\[
A = \\frac{3,814,460 \\times \\beta \\times E_a}{R} = \\frac{3,814,460 \\times 0.16667 \\times 171,378}{8.3145}
\\]
\\[
A = \\frac{1.08953 \\times 10^{11}}{8.3145} = 1.3104 \\times 10^{10}\\ \\text{s}^{-1} \\approx 1.31 \\times 10^{10}\\ \\text{s}^{-1}
\\]

**Conclusion**:
The pyrolysis exhibits an apparent activation energy of **$171.4\\ \\text{kJ}/\\text{mol}$** and a frequency factor of **$1.31 \\times 10^{10}\\ \\text{s}^{-1}$**, matching radical carbon-carbon scission mechanisms."""
            },
            {
                "id": "prob_9_8",
                "tier": "Advanced",
                "title": "Hydrometallurgical Gold Leaching from E-Waste via Acidic Thiourea",
                "statement": "Gold is recovered from pulverized smartphone printed circuit board scrap ($1.0\\ \\text{metric ton}$ batch containing $[Au] = 280.0\\ \\text{g Au}/\\text{ton}$) via non-cyanide hydrometallurgical leaching with acidic thiourea ($CS(NH_2)_2$, $Tu$, molar mass $76.12\\ \\text{g}/\\text{mol}$) using ferric sulfate ($\\text{Fe}_2(\\text{SO}_4)_3$) oxidant: $\\text{Au} + 2\\text{Tu} + \\text{Fe}^{3+} \\rightarrow [\\text{Au(Tu)}_2]^+ + \\text{Fe}^{2+}$. In a batch reactor ($V = 2000\\ \\text{L}$), the leaching kinetics follows the surface-reaction controlled shrinking core model: $1 - (1 - X)^{1/3} = k_{app} t$, where apparent rate constant $k_{app} = 0.0450\\ \\text{h}^{-1}$. (a) Calculate the leaching time in hours required to achieve $95.0\\%$ gold recovery ($X = 0.950$). (b) Calculate the theoretical stoichiometric mass of pure thiourea consumed by the gold in the batch in grams. (c) In practice, ferric ions oxidatively decompose thiourea into formamidine disulfide ($FDS$): $2\\text{Tu} + 2\\text{Fe}^{3+} \\rightarrow \\text{FDS} + 2\\text{Fe}^{2+} + 2\\text{H}^+$. If $85.0\\%$ of total thiourea consumption is lost to this side reaction, calculate the actual total mass of thiourea required in kilograms.",
                "hints": [
                    "Evaluate $1 - (1 - 0.95)^{1/3} = k_{app} t$.",
                    "Stoichiometry: $1\\ \\text{mol Au}$ ($196.97\\ \\text{g}$) consumes $2\\ \\text{mol Tu}$ ($2 \\times 76.12\\ \\text{g} = 152.24\\ \\text{g}$).",
                    "If side reaction consumes $85\\%$, gold reaction accounts for only $15\\%$ of total."
                ],
                "solution": """**Step 1: Calculate leaching time for $95.0\\%$ recovery**
From the shrinking core kinetic equation:
\\[
1 - (1 - X)^{1/3} = k_{app} t
\\]
For $X = 0.950$:
\\[
1 - X = 1 - 0.950 = 0.050
\\]
\\[
(0.050)^{1/3} = 0.36840
\\]
\\[
1 - 0.36840 = 0.63160
\\]
Given $k_{app} = 0.0450\\ \\text{h}^{-1}$:
\\[
t = \\frac{0.63160}{0.0450\\ \\text{h}^{-1}} = 14.036\\ \\text{hours} \\approx 14.0\\ \\text{hours}
\\]

**Step 2: Calculate stoichiometric thiourea consumed by gold**
Total gold in batch:
\\[
m_{Au} = 280.0\\ \\text{g Au}
\\]
Moles of gold ($M_{Au} = 196.967\\ \\text{g}/\\text{mol}$):
\\[
n_{Au} = \\frac{280.0\\ \\text{g}}{196.967\\ \\text{g}/\\text{mol}} = 1.4216\\ \\text{mol Au}
\\]
Stoichiometric moles of thiourea ($2\\ \\text{mol Tu} / \\text{mol Au}$):
\\[
n_{Tu, stoich} = 2 \\times 1.4216 = 2.8431\\ \\text{mol Tu}
\\]
Mass of thiourea ($M_{Tu} = 76.12\\ \\text{g}/\\text{mol}$):
\\[
m_{Tu, stoich} = 2.8431\\ \\text{mol} \\times 76.12\\ \\text{g}/\\text{mol} = 216.42\\ \\text{g Tu} = 0.2164\\ \\text{kg}
\\]

**Step 3: Calculate actual thiourea demand including oxidative degradation**
Since oxidative degradation consumes $85.0\\%$ of total thiourea, gold complexation accounts for only $15.0\\%$ ($0.150$) of the reagent consumed:
\\[
m_{Tu, total} = \\frac{m_{Tu, stoich}}{0.150} = \\frac{0.2164\\ \\text{kg}}{0.150} = 1.4428\\ \\text{kg Tu} \\approx 1.44\\ \\text{kg}
\\]
To maintain required excess active background concentration in the $2000\\ \\text{L}$ reactor (typically $15.0\\ \\text{g}/\\text{L}$):
\\[
m_{Tu, solvent} = 2000\\ \\text{L} \\times 0.015\\ \\text{kg}/\\text{L} = 30.0\\ \\text{kg}
\\]

**Conclusion**:
Achieving $95\\%$ extraction requires **14.0 hours**. Stoichiometric gold extraction consumes **$216.4\\ \\text{g of thiourea}$**, but oxidative decomposition expands consumption to **$1.44\\ \\text{kg}$**."""
            },
            {
                "id": "prob_9_9",
                "tier": "Advanced",
                "title": "Dynamic Material Flow Analysis and Circular Material Use Rate of Plastics",
                "statement": "A municipal plastics circular economy system processes post-consumer plastic packaging with an annual collection flow of $F_0 = 100,000\\ \\text{metric tons}/\\text{year}$. The material flows through the following stages: (1) Sorting & Material Recovery Facility (MRF): sorting efficiency $\\eta_1 = 80.0\\%$ (the remaining $20\\%$ rejects go to WtE incineration); (2) Mechanical Recycling: yield $\\eta_2 = 75.0\\%$ producing clean secondary polymer pellets, while $25\\%$ wash/extrusion residues feed a chemical pyrolysis plant; (3) Pyrolysis Plant: conversion yield $\\eta_3 = 60.0\\%$ into circular naphtha cracker feedstock. The total municipal packaging manufacturing demand is $D = 120,000\\ \\text{tons}/\\text{year}$. (a) Calculate the annual mass flow of mechanically recycled polymer pellets $F_{mech}$ and chemically recycled circular naphtha $F_{chem}$ in tons/year. (b) Calculate the total circular secondary material recovery $F_{circ} = F_{mech} + F_{chem}$ and the overall end-to-end recycling yield. (c) Calculate the Circular Material Use Rate ($CMUR\\% = \\frac{F_{circ}}{D} \\times 100$).",
                "hints": [
                    "Clean sorted plastics: $F_1 = F_0 \\times 0.80$.",
                    "Mechanical pellets: $F_{mech} = F_1 \\times 0.75$.",
                    "Residue to pyrolysis: $F_{res} = F_1 \\times 0.25$. Circular naphtha: $F_{chem} = F_{res} \\times 0.60$.",
                    "Circularity rate: $CMUR = (F_{circ} / D) \\times 100$."
                ],
                "solution": """**Step 1: Calculate flows through MRF and Mechanical Recycling**
1. **Initial Collection Flow**:
   \\[
   F_0 = 100,000\\ \\text{tons/year}
   \\]
2. **After MRF Sorting ($\\eta_1 = 80.0\\%$)**:
   \\[
   F_1 = 100,000 \\times 0.800 = 80,000\\ \\text{tons/year}
   \\]
   (Rejects to WtE incineration: $20,000\\ \\text{tons/year}$).
3. **Mechanical Recycling ($\\eta_2 = 75.0\\%$)**:
   \\[
   F_{mech} = F_1 \\times 0.750 = 80,000 \\times 0.750 = 60,000\\ \\text{tons/year}
   \\]
   Residues diverted to chemical recycling:
   \\[
   F_{res} = F_1 \\times (1 - 0.750) = 80,000 \\times 0.250 = 20,000\\ \\text{tons/year}
   \\]

**Step 2: Calculate Chemical Recycling Flow and Total Circular Output**
Pyrolysis conversion yield is $\\eta_3 = 60.0\\%$:
\\[
F_{chem} = F_{res} \\times \\eta_3 = 20,000 \\times 0.600 = 12,000\\ \\text{tons/year}
\\]
Total recovered circular materials:
\\[
F_{circ} = F_{mech} + F_{chem} = 60,000 + 12,000 = 72,000\\ \\text{tons/year}
\\]
Overall end-to-end material recovery yield from collected waste:
\\[
\\eta_{system} = \\frac{F_{circ}}{F_0} \\times 100 = \\frac{72,000}{100,000} \\times 100 = 72.0\\%
\\]

**Step 3: Calculate Circular Material Use Rate ($CMUR\\%$)**
Given total market demand $D = 120,000\\ \\text{tons/year}$:
\\[
CMUR = \\left( \\frac{F_{circ}}{D} \\right) \\times 100 = \\left( \\frac{72,000\\ \\text{tons/year}}{120,000\\ \\text{tons/year}} \\right) \\times 100 = 60.00\\%
\\]
The virgin polymer demand displaced:
\\[
F_{virgin} = D - F_{circ} = 120,000 - 72,000 = 48,000\\ \\text{tons/year}
\\]

**Conclusion**:
The integrated system recovers **$60,000\\ \\text{tons}$ of mechanical pellets** and **$12,000\\ \\text{tons}$ of circular naphtha** ($72\\%$ system recovery), achieving a **$60.0\\%$ Circular Material Use Rate**."""
            }
        ]
    }
    return unit

if __name__ == "__main__":
    u9 = get_unit_9()
    print(f"Unit 9 generated: {len(u9['sections'])} sections, {len(u9['problems'])} problems.")
