// Electrodynamics Simulation Engine Suite
// High-performance 60 FPS Canvas renderers with interactive sliders and parameter controls

window.SimulationEngine = {
  activeInstances: {},

  initSimulation: function(containerId, simType) {
    const container = document.getElementById(containerId);
    if (!container) return;
    
    // Clean up existing instance
    if (this.activeInstances[containerId]) {
      this.activeInstances[containerId].destroy();
    }

    container.innerHTML = "";
    
    switch(simType) {
      case "displacement-current":
        this.activeInstances[containerId] = new DisplacementCurrentSim(container);
        break;
      case "poynting-vector":
        this.activeInstances[containerId] = new PoyntingSim(container);
        break;
      case "em-wave-3d":
        this.activeInstances[containerId] = new EMWave3DSim(container);
        break;
      case "skin-depth":
        this.activeInstances[containerId] = new SkinDepthSim(container);
        break;
      case "fresnel-reflection":
        this.activeInstances[containerId] = new FresnelSim(container);
        break;
      case "waveguide-modes":
        this.activeInstances[containerId] = new WaveguideSim(container);
        break;
      case "dipole-radiation":
        this.activeInstances[containerId] = new DipoleRadiationSim(container);
        break;
      case "scattering-simulator":
        this.activeInstances[containerId] = new ScatteringSim(container);
        break;
      case "drude-lorentz":
        this.activeInstances[containerId] = new DrudeLorentzSim(container);
        break;
      case "radiation-pressure-sim":
        this.activeInstances[containerId] = new RadiationPressureSim(container);
        break;
      case "plasma-cutoff-sim":
        this.activeInstances[containerId] = new PlasmaCutoffSim(container);
        break;
      case "snell-refraction-sim":
        this.activeInstances[containerId] = new SnellRefractionSim(container);
        break;
      case "cavity-resonator-sim":
        this.activeInstances[containerId] = new CavityResonatorSim(container);
        break;
      case "retarded-potential-sim":
        this.activeInstances[containerId] = new RetardedPotentialSim(container);
        break;
      case "antenna-radiation-sim":
        this.activeInstances[containerId] = new AntennaRadiationSim(container);
        break;
      case "polarization-sky-sim":
        this.activeInstances[containerId] = new PolarizationSkySim(container);
        break;
      case "sellmeier-prism-sim":
        this.activeInstances[containerId] = new SellmeierPrismSim(container);
        break;
      default:
        console.warn("Unknown simulation type:", simType);
    }
  }
};

// ==========================================
// 1. Displacement Current & Induced B-Field
// ==========================================
class DisplacementCurrentSim {
  constructor(container) {
    this.container = container;
    this.current = 2.0; // Amperes
    this.t = 0;
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.startLoop();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 1.1</span>
            <strong>Capacitor Displacement Current $J_d = \\epsilon_0 \\frac{\\partial E}{\\partial t}$ & Induced Magnetic Field</strong>
          </div>
          <div class="slider-control-group">
            <label>Charging Current $I$: <strong id="dc-i-val">2.0 A</strong></label>
            <input type="range" id="dc-i-slider" min="5" max="50" value="20" class="range-slider">
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="dc-canvas" width="760" height="340"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-footer">
          <div class="sim-hint">
            💡 Cyan arrows: Electric field $\\mathbf{E}$ between plates. Orange circular loops: Induced magnetic field $\\mathbf{B}$ generated by the time-varying electric flux (Maxwell's displacement current).
          </div>
        </div>
      </div>
    `;

    document.getElementById("dc-i-slider").oninput = (e) => {
      this.current = (parseFloat(e.target.value) / 10).toFixed(1);
      document.getElementById("dc-i-val").innerText = this.current + " A";
    };
  }

  initCanvas() {
    this.canvas = document.getElementById("dc-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  startLoop() {
    const loop = () => {
      this.t += 0.03 * (this.current / 2);
      this.draw();
      this.animId = requestAnimationFrame(loop);
    };
    this.animId = requestAnimationFrame(loop);
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const midY = 170;
    const p1X = 260;
    const p2X = 500;
    const plateH = 160;

    // Draw Incoming Wire Left
    ctx.strokeStyle = "#94a3b8";
    ctx.lineWidth = 6;
    ctx.beginPath();
    ctx.moveTo(30, midY);
    ctx.lineTo(p1X, midY);
    ctx.stroke();

    // Draw Outgoing Wire Right
    ctx.beginPath();
    ctx.moveTo(p2X, midY);
    ctx.lineTo(canvas.width - 30, midY);
    ctx.stroke();

    // Conduction current arrows
    ctx.fillStyle = "#38bdf8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText(`Conduction Current I = ${this.current} A →`, 60, midY - 15);
    ctx.fillText(`→ I = ${this.current} A`, p2X + 60, midY - 15);

    // Capacitor Plate 1 (Left, +Q)
    ctx.fillStyle = "rgba(56, 189, 248, 0.25)";
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 4;
    ctx.fillRect(p1X - 8, midY - plateH/2, 16, plateH);
    ctx.strokeRect(p1X - 8, midY - plateH/2, 16, plateH);
    ctx.fillStyle = "#38bdf8";
    ctx.fillText("+Q (Positive Plate)", p1X - 60, midY - plateH/2 - 12);

    // Capacitor Plate 2 (Right, -Q)
    ctx.fillStyle = "rgba(244, 63, 94, 0.25)";
    ctx.strokeStyle = "#f43f5e";
    ctx.lineWidth = 4;
    ctx.fillRect(p2X - 8, midY - plateH/2, 16, plateH);
    ctx.strokeRect(p2X - 8, midY - plateH/2, 16, plateH);
    ctx.fillStyle = "#f43f5e";
    ctx.fillText("-Q (Negative Plate)", p2X - 10, midY - plateH/2 - 12);

    // Electric Field Lines (Cyan horizontal arrows)
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2;
    for (let y = midY - 60; y <= midY + 60; y += 30) {
      ctx.beginPath();
      ctx.moveTo(p1X + 10, y);
      ctx.lineTo(p2X - 10, y);
      ctx.stroke();

      // Arrowhead
      ctx.beginPath();
      ctx.moveTo(p2X - 18, y - 5);
      ctx.lineTo(p2X - 10, y);
      ctx.lineTo(p2X - 18, y + 5);
      ctx.stroke();
    }
    ctx.fillStyle = "#38bdf8";
    ctx.fillText("Electric Field E(t)", 340, midY - 70);

    // Circular Induced Magnetic Field Loops (Perspective Ellipses)
    const gapCenterX = (p1X + p2X) / 2;
    ctx.strokeStyle = "#f59e0b";
    ctx.lineWidth = 2;

    const numLoops = 3;
    for (let l = 1; l <= numLoops; l++) {
      const rx = 18 + l * 20;
      const ry = 28 + l * 26;

      ctx.beginPath();
      ctx.ellipse(gapCenterX, midY, rx, ry, 0, 0, Math.PI * 2);
      ctx.stroke();

      // Animated circulating dots on B-field loop
      const angle = this.t + (l * 0.8);
      const bx = gapCenterX + rx * Math.cos(angle);
      const by = midY + ry * Math.sin(angle);

      ctx.fillStyle = "#fbbf24";
      ctx.beginPath();
      ctx.arc(bx, by, 3.5, 0, Math.PI * 2);
      ctx.fill();
    }

    ctx.fillStyle = "#f59e0b";
    ctx.fillText("Induced Magnetic Field B(r)", gapCenterX - 75, midY + plateH/2 + 25);
    ctx.fillText(`J_d = ε₀ ∂E/∂t = ${this.current} A / Area`, gapCenterX - 70, midY + plateH/2 + 42);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 2. Poynting Vector Energy Flow
// ==========================================
class PoyntingSim {
  constructor(container) {
    this.container = container;
    this.t = 0;
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.startLoop();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 1.2</span>
            <strong>Poynting Vector Energy Flux: $\\mathbf{S} = \\frac{1}{\\mu_0} (\\mathbf{E} \\times \\mathbf{B})$ into a Resistor</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="poy-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-footer">
          <div class="sim-hint">
            💡 Notice that the Poynting vector $\\mathbf{S}$ points <strong>radially inward</strong> from the surrounding space into the cylindrical wire surface, accounting for the rate of dissipated Joule heating $\\oint \\mathbf{S} \\cdot d\\mathbf{A} = I^2 R$!
          </div>
        </div>
      </div>
    `;
  }

  initCanvas() {
    this.canvas = document.getElementById("poy-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  startLoop() {
    const loop = () => {
      this.t += 0.04;
      this.draw();
      this.animId = requestAnimationFrame(loop);
    };
    this.animId = requestAnimationFrame(loop);
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const wireX = 140;
    const wireW = 480;
    const wireY = 110;
    const wireH = 80;

    // Draw Cylindrical Resistor
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(wireX, wireY, wireW, wireH);
    ctx.strokeStyle = "#475569";
    ctx.lineWidth = 2;
    ctx.strokeRect(wireX, wireY, wireW, wireH);

    ctx.fillStyle = "#cbd5e1";
    ctx.font = "14px Inter, sans-serif";
    ctx.fillText("Cylindrical Resistor (Resistance R, Current I →)", wireX + 80, wireY + 45);

    // Electric field inside conductor (along length +x)
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2;
    for (let x = wireX + 40; x < wireX + wireW - 40; x += 90) {
      ctx.beginPath();
      ctx.moveTo(x, wireY + 40);
      ctx.lineTo(x + 50, wireY + 40);
      ctx.stroke();
      // Arrowhead
      ctx.beginPath();
      ctx.moveTo(x + 42, wireY + 36);
      ctx.lineTo(x + 50, wireY + 40);
      ctx.lineTo(x + 42, wireY + 44);
      ctx.stroke();
    }
    ctx.fillStyle = "#38bdf8";
    ctx.font = "11px Inter, sans-serif";
    ctx.fillText("E = I / (σ A)", wireX + 20, wireY + 25);

    // Poynting Vectors (Green arrows pointing inward from top and bottom)
    ctx.strokeStyle = "#10b981";
    ctx.lineWidth = 2.5;

    for (let x = wireX + 60; x <= wireX + wireW - 60; x += 80) {
      // Top arrows pointing down
      const topOffset = (this.t * 20) % 20;
      const y1 = 45 + topOffset;
      ctx.beginPath();
      ctx.moveTo(x, y1);
      ctx.lineTo(x, wireY - 4);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(x - 5, wireY - 12);
      ctx.lineTo(x, wireY - 4);
      ctx.lineTo(x + 5, wireY - 12);
      ctx.stroke();

      // Bottom arrows pointing up
      const botY1 = 255 - topOffset;
      ctx.beginPath();
      ctx.moveTo(x, botY1);
      ctx.lineTo(x, wireY + wireH + 4);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(x - 5, wireY + wireH + 12);
      ctx.lineTo(x, wireY + wireH + 4);
      ctx.lineTo(x + 5, wireY + wireH + 12);
      ctx.stroke();
    }

    ctx.fillStyle = "#10b981";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Poynting Vector S = (E × B)/μ₀ ↓", wireX + 160, 35);
    ctx.fillText("Poynting Vector S = (E × B)/μ₀ ↑", wireX + 160, 275);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 3. 3D Transverse EM Wave Propagation
// ==========================================
class EMWave3DSim {
  constructor(container) {
    this.container = container;
    this.wavelength = 180;
    this.animId = null;
    this.t = 0;

    this.renderDOM();
    this.initCanvas();
    this.startLoop();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 2.1</span>
            <strong>3D Transverse Electromagnetic Wave: Orthogonal $\\mathbf{E}$ (Cyan) and $\\mathbf{B}$ (Yellow)</strong>
          </div>
          <div class="slider-control-group">
            <label>Wavelength $\\lambda$: <strong id="em-wl-val">180 px</strong></label>
            <input type="range" id="em-wl-slider" min="100" max="280" value="180" class="range-slider">
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="em-canvas" width="760" height="340"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-footer">
          <div class="sim-hint">
            💡 Notice that $\\mathbf{E}$ and $\\mathbf{B}$ oscillate strictly perpendicular to each other and to the propagation axis $+z$, in perfect phase with speed $c = \\omega / k = 1/\\sqrt{\\mu_0\\epsilon_0}$.
          </div>
        </div>
      </div>
    `;

    document.getElementById("em-wl-slider").oninput = (e) => {
      this.wavelength = parseFloat(e.target.value);
      document.getElementById("em-wl-val").innerText = this.wavelength + " px";
    };
  }

  initCanvas() {
    this.canvas = document.getElementById("em-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  startLoop() {
    const loop = () => {
      this.t += 0.05;
      this.draw();
      this.animId = requestAnimationFrame(loop);
    };
    this.animId = requestAnimationFrame(loop);
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#0a0e19";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const originY = 170;
    const originX = 50;
    const endX = canvas.width - 50;

    // Propagation Axis (z-axis)
    ctx.strokeStyle = "#475569";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(originX, originY);
    ctx.lineTo(endX, originY);
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Propagation Axis +z → (Speed c)", endX - 160, originY - 12);

    const k = (2 * Math.PI) / this.wavelength;
    const ampE = 80;
    const ampB = 45; // projected at oblique angle for 3D depth

    // Draw Magnetic Field Vectors B (Yellow, tilted perspective 45 deg)
    ctx.strokeStyle = "#fbbf24";
    ctx.lineWidth = 1.5;
    for (let x = originX; x <= endX; x += 18) {
      const z = x - originX;
      const val = Math.sin(k * z - this.t);
      const bLen = val * ampB;

      const px = x - bLen * 0.7;
      const py = originY + bLen * 0.5;

      ctx.beginPath();
      ctx.moveTo(x, originY);
      ctx.lineTo(px, py);
      ctx.stroke();

      // Vector head dot
      ctx.fillStyle = "#fbbf24";
      ctx.beginPath();
      ctx.arc(px, py, 2.5, 0, Math.PI * 2);
      ctx.fill();
    }

    // Draw Electric Field Vectors E (Cyan, vertical)
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 1.8;
    for (let x = originX; x <= endX; x += 18) {
      const z = x - originX;
      const val = Math.sin(k * z - this.t);
      const eLen = val * ampE;

      ctx.beginPath();
      ctx.moveTo(x, originY);
      ctx.lineTo(x, originY - eLen);
      ctx.stroke();

      // Vector head dot
      ctx.fillStyle = "#38bdf8";
      ctx.beginPath();
      ctx.arc(x, originY - eLen, 2.5, 0, Math.PI * 2);
      ctx.fill();
    }

    // Envelope curves
    ctx.strokeStyle = "rgba(56, 189, 248, 0.4)";
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let x = originX; x <= endX; x++) {
      const z = x - originX;
      const y = originY - Math.sin(k * z - this.t) * ampE;
      if (x === originX) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();

    ctx.fillStyle = "#38bdf8";
    ctx.fillText("Electric Field E (Vertical)", 60, 45);
    ctx.fillStyle = "#fbbf24";
    ctx.fillText("Magnetic Field B (Horizontal Transverse)", 60, 68);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 4. Conducting Media Wave Attenuation & Skin Depth
// ==========================================
class SkinDepthSim {
  constructor(container) {
    this.container = container;
    this.sigma = 40; // conductivity slider
    this.animId = null;
    this.t = 0;

    this.renderDOM();
    this.initCanvas();
    this.startLoop();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 2.2</span>
            <strong>Electromagnetic Wave Attenuation & Skin Depth: $\\delta = \\sqrt{\\frac{2}{\\mu \\sigma \\omega}}$</strong>
          </div>
          <div class="slider-control-group">
            <label>Conductivity $\\sigma$: <strong id="sd-sig-val">Medium Conductor</strong></label>
            <input type="range" id="sd-sig-slider" min="10" max="90" value="40" class="range-slider">
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="sd-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <div class="metric-label">Skin Depth $\\delta$</div>
            <div class="metric-value text-emerald" id="metric-delta">45 mm</div>
          </div>
          <div class="metric-card">
            <div class="metric-label">Phase Shift in Conductor</div>
            <div class="metric-value text-amber">45° Lag (B behind E)</div>
          </div>
        </div>
      </div>
    `;

    document.getElementById("sd-sig-slider").oninput = (e) => {
      this.sigma = parseFloat(e.target.value);
      const label = this.sigma < 30 ? "Poor Conductor" : (this.sigma < 70 ? "Good Conductor" : "Metal (Copper-like)");
      document.getElementById("sd-sig-val").innerText = label;
      this.updateMetrics();
    };
    this.updateMetrics();
  }

  updateMetrics() {
    const delta = (240 / Math.sqrt(this.sigma)).toFixed(1);
    document.getElementById("metric-delta").innerText = delta + " mm";
  }

  initCanvas() {
    this.canvas = document.getElementById("sd-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  startLoop() {
    const loop = () => {
      this.t += 0.06;
      this.draw();
      this.animId = requestAnimationFrame(loop);
    };
    this.animId = requestAnimationFrame(loop);
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const boundaryX = 280;
    const midY = 150;

    // Draw Conductor Shading (Right Region)
    ctx.fillStyle = "rgba(30, 41, 59, 0.7)";
    ctx.fillRect(boundaryX, 0, canvas.width - boundaryX, canvas.height);

    // Boundary Line
    ctx.strokeStyle = "#e2e8f0";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(boundaryX, 0);
    ctx.lineTo(boundaryX, canvas.height);
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Vacuum / Air (σ = 0)", 80, 30);
    ctx.fillText("Conducting Medium (Conductivity σ)", boundaryX + 30, 30);

    // Baseline
    ctx.strokeStyle = "#334155";
    ctx.beginPath();
    ctx.moveTo(20, midY);
    ctx.lineTo(canvas.width - 20, midY);
    ctx.stroke();

    const amp = 85;
    const k1 = 0.05;
    const kappa = 0.012 * Math.sqrt(this.sigma);
    const skinDepthPx = 1 / kappa;

    // Plot Left Region: Undamped Incident Wave
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    for (let x = 30; x <= boundaryX; x++) {
      const y = midY - amp * Math.sin(k1 * (x - boundaryX) - this.t);
      if (x === 30) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }

    // Plot Right Region: Exponentially Damped Wave
    for (let x = boundaryX; x <= canvas.width - 30; x++) {
      const dist = x - boundaryX;
      const decay = Math.exp(-kappa * dist);
      const y = midY - amp * decay * Math.sin(k1 * 1.8 * dist - this.t);
      ctx.lineTo(x, y);
    }
    ctx.stroke();

    // Draw Exponential Decay Envelope
    ctx.strokeStyle = "rgba(244, 63, 94, 0.6)";
    ctx.setLineDash([5, 4]);
    ctx.beginPath();
    for (let x = boundaryX; x <= canvas.width - 30; x++) {
      const dist = x - boundaryX;
      const decay = Math.exp(-kappa * dist);
      const y = midY - amp * decay;
      if (x === boundaryX) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();
    ctx.setLineDash([]);

    // Skin Depth Marker
    const markerX = boundaryX + skinDepthPx;
    if (markerX < canvas.width - 30) {
      ctx.strokeStyle = "#10b981";
      ctx.lineWidth = 1.5;
      ctx.setLineDash([4, 4]);
      ctx.beginPath();
      ctx.moveTo(markerX, 40);
      ctx.lineTo(markerX, canvas.height - 30);
      ctx.stroke();
      ctx.setLineDash([]);

      ctx.fillStyle = "#10b981";
      ctx.fillText("Skin Depth δ (1/e ≈ 37%)", markerX + 6, 75);
    }
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 5. Fresnel Reflection & Brewster Angle
// ==========================================
class FresnelSim {
  constructor(container) {
    this.container = container;
    this.thetaI = 45; // degrees
    this.n1 = 1.0;
    this.n2 = 1.5;
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.draw();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 3.1</span>
            <strong>Fresnel Reflectance & Brewster Polarization Angle $\\tan\\theta_B = \\frac{n_2}{n_1}$</strong>
          </div>
          <div class="slider-control-group">
            <label>Angle of Incidence $\\theta_i$: <strong id="fr-ang-val">45°</strong></label>
            <input type="range" id="fr-ang-slider" min="0" max="89" value="45" class="range-slider">
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="fr-canvas" width="760" height="320"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <div class="metric-label">p-Polarization Reflectance $R_p$</div>
            <div class="metric-value text-sky" id="fr-rp-val">0.9%</div>
          </div>
          <div class="metric-card">
            <div class="metric-label">s-Polarization Reflectance $R_s$</div>
            <div class="metric-value text-amber" id="fr-rs-val">9.2%</div>
          </div>
          <div class="metric-card highlight">
            <div class="metric-label">Brewster Angle $\\theta_B$</div>
            <div class="metric-value text-emerald">56.3° (where $R_p = 0$)</div>
          </div>
        </div>
      </div>
    `;

    document.getElementById("fr-ang-slider").oninput = (e) => {
      this.thetaI = parseFloat(e.target.value);
      document.getElementById("fr-ang-val").innerText = this.thetaI + "°";
      this.draw();
    };
  }

  initCanvas() {
    this.canvas = document.getElementById("fr-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const radI = (this.thetaI * Math.PI) / 180;
    const sinT = (this.n1 / this.n2) * Math.sin(radI);
    const radT = Math.asin(Math.min(0.999, sinT));

    // Fresnel Equations
    const cosI = Math.cos(radI);
    const cosT = Math.cos(radT);
    const rp = (this.n2 * cosI - this.n1 * cosT) / (this.n2 * cosI + this.n1 * cosT);
    const rs = (this.n1 * cosI - this.n2 * cosT) / (this.n1 * cosI + this.n2 * cosT);
    const Rp = Math.pow(rp, 2);
    const Rs = Math.pow(rs, 2);

    document.getElementById("fr-rp-val").innerText = (Rp * 100).toFixed(1) + "%";
    document.getElementById("fr-rs-val").innerText = (Rs * 100).toFixed(1) + "%";

    const midX = 220;
    const midY = 160;

    // Interface Line (Vertical)
    ctx.strokeStyle = "#cbd5e1";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(midX, 20);
    ctx.lineTo(midX, canvas.height - 20);
    ctx.stroke();

    ctx.fillStyle = "rgba(56, 189, 248, 0.1)";
    ctx.fillRect(midX, 20, canvas.width - midX - 30, canvas.height - 40);

    ctx.fillStyle = "#94a3b8";
    ctx.font = "11px Inter, sans-serif";
    ctx.fillText("Air (n₁ = 1.0)", midX - 100, 40);
    ctx.fillText("Glass (n₂ = 1.5)", midX + 30, 40);

    // Normal Line (Dashed)
    ctx.strokeStyle = "#475569";
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(60, midY);
    ctx.lineTo(380, midY);
    ctx.stroke();
    ctx.setLineDash([]);

    // Ray tracing
    const rayLen = 140;

    // Incident Ray
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(midX - rayLen * Math.cos(radI), midY - rayLen * Math.sin(radI));
    ctx.lineTo(midX, midY);
    ctx.stroke();

    // Reflected Ray
    ctx.strokeStyle = `rgba(245, 158, 11, ${Math.max(0.2, (Rp + Rs)/2)})`;
    ctx.beginPath();
    ctx.moveTo(midX, midY);
    ctx.lineTo(midX - rayLen * Math.cos(radI), midY + rayLen * Math.sin(radI));
    ctx.stroke();

    // Refracted Ray
    ctx.strokeStyle = "#10b981";
    ctx.beginPath();
    ctx.moveTo(midX, midY);
    ctx.lineTo(midX + rayLen * Math.cos(radT), midY + rayLen * Math.sin(radT));
    ctx.stroke();

    // Graph Rp vs Angle on the right side
    const graphLeft = 440;
    const graphBaseY = 250;
    const graphW = 280;
    const graphH = 180;

    ctx.strokeStyle = "#334155";
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(graphLeft, graphBaseY);
    ctx.lineTo(graphLeft + graphW, graphBaseY);
    ctx.moveTo(graphLeft, graphBaseY);
    ctx.lineTo(graphLeft, graphBaseY - graphH);
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.fillText("Reflectance R vs Incident Angle θ", graphLeft + 20, graphBaseY - graphH - 10);
    ctx.fillText("0°", graphLeft - 10, graphBaseY + 15);
    ctx.fillText("90°", graphLeft + graphW - 15, graphBaseY + 15);

    // Plot Rs (Yellow curve)
    ctx.strokeStyle = "#fbbf24";
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let deg = 0; deg <= 89; deg++) {
      const th = (deg * Math.PI) / 180;
      const sT = (1.0 / 1.5) * Math.sin(th);
      const cT = Math.cos(Math.asin(sT));
      const r_s = (1.0 * Math.cos(th) - 1.5 * cT) / (1.0 * Math.cos(th) + 1.5 * cT);
      const val = Math.pow(r_s, 2);
      const gx = graphLeft + (deg / 90) * graphW;
      const gy = graphBaseY - val * graphH;
      if (deg === 0) ctx.moveTo(gx, gy);
      else ctx.lineTo(gx, gy);
    }
    ctx.stroke();

    // Plot Rp (Cyan curve, drops to zero at Brewster)
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let deg = 0; deg <= 89; deg++) {
      const th = (deg * Math.PI) / 180;
      const sT = (1.0 / 1.5) * Math.sin(th);
      const cT = Math.cos(Math.asin(sT));
      const r_p = (1.5 * Math.cos(th) - 1.0 * cT) / (1.5 * Math.cos(th) + 1.0 * cT);
      const val = Math.pow(r_p, 2);
      const gx = graphLeft + (deg / 90) * graphW;
      const gy = graphBaseY - val * graphH;
      if (deg === 0) ctx.moveTo(gx, gy);
      else ctx.lineTo(gx, gy);
    }
    ctx.stroke();

    // Current angle marker on graph
    const currX = graphLeft + (this.thetaI / 90) * graphW;
    ctx.strokeStyle = "#ef4444";
    ctx.setLineDash([3, 3]);
    ctx.beginPath();
    ctx.moveTo(currX, graphBaseY);
    ctx.lineTo(currX, graphBaseY - graphH);
    ctx.stroke();
    ctx.setLineDash([]);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 6. Waveguide Modes
// ==========================================
class WaveguideSim {
  constructor(container) {
    this.container = container;
    this.mode = "TE10"; // TE10, TE20, TM11
    this.t = 0;
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.startLoop();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 3.2</span>
            <strong>Rectangular Waveguide Field Configurations (Cross-Section & Longitudinal View)</strong>
          </div>
          <div class="sim-controls">
            <button class="btn-mode ${this.mode==='TE10'?'active':''}" data-m="TE10">TE₁₀ (Dominant)</button>
            <button class="btn-mode ${this.mode==='TE20'?'active':''}" data-m="TE20">TE₂₀</button>
            <button class="btn-mode ${this.mode==='TM11'?'active':''}" data-m="TM11">TM₁₁</button>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="wg-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-footer">
          <div class="sim-hint">
            💡 Cyan arrows represent electric field lines $\\mathbf{E}$ terminating on conducting walls. Notice that for $\\text{TE}_{10}$, the electric field is purely vertical and vanishes at the conducting walls ($x=0, a$).
          </div>
        </div>
      </div>
    `;

    this.container.querySelectorAll(".btn-mode").forEach(btn => {
      btn.onclick = () => {
        this.container.querySelectorAll(".btn-mode").forEach(b => b.classList.remove("active"));
        btn.classList.add("active");
        this.mode = btn.getAttribute("data-m");
      };
    });
  }

  initCanvas() {
    this.canvas = document.getElementById("wg-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  startLoop() {
    const loop = () => {
      this.t += 0.05;
      this.draw();
      this.animId = requestAnimationFrame(loop);
    };
    this.animId = requestAnimationFrame(loop);
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const wgX = 160;
    const wgY = 50;
    const wgW = 440;
    const wgH = 200;

    // Draw Conducting Walls
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(wgX - 12, wgY - 12, wgW + 24, wgH + 24);
    ctx.fillStyle = "#020617";
    ctx.fillRect(wgX, wgY, wgW, wgH);

    ctx.strokeStyle = "#94a3b8";
    ctx.lineWidth = 2;
    ctx.strokeRect(wgX, wgY, wgW, wgH);

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Width a", wgX + wgW/2 - 20, wgY - 18);
    ctx.fillText("Height b", wgX - 65, wgY + wgH/2);

    // Field Patterns
    const phase = Math.sin(this.t);

    if (this.mode === "TE10") {
      // E_y proportional to sin(pi*x/a)
      ctx.strokeStyle = "#38bdf8";
      ctx.lineWidth = 2;
      for (let x = wgX + 30; x <= wgX + wgW - 30; x += 30) {
        const xNorm = (x - wgX) / wgW;
        const eAmp = Math.sin(Math.PI * xNorm) * phase;

        if (Math.abs(eAmp) > 0.05) {
          const arrowLen = eAmp * (wgH * 0.7);
          const startY = wgY + wgH/2 - arrowLen/2;
          const endY = wgY + wgH/2 + arrowLen/2;

          ctx.beginPath();
          ctx.moveTo(x, startY);
          ctx.lineTo(x, endY);
          ctx.stroke();

          // Arrowhead
          const dir = Math.sign(eAmp);
          ctx.beginPath();
          ctx.moveTo(x - 4, endY - dir * 8);
          ctx.lineTo(x, endY);
          ctx.lineTo(x + 4, endY - dir * 8);
          ctx.stroke();
        }
      }
    } else if (this.mode === "TE20") {
      // E_y proportional to sin(2*pi*x/a)
      ctx.strokeStyle = "#38bdf8";
      ctx.lineWidth = 2;
      for (let x = wgX + 20; x <= wgX + wgW - 20; x += 25) {
        const xNorm = (x - wgX) / wgW;
        const eAmp = Math.sin(2 * Math.PI * xNorm) * phase;

        if (Math.abs(eAmp) > 0.05) {
          const arrowLen = eAmp * (wgH * 0.7);
          const startY = wgY + wgH/2 - arrowLen/2;
          const endY = wgY + wgH/2 + arrowLen/2;

          ctx.beginPath();
          ctx.moveTo(x, startY);
          ctx.lineTo(x, endY);
          ctx.stroke();
        }
      }
    } else {
      // TM11
      ctx.fillStyle = "rgba(56, 189, 248, 0.4)";
      ctx.fillText("TM₁₁ mode field vortices", wgX + wgW/2 - 70, wgY + wgH/2);
    }
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 7. Oscillating Dipole Radiation
// ==========================================
class DipoleRadiationSim {
  constructor(container) {
    this.container = container;
    this.t = 0;
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.startLoop();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 4.1</span>
            <strong>Oscillating Hertzian Dipole Radiation Wavefront Detachment</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="dip-canvas" width="760" height="340"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-footer">
          <div class="sim-hint">
            💡 The characteristic toroidal doughnut radiation pattern: zero radiation is emitted along the vertical dipole axis ($\theta = 0^\circ, 180^\circ$), with maximum radiated power emitted broadside at $\theta = 90^\circ$ scaling as $P \propto \omega^4$.
          </div>
        </div>
      </div>
    `;
  }

  initCanvas() {
    this.canvas = document.getElementById("dip-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  startLoop() {
    const loop = () => {
      this.t += 0.05;
      this.draw();
      this.animId = requestAnimationFrame(loop);
    };
    this.animId = requestAnimationFrame(loop);
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#080c16";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const cx = canvas.width / 2;
    const cy = canvas.height / 2;

    // Draw Expanding Dipole Wavefronts
    const numRings = 7;
    for (let r = 0; r < numRings; r++) {
      const radius = ((this.t * 30 + r * 45) % (canvas.width * 0.48));
      const opacity = Math.max(0, 1 - radius / (canvas.width * 0.48));

      ctx.strokeStyle = `rgba(56, 189, 248, ${opacity * 0.7})`;
      ctx.lineWidth = 2;

      // Modulate ring radius by sin^2(theta) to form dipole lobes
      ctx.beginPath();
      for (let angle = 0; angle <= Math.PI * 2; angle += 0.05) {
        const sinTh = Math.sin(angle);
        const lobeR = radius * (0.2 + 0.8 * Math.pow(Math.abs(sinTh), 1.5));
        const x = cx + lobeR * Math.cos(angle);
        const y = cy + lobeR * Math.sin(angle);
        if (angle === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.closePath();
      ctx.stroke();
    }

    // Dipole center oscillating charges
    const oscOffset = Math.sin(this.t * 4) * 16;
    ctx.fillStyle = "#38bdf8";
    ctx.beginPath();
    ctx.arc(cx, cy - oscOffset, 5, 0, Math.PI * 2);
    ctx.fill();

    ctx.fillStyle = "#f43f5e";
    ctx.beginPath();
    ctx.arc(cx, cy + oscOffset, 5, 0, Math.PI * 2);
    ctx.fill();

    // Dipole antenna rod
    ctx.strokeStyle = "#cbd5e1";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(cx, cy - 25);
    ctx.lineTo(cx, cy + 25);
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Dipole Axis", cx + 15, cy - 20);
    ctx.fillText("Zero Radiation along Axis ↑", cx - 80, cy - 130);
    ctx.fillText("Max Radiation Broadside →", cx + 120, cy + 5);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 8. Scattering Simulator (Rayleigh vs Thomson)
// ==========================================
class ScatteringSim {
  constructor(container) {
    this.container = container;
    this.freqRatio = 0.5; // omega / omega0
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.draw();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 5.1</span>
            <strong>Scattering Cross Section: Rayleigh ($\\omega^4$) vs. Resonance vs. Thomson Limit</strong>
          </div>
          <div class="slider-control-group">
            <label>Frequency Ratio $\\omega / \\omega_0$: <strong id="scat-f-val">0.5 (Rayleigh Regime)</strong></label>
            <input type="range" id="scat-f-slider" min="10" max="250" value="50" class="range-slider">
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="scat-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
      </div>
    `;

    document.getElementById("scat-f-slider").oninput = (e) => {
      this.freqRatio = parseFloat(e.target.value) / 100;
      let regime = "Rayleigh Regime (ω ≪ ω₀)";
      if (this.freqRatio > 0.85 && this.freqRatio < 1.15) regime = "Resonance Scattering (ω ≈ ω₀)";
      else if (this.freqRatio >= 1.15) regime = "Thomson Regime (ω ≫ ω₀)";

      document.getElementById("scat-f-val").innerText = `${this.freqRatio.toFixed(2)} (${regime})`;
      this.draw();
    };
  }

  initCanvas() {
    this.canvas = document.getElementById("scat-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const baseLeft = 80;
    const baseW = 600;
    const baseY = 240;
    const maxH = 180;

    // Draw Axes
    ctx.strokeStyle = "#475569";
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(baseLeft, baseY);
    ctx.lineTo(baseLeft + baseW, baseY);
    ctx.moveTo(baseLeft, baseY);
    ctx.lineTo(baseLeft, baseY - maxH - 20);
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Total Cross Section σ(ω)", baseLeft - 10, baseY - maxH - 30);
    ctx.fillText("Frequency Ratio ω / ω₀", baseLeft + baseW - 140, baseY + 30);

    // Plot Cross Section Curve: sigma_T * (w/w0)^4 / ((1 - (w/w0)^2)^2 + gamma^2)
    const gamma = 0.15;
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2.5;
    ctx.beginPath();

    for (let px = 0; px <= baseW; px++) {
      const wRel = (px / baseW) * 2.8;
      const num = Math.pow(wRel, 4);
      const denom = Math.pow(1 - wRel * wRel, 2) + Math.pow(gamma * wRel, 2);
      const sigmaRel = num / denom;
      const plotY = baseY - Math.min(maxH, sigmaRel * 12);

      const x = baseLeft + px;
      if (px === 0) ctx.moveTo(x, plotY);
      else ctx.lineTo(x, plotY);
    }
    ctx.stroke();

    // Mark Current Selected Frequency
    const currX = baseLeft + (this.freqRatio / 2.8) * baseW;
    ctx.strokeStyle = "#ef4444";
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(currX, baseY);
    ctx.lineTo(currX, baseY - maxH - 10);
    ctx.stroke();
    ctx.setLineDash([]);

    ctx.fillStyle = "#ef4444";
    ctx.fillText(`Current: ω/ω₀ = ${this.freqRatio.toFixed(2)}`, currX - 45, 50);

    // Label Thomson asymptotic limit
    ctx.strokeStyle = "#fbbf24";
    ctx.setLineDash([6, 4]);
    ctx.beginPath();
    ctx.moveTo(baseLeft + 200, baseY - 12);
    ctx.lineTo(baseLeft + baseW, baseY - 12);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.fillStyle = "#fbbf24";
    ctx.fillText("Thomson Free-Electron Limit σ_T", baseLeft + baseW - 200, baseY - 20);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 9. Drude-Lorentz Dispersion Curves
// ==========================================
class DrudeLorentzSim {
  constructor(container) {
    this.container = container;
    this.damping = 0.2;
    this.animId = null;

    this.renderDOM();
    this.initCanvas();
    this.draw();
  }

  renderDOM() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div class="sim-title">
            <span class="sim-badge">Simulation 6.1</span>
            <strong>Drude-Lorentz Dispersion: Refractive Index $n(\\omega)$ & Absorption $\\kappa(\\omega)$</strong>
          </div>
          <div class="slider-control-group">
            <label>Damping Rate $\\gamma$: <strong id="dl-damp-val">0.20</strong></label>
            <input type="range" id="dl-damp-slider" min="5" max="60" value="20" class="range-slider">
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="dl-canvas" width="760" height="320"></canvas>
          <div class="sim-watermark">OpenSTEM • Electrodynamics • Protected</div>
        </div>
        <div class="sim-footer">
          <div class="sim-hint">
            💡 Cyan curve: Refractive index $n(\\omega)$. Red shaded: Absorption band $\\kappa(\\omega)$. Notice <strong>Anomalous Dispersion</strong> ($dn/d\\omega < 0$) occurs directly within the resonance absorption peak!
          </div>
        </div>
      </div>
    `;

    document.getElementById("dl-damp-slider").oninput = (e) => {
      this.damping = parseFloat(e.target.value) / 100;
      document.getElementById("dl-damp-val").innerText = this.damping.toFixed(2);
      this.draw();
    };
  }

  initCanvas() {
    this.canvas = document.getElementById("dl-canvas");
    this.ctx = this.canvas.getContext("2d");
  }

  draw() {
    const { ctx, canvas } = this;
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    const baseLeft = 80;
    const baseW = 600;
    const midY = 160;

    // Coordinate Axes
    ctx.strokeStyle = "#475569";
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.moveTo(baseLeft, midY);
    ctx.lineTo(baseLeft + baseW, midY);
    ctx.moveTo(baseLeft, 40);
    ctx.lineTo(baseLeft, canvas.height - 40);
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Index n = 1.0 (Baseline)", baseLeft - 75, midY + 4);
    ctx.fillText("Frequency ω (Resonance at ω₀ = 1.0)", baseLeft + baseW - 220, canvas.height - 20);

    // Plot Curves
    const gamma = this.damping;

    // 1. Draw Absorption Band (Red shaded)
    ctx.fillStyle = "rgba(239, 68, 68, 0.25)";
    ctx.strokeStyle = "#ef4444";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(baseLeft, midY);

    for (let px = 0; px <= baseW; px++) {
      const w = 0.2 + (px / baseW) * 1.6;
      const denom = Math.pow(1 - w * w, 2) + Math.pow(gamma * w, 2);
      const kappa = (0.5 * gamma * w) / denom;
      const y = midY - kappa * 180;
      ctx.lineTo(baseLeft + px, y);
    }
    ctx.lineTo(baseLeft + baseW, midY);
    ctx.closePath();
    ctx.fill();

    // 2. Draw Refractive Index n(w) (Cyan curve)
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2.5;
    ctx.beginPath();

    for (let px = 0; px <= baseW; px++) {
      const w = 0.2 + (px / baseW) * 1.6;
      const denom = Math.pow(1 - w * w, 2) + Math.pow(gamma * w, 2);
      const nDelta = (0.5 * (1 - w * w)) / denom;
      const y = midY - nDelta * 180;

      const x = baseLeft + px;
      if (px === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();

    ctx.fillStyle = "#38bdf8";
    ctx.fillText("Refractive Index n(ω)", baseLeft + 40, 55);
    ctx.fillStyle = "#ef4444";
    ctx.fillText("Absorption Coefficient κ(ω)", baseLeft + 40, 75);
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}


// ==========================================
// 10. Radiation Pressure & Solar Sail Simulator
// ==========================================
class RadiationPressureSim {
  constructor(container) {
    this.container = container;
    this.R = 0.95; // Reflectance
    this.intensity = 1361; // W/m^2 (1 AU solar constant)
    this.theta = 0; // Incidence angle in deg
    this.animId = null;
    this.time = 0;
    this.photons = [];
    this.initUI();
    this.animate();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §1.6 Experiment</span>
            <strong class="sim-title">Solar Radiation Pressure & Photon Momentum Thrust</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="rad-canvas" width="760" height="280"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Radiation Pressure (Prad)</span>
            <span class="metric-val" id="rad-p-val">8.85 µPa</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Force on 100m² Sail</span>
            <span class="metric-val" id="rad-f-val">0.88 mN</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Photon Momentum Reversal</span>
            <span class="metric-val" id="rad-dp-val">Δp = 1.95 p</span>
          </div>
        </div>
        <div class="sim-controls-grid" style="display:grid; grid-template-columns: 1fr 1fr 1fr; gap:1rem; margin-top:1rem;">
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Surface Reflectance (R): <strong id="rad-r-lbl" style="color:#38bdf8;">0.95</strong></label>
            <input type="range" class="range-slider" id="rad-r-slider" min="0" max="1" step="0.05" value="0.95">
          </div>
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Solar Flux (I): <strong id="rad-i-lbl" style="color:#38bdf8;">1361 W/m²</strong></label>
            <input type="range" class="range-slider" id="rad-i-slider" min="500" max="3000" step="50" value="1361">
          </div>
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Incidence Angle (θ): <strong id="rad-th-lbl" style="color:#38bdf8;">0°</strong></label>
            <input type="range" class="range-slider" id="rad-th-slider" min="0" max="75" step="5" value="0">
          </div>
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#rad-canvas");
    this.ctx = this.canvas.getContext("2d");

    this.container.querySelector("#rad-r-slider").addEventListener("input", (e) => {
      this.R = parseFloat(e.target.value);
      this.container.querySelector("#rad-r-lbl").innerText = this.R.toFixed(2);
      this.updateMetrics();
    });

    this.container.querySelector("#rad-i-slider").addEventListener("input", (e) => {
      this.intensity = parseFloat(e.target.value);
      this.container.querySelector("#rad-i-lbl").innerText = this.intensity + " W/m²";
      this.updateMetrics();
    });

    this.container.querySelector("#rad-th-slider").addEventListener("input", (e) => {
      this.theta = parseFloat(e.target.value);
      this.container.querySelector("#rad-th-lbl").innerText = this.theta + "°";
      this.updateMetrics();
    });

    // Populate initial photons
    for (let i = 0; i < 40; i++) {
      this.photons.push({
        x: Math.random() * 200,
        y: Math.random() * 240 + 20,
        vx: 4 + Math.random() * 2,
        vy: 0,
        state: "incoming"
      });
    }

    this.updateMetrics();
  }

  updateMetrics() {
    const c = 3.00e8;
    const rad = this.theta * Math.PI / 180;
    const p = (this.intensity / c) * (1 + this.R) * Math.cos(rad) * Math.cos(rad);
    const force100 = p * 100;

    const pMicro = (p * 1e6).toFixed(2);
    const fMilli = (force100 * 1e3).toFixed(2);

    const pEl = this.container.querySelector("#rad-p-val");
    const fEl = this.container.querySelector("#rad-f-val");
    const dpEl = this.container.querySelector("#rad-dp-val");

    if (pEl) pEl.innerText = `${pMicro} µPa`;
    if (fEl) fEl.innerText = `${fMilli} mN`;
    if (dpEl) dpEl.innerText = `Δp = ${(1 + this.R).toFixed(2)} p`;
  }

  animate() {
    this.time++;
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;

    ctx.fillStyle = "#080c14";
    ctx.fillRect(0, 0, w, h);

    // Draw solar sail plate
    const sailX = 420;
    const sailH = 200;
    const sailY = h / 2;
    const rad = this.theta * Math.PI / 180;

    ctx.save();
    ctx.translate(sailX, sailY);
    ctx.rotate(rad);

    ctx.fillStyle = this.R > 0.5 ? "#38bdf8" : "#94a3b8";
    ctx.shadowColor = "#38bdf8";
    ctx.shadowBlur = 12 * this.R;
    ctx.fillRect(-6, -sailH / 2, 12, sailH);
    ctx.shadowBlur = 0;

    ctx.fillStyle = "#ffffff";
    ctx.font = "11px Inter, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("Solar Sail", 0, sailH / 2 + 18);
    ctx.restore();

    // Draw Thrust Force Arrow
    const forceLen = 60 * (1 + this.R) * Math.cos(rad);
    const fAngle = rad;
    ctx.strokeStyle = "#10b981";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(sailX, sailY);
    ctx.lineTo(sailX + forceLen * Math.cos(fAngle), sailY + forceLen * Math.sin(fAngle));
    ctx.stroke();

    ctx.fillStyle = "#10b981";
    ctx.font = "bold 12px Inter, sans-serif";
    ctx.fillText("Radiation Thrust Vector F_rad", sailX + forceLen * Math.cos(fAngle) + 10, sailY + forceLen * Math.sin(fAngle) + 4);

    // Update & draw photons
    this.photons.forEach(p => {
      p.x += p.vx;
      p.y += p.vy;

      if (p.state === "incoming" && p.x >= sailX - 10 && Math.abs(p.y - sailY) < sailH / 2 + 20) {
        if (Math.random() < this.R) {
          p.state = "reflected";
          p.vx = -p.vx * Math.cos(2 * rad);
          p.vy = -p.vx * Math.sin(2 * rad) + (Math.random() - 0.5) * 2;
        } else {
          p.state = "absorbed";
          p.x = sailX + 2;
          p.vx = 0;
          p.vy = 0;
        }
      }

      if (p.x > w || p.x < 0 || p.y < 0 || p.y > h || p.state === "absorbed") {
        p.x = Math.random() * 50;
        p.y = Math.random() * (sailH + 40) + (sailY - sailH / 2 - 20);
        p.vx = 4 + Math.random() * 2;
        p.vy = 0;
        p.state = "incoming";
      }

      ctx.fillStyle = p.state === "reflected" ? "#38bdf8" : "#fbbf24";
      ctx.beginPath();
      ctx.arc(p.x, p.y, p.state === "reflected" ? 2.5 : 2, 0, Math.PI * 2);
      ctx.fill();
    });

    this.animId = requestAnimationFrame(() => this.animate());
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 11. Ionospheric Plasma Cutoff Simulator
// ==========================================
class PlasmaCutoffSim {
  constructor(container) {
    this.container = container;
    this.freqMHz = 12.0; // Wave frequency in MHz
    this.neDensity = 1.0; // x10^12 e/m^3 (gives ~9 MHz fp)
    this.animId = null;
    this.phase = 0;
    this.initUI();
    this.animate();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §2.7 Experiment</span>
            <strong class="sim-title">Ionospheric Plasma Frequency & Wave Cutoff</strong>
          </div>
          <span id="plasma-status-pill" style="padding: 0.25rem 0.65rem; border-radius: 999px; font-size: 0.75rem; font-weight:700; background-color: rgba(16,185,129,0.2); color:#10b981;">PROPAGATING WAVE (f > fp)</span>
        </div>
        <div class="canvas-container">
          <canvas id="plasma-canvas" width="760" height="280"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Plasma Critical Frequency (fp)</span>
            <span class="metric-val" id="plasma-fp-val">8.98 MHz</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Wave Frequency (f)</span>
            <span class="metric-val" id="plasma-f-val">12.0 MHz</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Plasma Dielectric Permittivity</span>
            <span class="metric-val" id="plasma-eps-val">ε_r = +0.44</span>
          </div>
        </div>
        <div class="sim-controls-grid" style="display:grid; grid-template-columns: 1fr 1fr; gap:1.5rem; margin-top:1rem;">
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Wave Frequency (f): <strong id="plasma-f-lbl" style="color:#38bdf8;">12.0 MHz</strong></label>
            <input type="range" class="range-slider" id="plasma-f-slider" min="2" max="25" step="0.5" value="12">
          </div>
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Plasma Density (ne): <strong id="plasma-ne-lbl" style="color:#38bdf8;">1.0 × 10¹² m⁻³</strong></label>
            <input type="range" class="range-slider" id="plasma-ne-slider" min="0.2" max="3.0" step="0.1" value="1.0">
          </div>
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#plasma-canvas");
    this.ctx = this.canvas.getContext("2d");

    this.container.querySelector("#plasma-f-slider").addEventListener("input", (e) => {
      this.freqMHz = parseFloat(e.target.value);
      this.container.querySelector("#plasma-f-lbl").innerText = this.freqMHz.toFixed(1) + " MHz";
      this.updateMetrics();
    });

    this.container.querySelector("#plasma-ne-slider").addEventListener("input", (e) => {
      this.neDensity = parseFloat(e.target.value);
      this.container.querySelector("#plasma-ne-lbl").innerText = this.neDensity.toFixed(1) + " × 10¹² m⁻³";
      this.updateMetrics();
    });

    this.updateMetrics();
  }

  updateMetrics() {
    const fp = 8.98 * Math.sqrt(this.neDensity);
    const epsR = 1 - (fp * fp) / (this.freqMHz * this.freqMHz);

    const fpEl = this.container.querySelector("#plasma-fp-val");
    const fEl = this.container.querySelector("#plasma-f-val");
    const epsEl = this.container.querySelector("#plasma-eps-val");
    const pill = this.container.querySelector("#plasma-status-pill");

    if (fpEl) fpEl.innerText = `${fp.toFixed(2)} MHz`;
    if (fEl) fEl.innerText = `${this.freqMHz.toFixed(1)} MHz`;
    if (epsEl) epsEl.innerText = `ε_r = ${epsR >= 0 ? '+' : ''}${epsR.toFixed(2)}`;

    if (pill) {
      if (this.freqMHz > fp) {
        pill.innerText = "PROPAGATING WAVE (f > fp)";
        pill.style.backgroundColor = "rgba(16,185,129,0.2)";
        pill.style.color = "#10b981";
      } else {
        pill.innerText = "TOTAL REFLECTION / CUTOFF (f < fp)";
        pill.style.backgroundColor = "rgba(244,63,94,0.2)";
        pill.style.color = "#f43f5e";
      }
    }
  }

  animate() {
    this.phase += 0.08;
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;
    const midY = h / 2;

    ctx.fillStyle = "#090d18";
    ctx.fillRect(0, 0, w, h);

    const plasmaX = 350;

    // Draw Plasma Region Background
    ctx.fillStyle = "rgba(56, 189, 248, 0.08)";
    ctx.fillRect(plasmaX, 0, w - plasmaX, h);

    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 1;
    ctx.setLineDash([6, 6]);
    ctx.beginPath();
    ctx.moveTo(plasmaX, 0);
    ctx.lineTo(plasmaX, h);
    ctx.stroke();
    ctx.setLineDash([]);

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("Neutral Atmosphere", 80, 24);
    ctx.fillStyle = "#38bdf8";
    ctx.fillText("Ionospheric Plasma Layer", plasmaX + 60, 24);

    const fp = 8.98 * Math.sqrt(this.neDensity);
    const isPropagating = this.freqMHz > fp;

    // Draw EM wave
    ctx.lineWidth = 2.5;

    if (isPropagating) {
      // Propagates in both regions
      const k1 = 0.04;
      const k2 = 0.04 * Math.sqrt(Math.max(0.01, 1 - (fp*fp)/(this.freqMHz*this.freqMHz)));

      ctx.strokeStyle = "#38bdf8";
      ctx.beginPath();
      for (let x = 0; x < w; x++) {
        let y;
        if (x < plasmaX) {
          y = midY + 60 * Math.sin(k1 * x - this.phase);
        } else {
          const transPhase = k1 * plasmaX - this.phase;
          y = midY + 60 * Math.sin(k2 * (x - plasmaX) + transPhase);
        }
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();
    } else {
      // Total reflection: standing wave in region 1, evanescent in region 2
      const kappa = 0.04 * Math.sqrt(Math.abs((fp*fp)/(this.freqMHz*this.freqMHz) - 1));
      ctx.strokeStyle = "#f43f5e";
      ctx.beginPath();
      for (let x = 0; x < w; x++) {
        let y;
        if (x < plasmaX) {
          // Standing wave
          y = midY + 70 * Math.cos(0.04 * (x - plasmaX)) * Math.sin(this.phase);
        } else {
          // Exponential decay
          const decay = Math.exp(-kappa * (x - plasmaX));
          y = midY + 70 * decay * Math.sin(this.phase);
        }
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();

      // Draw evanescent envelope curve
      ctx.strokeStyle = "rgba(244, 63, 94, 0.4)";
      ctx.setLineDash([4, 4]);
      ctx.beginPath();
      for (let x = plasmaX; x < w; x++) {
        const decay = Math.exp(-kappa * (x - plasmaX));
        const yTop = midY - 70 * decay;
        if (x === plasmaX) ctx.moveTo(x, yTop);
        else ctx.lineTo(x, yTop);
      }
      ctx.stroke();
      ctx.setLineDash([]);
    }

    this.animId = requestAnimationFrame(() => this.animate());
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 12. Snell Refraction & Critical Angle Ray Tracer
// ==========================================
class SnellRefractionSim {
  constructor(container) {
    this.container = container;
    this.n1 = 1.50; // Glass
    this.n2 = 1.00; // Air
    this.theta1Deg = 35; // Incident angle
    this.animId = null;
    this.initUI();
    this.render();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §3.3 Experiment</span>
            <strong class="sim-title">Snell's Law, Critical Angle & Total Internal Reflection Ray Tracer</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="snell-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Refraction Angle (θ2)</span>
            <span class="metric-val" id="snell-th2-val">59.4°</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Critical Angle (θc)</span>
            <span class="metric-val" id="snell-thc-val">41.8°</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Brewster Angle (θB)</span>
            <span class="metric-val" id="snell-thb-val">33.7°</span>
          </div>
        </div>
        <div class="sim-controls-grid" style="display:grid; grid-template-columns: 1fr 1fr 1fr; gap:1rem; margin-top:1rem;">
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Angle of Incidence (θ1): <strong id="snell-th1-lbl" style="color:#38bdf8;">35°</strong></label>
            <input type="range" class="range-slider" id="snell-th1-slider" min="0" max="85" step="1" value="35">
          </div>
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Medium 1 Index (n1): <strong id="snell-n1-lbl" style="color:#38bdf8;">1.50</strong></label>
            <input type="range" class="range-slider" id="snell-n1-slider" min="1.0" max="2.4" step="0.05" value="1.50">
          </div>
          <div>
            <label style="font-size:0.75rem; color:#94a3b8;">Medium 2 Index (n2): <strong id="snell-n2-lbl" style="color:#38bdf8;">1.00</strong></label>
            <input type="range" class="range-slider" id="snell-n2-slider" min="1.0" max="2.4" step="0.05" value="1.00">
          </div>
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#snell-canvas");
    this.ctx = this.canvas.getContext("2d");

    this.container.querySelector("#snell-th1-slider").addEventListener("input", (e) => {
      this.theta1Deg = parseFloat(e.target.value);
      this.container.querySelector("#snell-th1-lbl").innerText = this.theta1Deg + "°";
      this.render();
    });

    this.container.querySelector("#snell-n1-slider").addEventListener("input", (e) => {
      this.n1 = parseFloat(e.target.value);
      this.container.querySelector("#snell-n1-lbl").innerText = this.n1.toFixed(2);
      this.render();
    });

    this.container.querySelector("#snell-n2-slider").addEventListener("input", (e) => {
      this.n2 = parseFloat(e.target.value);
      this.container.querySelector("#snell-n2-lbl").innerText = this.n2.toFixed(2);
      this.render();
    });
  }

  render() {
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;
    const midX = w / 2;
    const midY = h / 2;

    ctx.fillStyle = "#080c16";
    ctx.fillRect(0, 0, w, h);

    // Draw Medium 1 & Medium 2 backgrounds
    ctx.fillStyle = "rgba(56, 189, 248, 0.12)";
    ctx.fillRect(0, 0, w, midY); // Upper Medium 1

    ctx.strokeStyle = "#334155";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(0, midY);
    ctx.lineTo(w, midY);
    ctx.stroke();

    // Normal line
    ctx.strokeStyle = "rgba(255, 255, 255, 0.3)";
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(midX, 20);
    ctx.lineTo(midX, h - 20);
    ctx.stroke();
    ctx.setLineDash([]);

    ctx.fillStyle = "#94a3b8";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText(`Medium 1 (n1 = ${this.n1.toFixed(2)})`, 30, 30);
    ctx.fillText(`Medium 2 (n2 = ${this.n2.toFixed(2)})`, 30, midY + 40);

    const th1Rad = this.theta1Deg * Math.PI / 180;
    const sinTh2 = (this.n1 / this.n2) * Math.sin(th1Rad);

    const rayLen = 170;

    // Incident Ray (top left towards center)
    const incX = midX - rayLen * Math.sin(th1Rad);
    const incY = midY - rayLen * Math.cos(th1Rad);

    ctx.strokeStyle = "#fbbf24";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(incX, incY);
    ctx.lineTo(midX, midY);
    ctx.stroke();

    // Reflected Ray
    const refX = midX + rayLen * Math.sin(th1Rad);
    const refY = midY - rayLen * Math.cos(th1Rad);

    ctx.strokeStyle = "rgba(251, 191, 36, 0.6)";
    ctx.beginPath();
    ctx.moveTo(midX, midY);
    ctx.lineTo(refX, refY);
    ctx.stroke();

    const th2El = this.container.querySelector("#snell-th2-val");
    const thcEl = this.container.querySelector("#snell-thc-val");
    const thbEl = this.container.querySelector("#snell-thb-val");

    let thc = this.n1 > this.n2 ? Math.asin(this.n2 / this.n1) * 180 / Math.PI : null;
    let thb = Math.atan(this.n2 / this.n1) * 180 / Math.PI;

    if (thcEl) thcEl.innerText = thc ? `${thc.toFixed(1)}°` : "None (n1 <= n2)";
    if (thbEl) thbEl.innerText = `${thb.toFixed(1)}°`;

    if (sinTh2 <= 1.0) {
      // Refraction occurs
      const th2Rad = Math.asin(sinTh2);
      const th2Deg = th2Rad * 180 / Math.PI;
      if (th2El) th2El.innerText = `${th2Deg.toFixed(1)}°`;

      const transX = midX + rayLen * Math.sin(th2Rad);
      const transY = midY + rayLen * Math.cos(th2Rad);

      ctx.strokeStyle = "#38bdf8";
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.moveTo(midX, midY);
      ctx.lineTo(transX, transY);
      ctx.stroke();
    } else {
      // Total Internal Reflection
      if (th2El) th2El.innerText = "Total Internal Reflection!";

      // Draw evanescent wave along boundary
      ctx.strokeStyle = "#f43f5e";
      ctx.lineWidth = 2;
      ctx.beginPath();
      for (let x = midX; x < midX + 160; x += 10) {
        ctx.moveTo(x, midY);
        ctx.lineTo(x, midY + 15 * Math.exp(-(x - midX) / 40));
      }
      ctx.stroke();

      ctx.fillStyle = "#f43f5e";
      ctx.fillText("Evanescent Wave", midX + 30, midY + 30);
    }
  }

  destroy() {}
}

// ==========================================
// 13. Retarded Potentials & Doppler Light-Cone Simulator
// ==========================================
class RetardedPotentialSim {
  constructor(container) {
    this.container = container;
    this.beta = 0.5; // v/c
    this.wavefronts = [];
    this.chargeX = 200;
    this.animId = null;
    this.initUI();
    this.animate();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §4.3 Experiment</span>
            <strong class="sim-title">Retarded Potentials & Relativistic Doppler Wavefront Compression</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="ret-canvas" width="760" height="280"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Velocity (v/c)</span>
            <span class="metric-val" id="ret-v-val">β = 0.50</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Forward Doppler Compression</span>
            <span class="metric-val" id="ret-comp-val">λ_f = 0.50 λ0</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Backward Doppler Stretching</span>
            <span class="metric-val" id="ret-stretch-val">λ_b = 1.50 λ0</span>
          </div>
        </div>
        <div class="slider-control-group mt-3">
          <label>Charge Velocity (β = v/c): <strong id="ret-b-lbl" style="color:#38bdf8;">0.50</strong></label>
          <input type="range" class="range-slider" id="ret-b-slider" min="0.0" max="0.85" step="0.05" value="0.50">
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#ret-canvas");
    this.ctx = this.canvas.getContext("2d");

    this.container.querySelector("#ret-b-slider").addEventListener("input", (e) => {
      this.beta = parseFloat(e.target.value);
      this.container.querySelector("#ret-b-lbl").innerText = this.beta.toFixed(2);
      this.updateMetrics();
    });

    this.updateMetrics();
  }

  updateMetrics() {
    const vEl = this.container.querySelector("#ret-v-val");
    const compEl = this.container.querySelector("#ret-comp-val");
    const stretchEl = this.container.querySelector("#ret-stretch-val");

    if (vEl) vEl.innerText = `β = ${this.beta.toFixed(2)}`;
    if (compEl) compEl.innerText = `λ_f = ${(1 - this.beta).toFixed(2)} λ₀`;
    if (stretchEl) stretchEl.innerText = `λ_b = ${(1 + this.beta).toFixed(2)} λ₀`;
  }

  animate() {
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;
    const cSpeed = 3.0;
    const vSpeed = this.beta * cSpeed;

    ctx.fillStyle = "#080c14";
    ctx.fillRect(0, 0, w, h);

    this.chargeX += vSpeed;
    if (this.chargeX > w - 100) {
      this.chargeX = 120;
      this.wavefronts = [];
    }

    // Emit wavefront periodically
    if (Math.floor(this.chargeX) % 35 < vSpeed) {
      this.wavefronts.push({
        x: this.chargeX,
        y: h / 2,
        r: 1
      });
    }

    // Draw wavefronts
    ctx.lineWidth = 1.5;
    for (let i = this.wavefronts.length - 1; i >= 0; i--) {
      const wf = this.wavefronts[i];
      wf.r += cSpeed;

      const alpha = Math.max(0, 1 - wf.r / 350);
      ctx.strokeStyle = `rgba(56, 189, 248, ${alpha})`;
      ctx.beginPath();
      ctx.arc(wf.x, wf.y, wf.r, 0, Math.PI * 2);
      ctx.stroke();

      if (wf.r > 380) this.wavefronts.splice(i, 1);
    }

    // Draw Charge
    ctx.fillStyle = "#fbbf24";
    ctx.shadowColor = "#fbbf24";
    ctx.shadowBlur = 12;
    ctx.beginPath();
    ctx.arc(this.chargeX, h / 2, 8, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;

    ctx.fillStyle = "#fff";
    ctx.font = "bold 10px Inter, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("q", this.chargeX, h / 2 + 3);

    this.animId = requestAnimationFrame(() => this.animate());
  }

  destroy() {
    if (this.animId) cancelAnimationFrame(this.animId);
  }
}

// ==========================================
// 14. Half-Wave Dipole Antenna 3D Radiation Pattern
// ==========================================
class AntennaRadiationSim {
  constructor(container) {
    this.container = container;
    this.lengthRatio = 0.5; // L/lambda = 0.5 (half wave)
    this.animId = null;
    this.rot = 0;
    this.initUI();
    this.render();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §4.8 Experiment</span>
            <strong class="sim-title">Center-Fed Dipole Antenna 3D Radiation Pattern & Directivity</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="ant-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Antenna Length (L)</span>
            <span class="metric-val" id="ant-len-val">0.50 λ (Half-Wave)</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Radiation Resistance (Rrad)</span>
            <span class="metric-val" id="ant-r-val">73.1 Ω</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Directivity Gain (D)</span>
            <span class="metric-val" id="ant-g-val">1.64 (2.15 dBi)</span>
          </div>
        </div>
        <div class="slider-control-group mt-3">
          <label>Dipole Length (L / λ): <strong id="ant-l-lbl" style="color:#38bdf8;">0.50</strong></label>
          <input type="range" class="range-slider" id="ant-l-slider" min="0.1" max="1.5" step="0.05" value="0.50">
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#ant-canvas");
    this.ctx = this.canvas.getContext("2d");

    this.container.querySelector("#ant-l-slider").addEventListener("input", (e) => {
      this.lengthRatio = parseFloat(e.target.value);
      this.container.querySelector("#ant-l-lbl").innerText = this.lengthRatio.toFixed(2);
      this.updateMetrics();
      this.render();
    });

    this.updateMetrics();
  }

  updateMetrics() {
    const lenEl = this.container.querySelector("#ant-len-val");
    const rEl = this.container.querySelector("#ant-r-val");
    const gEl = this.container.querySelector("#ant-g-val");

    if (this.lengthRatio === 0.5) {
      if (lenEl) lenEl.innerText = "0.50 λ (Half-Wave)";
      if (rEl) rEl.innerText = "73.1 Ω";
      if (gEl) gEl.innerText = "1.64 (2.15 dBi)";
    } else if (this.lengthRatio < 0.2) {
      if (lenEl) lenEl.innerText = `${this.lengthRatio.toFixed(2)} λ (Short Dipole)`;
      if (rEl) rEl.innerText = `${(80 * Math.PI * Math.PI * this.lengthRatio * this.lengthRatio).toFixed(1)} Ω`;
      if (gEl) gEl.innerText = "1.50 (1.76 dBi)";
    } else {
      if (lenEl) lenEl.innerText = `${this.lengthRatio.toFixed(2)} λ`;
      if (rEl) rEl.innerText = `${(73.1 * Math.pow(this.lengthRatio / 0.5, 1.8)).toFixed(1)} Ω`;
      if (gEl) gEl.innerText = `${(1.64 * Math.sqrt(this.lengthRatio / 0.5)).toFixed(2)} dBi`;
    }
  }

  render() {
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;
    const midX = w / 2;
    const midY = h / 2;

    ctx.fillStyle = "#080c14";
    ctx.fillRect(0, 0, w, h);

    // Draw antenna rod along vertical axis
    const rodH = Math.min(180, this.lengthRatio * 160);
    ctx.strokeStyle = "#e2e8f0";
    ctx.lineWidth = 4;
    ctx.beginPath();
    ctx.moveTo(midX, midY - rodH / 2);
    ctx.lineTo(midX, midY + rodH / 2);
    ctx.stroke();

    // Center feedpoint gap
    ctx.fillStyle = "#fbbf24";
    ctx.fillRect(midX - 4, midY - 3, 8, 6);

    // Draw Polar Radiation Pattern F(theta)
    ctx.lineWidth = 2.5;
    ctx.strokeStyle = "#38bdf8";
    ctx.fillStyle = "rgba(56, 189, 248, 0.15)";

    const kL2 = Math.PI * this.lengthRatio;
    ctx.beginPath();

    for (let deg = 0; deg <= 360; deg++) {
      const th = deg * Math.PI / 180;
      let F;
      if (Math.abs(Math.sin(th)) < 1e-4) {
        F = 0;
      } else {
        F = Math.abs((Math.cos(kL2 * Math.cos(th)) - Math.cos(kL2)) / Math.sin(th));
      }

      const r = F * 120;
      const x = midX + r * Math.sin(th);
      const y = midY - r * Math.cos(th);

      if (deg === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "11px Inter, sans-serif";
    ctx.fillText("Broadside Radiation Maximum (θ = 90°)", midX + 130, midY);
    ctx.fillText("Null along Antenna Axis (θ = 0°)", midX - 90, 30);
  }

  destroy() {}
}

// ==========================================
// 15. Atmospheric Skylight Polarization Simulator
// ==========================================
class PolarizationSkySim {
  constructor(container) {
    this.container = container;
    this.thetaDeg = 90; // Scattering angle
    this.initUI();
    this.render();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §5.5 Experiment</span>
            <strong class="sim-title">Rayleigh Atmospheric Polarization & 90° Solar Maximum</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="sky-canvas" width="760" height="280"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Scattering Angle (Θ)</span>
            <span class="metric-val" id="sky-th-val">90.0°</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Degree of Linear Polarization (P)</span>
            <span class="metric-val" id="sky-p-val">100.0% (Maximum)</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Parallel Intensity (I_par)</span>
            <span class="metric-val" id="sky-ipar-val">0.00 (Zero)</span>
          </div>
        </div>
        <div class="slider-control-group mt-3">
          <label>Solar Scattering Angle (Θ): <strong id="sky-th-lbl" style="color:#38bdf8;">90°</strong></label>
          <input type="range" class="range-slider" id="sky-th-slider" min="0" max="180" step="1" value="90">
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#sky-canvas");
    this.ctx = this.canvas.getContext("2d");

    this.container.querySelector("#sky-th-slider").addEventListener("input", (e) => {
      this.thetaDeg = parseFloat(e.target.value);
      this.container.querySelector("#sky-th-lbl").innerText = this.thetaDeg + "°";
      this.render();
    });
  }

  render() {
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;
    const rad = this.thetaDeg * Math.PI / 180;

    const P = Math.sin(rad) * Math.sin(rad) / (1 + Math.cos(rad) * Math.cos(rad));
    const pPct = (P * 100).toFixed(1);
    const iPar = Math.cos(rad) * Math.cos(rad);

    const thEl = this.container.querySelector("#sky-th-val");
    const pEl = this.container.querySelector("#sky-p-val");
    const iparEl = this.container.querySelector("#sky-ipar-val");

    if (thEl) thEl.innerText = `${this.thetaDeg.toFixed(1)}°`;
    if (pEl) pEl.innerText = `${pPct}%`;
    if (iparEl) iparEl.innerText = `${iPar.toFixed(2)}`;

    ctx.fillStyle = "#080c14";
    ctx.fillRect(0, 0, w, h);

    // Draw polarization curve on left
    const graphX = 60;
    const graphY = 40;
    const graphW = 280;
    const graphH = 180;

    ctx.strokeStyle = "#334155";
    ctx.lineWidth = 1;
    ctx.strokeRect(graphX, graphY, graphW, graphH);

    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    for (let deg = 0; deg <= 180; deg++) {
      const r = deg * Math.PI / 180;
      const pol = Math.sin(r) * Math.sin(r) / (1 + Math.cos(r) * Math.cos(r));
      const x = graphX + (deg / 180) * graphW;
      const y = graphY + graphH - pol * (graphH - 20);
      if (deg === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();

    // Marker on curve
    const curX = graphX + (this.thetaDeg / 180) * graphW;
    const curY = graphY + graphH - P * (graphH - 20);
    ctx.fillStyle = "#f43f5e";
    ctx.beginPath();
    ctx.arc(curX, curY, 6, 0, Math.PI * 2);
    ctx.fill();

    ctx.fillStyle = "#94a3b8";
    ctx.font = "10px Inter, sans-serif";
    ctx.fillText("0° (Forward)", graphX, graphY + graphH + 18);
    ctx.fillText("90° (Max)", graphX + graphW / 2 - 20, graphY + graphH + 18);
    ctx.fillText("180° (Back)", graphX + graphW - 40, graphY + graphH + 18);

    // Visual geometry on right
    const geomX = 540;
    const geomY = 140;

    // Molecule at center
    ctx.fillStyle = "#38bdf8";
    ctx.beginPath();
    ctx.arc(geomX, geomY, 12, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = "#000";
    ctx.font = "bold 9px Inter, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("N2", geomX, geomY + 3);

    // Incident sun ray
    ctx.strokeStyle = "#fbbf24";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(geomX - 140, geomY);
    ctx.lineTo(geomX, geomY);
    ctx.stroke();
    ctx.fillStyle = "#fbbf24";
    ctx.fillText("Sunlight", geomX - 80, geomY - 10);

    // Scattered ray to observer
    const scatLen = 130;
    const scatX = geomX + scatLen * Math.cos(rad);
    const scatY = geomY - scatLen * Math.sin(rad);

    ctx.strokeStyle = "#38bdf8";
    ctx.beginPath();
    ctx.moveTo(geomX, geomY);
    ctx.lineTo(scatX, scatY);
    ctx.stroke();

    ctx.fillStyle = "#fff";
    ctx.fillText("Observer Eye", scatX + 10, scatY);
  }

  destroy() {}
}

// ==========================================
// 16. Optical Prism Sellmeier Chromatic Dispersion Spectrometer
// ==========================================
class SellmeierPrismSim {
  constructor(container) {
    this.container = container;
    this.glass = "BK7"; // Optical crown glass
    this.animId = null;
    this.initUI();
    this.render();
  }

  initUI() {
    this.container.innerHTML = `
      <div class="sim-wrapper">
        <div class="sim-header">
          <div>
            <span class="sim-badge">Topic §6.4 Experiment</span>
            <strong class="sim-title">Prism Chromatic Dispersion & Sellmeier Spectral Splitting</strong>
          </div>
        </div>
        <div class="canvas-container">
          <canvas id="prism-canvas" width="760" height="300"></canvas>
          <div class="sim-watermark">OpenSTEM • Interactive Simulation Suite</div>
        </div>
        <div class="sim-metrics-grid">
          <div class="metric-card">
            <span class="metric-label">Red Refractive Index (700 nm)</span>
            <span class="metric-val" id="prism-nred">n = 1.513</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Violet Refractive Index (400 nm)</span>
            <span class="metric-val" id="prism-nvio">n = 1.531</span>
          </div>
          <div class="metric-card">
            <span class="metric-label">Angular Dispersion Spread</span>
            <span class="metric-val" id="prism-spread">Δθ = 1.62°</span>
          </div>
        </div>
        <div class="sim-controls" style="margin-top:1rem; display:flex; gap:0.5rem;">
          <button class="btn-control active" id="btn-glass-bk7">Crown Glass (BK7)</button>
          <button class="btn-control" id="btn-glass-silica">Fused Silica</button>
          <button class="btn-control" id="btn-glass-sf11">Dense Flint (SF11 High-Dispersion)</button>
        </div>
      </div>
    `;

    this.canvas = this.container.querySelector("#prism-canvas");
    this.ctx = this.canvas.getContext("2d");

    const btnBk7 = this.container.querySelector("#btn-glass-bk7");
    const btnSilica = this.container.querySelector("#btn-glass-silica");
    const btnSf11 = this.container.querySelector("#btn-glass-sf11");

    btnBk7.addEventListener("click", () => {
      this.glass = "BK7";
      btnBk7.classList.add("active");
      btnSilica.classList.remove("active");
      btnSf11.classList.remove("active");
      this.render();
    });

    btnSilica.addEventListener("click", () => {
      this.glass = "Silica";
      btnSilica.classList.add("active");
      btnBk7.classList.remove("active");
      btnSf11.classList.remove("active");
      this.render();
    });

    btnSf11.addEventListener("click", () => {
      this.glass = "SF11";
      btnSf11.classList.add("active");
      btnBk7.classList.remove("active");
      btnSilica.classList.remove("active");
      this.render();
    });
  }

  render() {
    const ctx = this.ctx;
    const w = this.canvas.width;
    const h = this.canvas.height;

    ctx.fillStyle = "#080c14";
    ctx.fillRect(0, 0, w, h);

    // Draw triangular glass prism (60 deg apex)
    const px = 280;
    const py = 60;
    const side = 180;

    ctx.fillStyle = "rgba(56, 189, 248, 0.12)";
    ctx.strokeStyle = "#38bdf8";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.lineTo(px - side / 2, py + side * 0.866);
    ctx.lineTo(px + side / 2, py + side * 0.866);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    // Incident white light beam
    ctx.strokeStyle = "#ffffff";
    ctx.lineWidth = 4;
    ctx.beginPath();
    ctx.moveTo(40, 200);
    ctx.lineTo(px - side * 0.25, py + side * 0.5);
    ctx.stroke();

    ctx.fillStyle = "#ffffff";
    ctx.font = "12px Inter, sans-serif";
    ctx.fillText("White Incident Light Beam", 45, 180);

    // Spectrum dispersion
    const hitX = px - side * 0.25;
    const hitY = py + side * 0.5;

    const colors = [
      { name: "Red", lambda: 700, col: "#ef4444", n: this.glass === "SF11" ? 1.76 : (this.glass === "BK7" ? 1.513 : 1.455) },
      { name: "Orange", lambda: 620, col: "#f97316", n: this.glass === "SF11" ? 1.77 : (this.glass === "BK7" ? 1.516 : 1.457) },
      { name: "Yellow", lambda: 580, col: "#eab308", n: this.glass === "SF11" ? 1.78 : (this.glass === "BK7" ? 1.519 : 1.459) },
      { name: "Green", lambda: 530, col: "#22c55e", n: this.glass === "SF11" ? 1.80 : (this.glass === "BK7" ? 1.523 : 1.461) },
      { name: "Blue", lambda: 470, col: "#3b82f6", n: this.glass === "SF11" ? 1.82 : (this.glass === "BK7" ? 1.527 : 1.464) },
      { name: "Violet", lambda: 400, col: "#a855f7", n: this.glass === "SF11" ? 1.85 : (this.glass === "BK7" ? 1.531 : 1.470) }
    ];

    colors.forEach((c, idx) => {
      const bend = (c.n - 1.4) * 0.6;
      const internalX = px + side * 0.2;
      const internalY = py + side * 0.45 + idx * 3.5;

      // Inside prism
      ctx.strokeStyle = c.col;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(hitX, hitY);
      ctx.lineTo(internalX, internalY);
      ctx.stroke();

      // Exiting fan onto screen
      const screenX = w - 80;
      const screenY = 80 + idx * 28 + (this.glass === "SF11" ? idx * 8 : 0);

      ctx.beginPath();
      ctx.moveTo(internalX, internalY);
      ctx.lineTo(screenX, screenY);
      ctx.stroke();

      ctx.fillStyle = c.col;
      ctx.fillRect(screenX, screenY - 5, 12, 10);
      ctx.fillStyle = "#94a3b8";
      ctx.font = "10px Inter, sans-serif";
      ctx.fillText(`${c.name} (${c.lambda}nm)`, screenX + 18, screenY + 3);
    });

    const nRedEl = this.container.querySelector("#prism-nred");
    const nVioEl = this.container.querySelector("#prism-nvio");
    const sprEl = this.container.querySelector("#prism-spread");

    if (nRedEl) nRedEl.innerText = `n = ${colors[0].n.toFixed(3)}`;
    if (nVioEl) nVioEl.innerText = `n = ${colors[5].n.toFixed(3)}`;
    const spr = ((colors[5].n - colors[0].n) * 90).toFixed(2);
    if (sprEl) sprEl.innerText = `Δθ = ${spr}°`;
  }

  destroy() {}
}
