# -*- coding: utf-8 -*-
"""
expand_org2_deep.py
Deep physical organic and spectroscopic expansion for Organic Chemistry II.
Injects comprehensive spectroscopic tables (1H NMR, 13C NMR, FT-IR, UV-Vis, HRMS),
thermodynamic and kinetic activation parameters, and mechanistic boundary cases.
Pushes master data file to >66,000 words.
Strict zero course numbers or marks.
"""

def deep_enrich_all_units(units):
    print("Applying deep physical organic & spectroscopic expansions across all 9 units...")

    # --- UNIT 1 EXPANSIONS ---
    u1 = units[0]
    u1["sections"][1]["content"] += r"""

### High-Resolution Spectroscopic Fingerprints of Polynuclear Aromatics

The magnetic anisotropy generated by delocalized ring currents in fused benzenoids produces distinctive nuclear magnetic resonance ($^1\text{H}$ and $^{13}\text{C}$ NMR) and vibrational (FT-IR) signatures:

| Compound | $^1\text{H}$ NMR ($\delta$ in $\text{ppm}$, $\text{CDCl}_3$) | $^{13}\text{C}$ NMR ($\delta$ in $\text{ppm}$) | FT-IR ($\nu_{\max}$ in $\text{cm}^{-1}$) | UV-Vis ($\lambda_{\max}$ in $\text{nm}$, $\log\epsilon$) |
| :--- | :--- | :--- | :--- | :--- |
| **Naphthalene** | $\delta\ 7.85$ (m, $4\text{H}$, $\alpha$-H)<br>$\delta\ 7.48$ (m, $4\text{H}$, $\beta$-H) | $\delta\ 133.6$ (C4a, C8a)<br>$\delta\ 127.9$ ($\alpha$, C1/C4/C5/C8)<br>$\delta\ 125.8$ ($\beta$, C2/C3/C6/C7) | $3050$ (aromatic $\text{C}-\text{H}$ stretch)<br>$1600, 1505$ (ring skeletal)<br>$782$ (strong, $4$ adjacent $\text{C}-\text{H}$ out-of-plane bend) | $221\ (5.05)$<br>$275\ (3.75)$<br>$312\ (2.45)$ |
| **Anthracene** | $\delta\ 8.42$ (s, $2\text{H}$, C9/C10 meso-H)<br>$\delta\ 7.99$ (m, $4\text{H}$, $\alpha$-H)<br>$\delta\ 7.46$ (m, $4\text{H}$, $\beta$-H) | $\delta\ 131.8$ (C4a/C8a/C9a/C10a)<br>$\delta\ 128.3$ ($\alpha$-carbons)<br>$\delta\ 127.2$ ($\beta$-carbons)<br>$\delta\ 125.5$ (C9/C10 meso-carbons) | $3052$ (aromatic $\text{C}-\text{H}$)<br>$1622, 1448$ (ring)<br>$884$ (isolated meso $\text{C}-\text{H}$)<br>$725$ (out-of-plane) | $256\ (5.26)$<br>$310\ (3.30)$<br>$356\ (3.90)$<br>$375\ (3.95)$ |
| **Phenanthrene** | $\delta\ 8.70$ (d, $2\text{H}$, C4/C5 bay-H)<br>$\delta\ 7.89$ (d, $2\text{H}$, C1/C8)<br>$\delta\ 7.74$ (s, $2\text{H}$, C9/C10 K-region)<br>$\delta\ 7.63$ (m, $4\text{H}$, C2/C3/C6/C7) | $\delta\ 132.0$ (C4a/C4b)<br>$\delta\ 130.3$ (C8a/C10a)<br>$\delta\ 128.5$ (C1/C8)<br>$\delta\ 126.9$ (C9/C10)<br>$\delta\ 126.5$ (C3/C6)<br>$\delta\ 122.6$ (C4/C5) | $3058$ (aromatic $\text{C}-\text{H}$)<br>$1601, 1495$ (ring)<br>$812$ ($2$ adjacent $\text{C}-\text{H}$)<br>$715$ ($4$ adjacent $\text{C}-\text{H}$) | $211\ (4.65)$<br>$251\ (4.85)$<br>$274\ (4.15)$<br>$293\ (4.20)$ |

Notice that the **bay protons (H4 and H5)** in phenanthrene are shifted dramatically downfield to **$\delta\ 8.70\text{ ppm}$**! This extreme deshielding arises because:
1. They project directly into the combined van der Waals repulsive fields of each other ($d_{\text{H4}\cdots\text{H5}} \approx 2.05\text{ \AA}$).
2. They lie directly inside the additive diamagnetic deshielding cones of both opposite aromatic rings."""

    # --- UNIT 2 EXPANSIONS ---
    u2 = units[1]
    u2["sections"][1]["content"] += r"""

### Spectroscopic Diagnostics of the Carbonyl Group: FT-IR and NMR Profiles

The vibrational frequency of the carbonyl group ($\nu_{\text{C=O}}$) is the most diagnostic infrared signal in organic analysis, governed by Hooke's law for a harmonic oscillator:

$$\nu = \frac{1}{2\pi c} \sqrt{\frac{k}{\mu}} \tag{2.0a}$$

where $k$ is the effective bond force constant ($k \approx 1200\text{ N/m}$ for $\text{C}=\text{O}$) and $\mu = \frac{m_{\text{C}} m_{\text{O}}}{m_{\text{C}} + m_{\text{O}}} \approx 1.14 \times 10^{-26}\text{ kg}$ is the reduced mass.

| Carbonyl Substrate | FT-IR $\nu_{\text{C=O}}$ ($\text{cm}^{-1}$) | $^{13}\text{C}$ NMR ($\delta$ in $\text{ppm}$) | $^1\text{H}$ NMR ($\delta$ in $\text{ppm}$) | Electronic Origin of Shifts |
| :--- | :--- | :--- | :--- | :--- |
| **Aliphatic Aldehyde** ($\text{RCHO}$) | $1725\text{–}1740$ | $\delta\ 195\text{–}205$ | $\delta\ 9.5\text{–}10.0$ (s/d, formyl H) | Fermi resonance doublet at $2820$ and $2720\text{ cm}^{-1}$ ($\text{C}-\text{H}$ stretch) |
| **Aliphatic Ketone** ($\text{RCOR}'$) | $1715$ | $\delta\ 205\text{–}215$ | $\delta\ 2.1\text{–}2.5$ ($\alpha$-$\text{CH}_2$ multiplet) | Standard unconstrained $sp^2$ force constant |
| **$\alpha,\beta$-Unsaturated Ketone** | $1685\text{–}1690$ | $\delta\ 195\text{–}202$ | $\delta\ 5.8\text{–}6.8$ (vinyl $\text{H}_\alpha, \text{H}_\beta$) | $\pi$-Conjugation lowers double-bond order ($\Delta\nu \approx -30\text{ cm}^{-1}$) |
| **Aryl Ketone** ($\text{ArCOR}$) | $1685$ | $\delta\ 197\text{–}200$ | $\delta\ 7.4\text{–}8.0$ (aromatic $\text{H}$) | Resonance donation from phenyl ring lowers force constant |
| **Cyclobutanone** | $1785$ | $\delta\ 208$ | $\delta\ 3.0$ ($\alpha$-$\text{CH}_2$) | Severe internal angle strain ($90^\circ$) concentrates $s$-character into exocyclic $\text{C}=\text{O}$ |
| **Cyclopentanone** | $1745$ | $\delta\ 215$ | $\delta\ 2.2$ ($\alpha$-$\text{CH}_2$) | Moderate ring strain ($108^\circ$) elevates stretching frequency |
| **Cyclohexanone** | $1715$ | $\delta\ 211$ | $\delta\ 2.3$ ($\alpha$-$\text{CH}_2$) | Strain-free chair conformation identical to acyclic ketone |"""

    # --- UNIT 3 EXPANSIONS ---
    u3 = units[2]
    u3["sections"][1]["content"] += r"""

### Spectroscopic Profiles & Hydrogen-Bonded Dimer Dynamics of Carboxylic Acids

In non-polar solvents ($\text{CCl}_4, \text{CDCl}_3$) and in the pure liquid/solid state, carboxylic acids exist almost exclusively as **centrosymmetric cyclic dimers** held together by two strong, cooperative intermolecular hydrogen bonds ($\Delta H^\circ_{\text{dimerization}} \approx -58\text{ kJ}\cdot\text{mol}^{-1}$):

```
       Carboxylic Acid Cyclic Dimer:
                 O . . . . . . H - O
                //                   \\
             R-C                       C-R
                \\                   //
                 O - H . . . . . . O
```

1. **FT-IR Signatures**:
   - **Broad $\text{O}-\text{H}$ Envelope**: An extraordinarily broad, intense absorption stretching continuously from **$2500\text{ cm}^{-1}$ to $3300\text{ cm}^{-1}$**, centered at $\sim 3000\text{ cm}^{-1}$, characterized by distinct Fermi resonance sub-peaks ("satellite bumps") at $2600$ and $2700\text{ cm}^{-1}$. This extreme breadth is the definitive diagnostic signature distinguishing carboxylic acids from alcohols (which show smooth $\text{O}-\text{H}$ bands at $3300\text{–}3600\text{ cm}^{-1}$).
   - **Carbonyl Stretch ($\nu_{\text{C=O}}$)**:
     - Dimerized form: $1710\text{ cm}^{-1}$.
     - Monomeric free form (highly dilute in gas phase): $1760\text{ cm}^{-1}$.
2. **Nuclear Magnetic Resonance ($^1\text{H}$ & $^{13}\text{C}$ NMR)**:
   - **Carboxyl Proton ($-\text{COOH}$)**: Appears downfield at **$\delta\ 10.5\text{–}13.0\text{ ppm}$** as a broad singlet. The extreme chemical shift reflects powerful magnetic deshielding by the adjacent carbonyl group and cyclic hydrogen-bond polarization. The signal exchanges rapidly upon adding $\text{D}_2\text{O}$ ($\text{RCOOH} + \text{D}_2\text{O} \to \text{RCOOD} + \text{HOD}$), causing the peak to vanish.
   - **Carboxyl Carbon ($-\text{COOH}$)**: Appears characteristically at **$\delta\ 175\text{–}185\text{ ppm}$** in $^{13}\text{C}$ NMR, substantially upfield from aldehyde/ketone carbonyls ($\delta\ 195\text{–}215\text{ ppm}$) due to resonance shielding by the hydroxyl oxygen lone pair."""

    # --- UNIT 4 EXPANSIONS ---
    u4 = units[3]
    u4["sections"][2]["content"] += r"""

### Infrared Carbonyl Frequencies Across the Carboxylic Derivative Family

The infrared stretching frequency of carboxylic acid derivatives provides a direct physical measure of the competition between **electronegative inductive withdrawal ($-I$)** and **resonance lone-pair donation ($+M$)**:

$$\text{Inductive Pull } (-I) \implies \text{Concentrates } s\text{-character into C=O} \implies k \uparrow \implies \nu \uparrow \tag{4.0a}$$
$$\text{Resonance Donation } (+M) \implies \text{Single-bond character into C-O} \implies k \downarrow \implies \nu \downarrow \tag{4.0b}$$

| Derivative Class | Representative Formula | FT-IR $\nu_{\text{C=O}}$ ($\text{cm}^{-1}$) | $^{13}\text{C}$ NMR ($\delta$ in $\text{ppm}$) | Dominant Electronic Factor |
| :--- | :--- | :--- | :--- | :--- |
| **Acyl Halides** | $\text{CH}_3\text{COCl}$ | **$1800\text{–}1815$** | $\delta\ 170\text{–}175$ | Severe $-I$ pull by chlorine; poor $2p-3p$ orbital overlap suppresses resonance |
| **Acid Anhydrides** | $(\text{CH}_3\text{CO})_2\text{O}$ | **$1820$ and $1750$** (Doublet) | $\delta\ 165\text{–}170$ | Symmetric and asymmetric vibrational coupling of the two coupled carbonyls |
| **Esters** | $\text{CH}_3\text{COOEt}$ | **$1735\text{–}1750$** | $\delta\ 170\text{–}175$ | Balanced $-I$ withdrawal and $+M$ resonance |
| **Carboxylic Acids** | $\text{CH}_3\text{COOH}$ | **$1710$** (Dimer) | $\delta\ 175\text{–}180$ | Hydrogen-bond weakening of carbonyl double bond |
| **Amides** | $\text{CH}_3\text{CONH}_2$ | **$1650\text{–}1690$** (Amide I) | $\delta\ 165\text{–}175$ | Massive $+M$ resonance donation ($40\%$ double bond character in $\text{C}-\text{N}$) |
| **Carboxylate Salts** | $\text{CH}_3\text{COO}^-\text{Na}^+$ | **$1580$ and $1400$** (Asym / Sym) | $\delta\ 180\text{–}185$ | Degenerate delocalization gives true bond order of $1.5$ |"""

    # --- UNIT 5 EXPANSIONS ---
    u5 = units[4]
    u5["sections"][1]["content"] += r"""

### Spectroscopic Identification of Nitrogen Systems: FT-IR, $^{1}\text{H}$ & $^{13}\text{C}$ NMR

Amine classes ($1^\circ, 2^\circ, 3^\circ$), diazonium salts, and nitro compounds are readily distinguished by their characteristic vibrational bands and chemical shifts:

| Nitrogen Class | Structure | FT-IR ($\nu_{\max}$ in $\text{cm}^{-1}$) | $^1\text{H}$ NMR ($\delta$ in $\text{ppm}$) | Diagnostic Features |
| :--- | :--- | :--- | :--- | :--- |
| **Primary Amine ($1^\circ$)** | $\text{R-NH}_2$ | **$3300\text{–}3500$** (Two distinct peaks: sym and asym $\text{N}-\text{H}$ stretch) | $\delta\ 1.0\text{–}3.0$ (broad singlet, $2\text{H}$, exchanges with $\text{D}_2\text{O}$) | Scissoring band at $1580\text{–}1650\text{ cm}^{-1}$ |
| **Secondary Amine ($2^\circ$)** | $\text{R}_2\text{NH}$ | **$3300\text{–}3400$** (Exactly ONE peak: single $\text{N}-\text{H}$ stretch) | $\delta\ 1.0\text{–}3.0$ (broad singlet, $1\text{H}$, exchanges with $\text{D}_2\text{O}$) | Weaker intensity than primary amine |
| **Tertiary Amine ($3^\circ$)** | $\text{R}_3\text{N}$ | **No $\text{N}-\text{H}$ absorption** | No exchangeable proton | $\text{C}-\text{N}$ stretch at $1050\text{–}1200\text{ cm}^{-1}$ |
| **Arenediazonium Salt** | $[\text{Ar-N}_2]^+\text{BF}_4^-$ | **$2260\text{–}2300$** (Extremely sharp, intense $\text{N}\equiv\text{N}$ stretch) | $\delta\ 8.0\text{–}8.8$ (strongly deshielded ortho-aromatic protons) | Insoluble in non-polar solvents; explodes on dry impact |
| **Aliphatic Nitro** | $\text{R-NO}_2$ | **$1550$** (Asymmetric $\text{N}=\text{O}$) and **$1370$** (Symmetric $\text{N}=\text{O}$) | $\delta\ 4.3\text{–}4.6$ ($\alpha$-$\text{CH}_2$ downfield multiplet) | Powerful $-I$ deshielding on adjacent carbon |
| **Aromatic Nitro** | $\text{Ar-NO}_2$ | **$1525$** (Asymmetric) and **$1345$** (Symmetric) | $\delta\ 8.1\text{–}8.3$ (ortho protons strongly deshielded) | Strongly deactivates aromatic ring |"""

    # --- UNIT 6 EXPANSIONS ---
    u6 = units[5]
    u6["sections"][0]["content"] += r"""

### Mathematical Group Theory & Chirality Operations Matrix

The complete set of symmetry operations acting on three-dimensional molecular Cartesian coordinates $\mathbf{x} = (x, y, z)^T$ is represented by $3 \times 3$ orthogonal transformation matrices $\mathbf{R} \in O(3)$:

$$\det(\mathbf{R}) = \begin{cases} +1 & \text{Proper Rotation } (C_n) \\ -1 & \text{Improper Rotation } (S_n, \sigma, i) \end{cases} \tag{6.0a}$$

1. **Proper Rotation Matrix $\mathbf{R}_z(\theta)$**:
   $$\mathbf{R}_z(\theta) = \begin{pmatrix} \cos\theta & -\sin\theta & 0 \\ \sin\theta & \cos\theta & 0 \\ 0 & 0 & 1 \end{pmatrix}, \quad \det(\mathbf{R}_z) = \cos^2\theta + \sin^2\theta = +1$$
2. **Reflection Matrix $\boldsymbol{\sigma}_{xy}$**:
   $$\boldsymbol{\sigma}_{xy} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & -1 \end{pmatrix}, \quad \det(\boldsymbol{\sigma}_{xy}) = -1$$
3. **Inversion Matrix $\mathbf{i}$**:
   $$\mathbf{i} = \begin{pmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \end{pmatrix}, \quad \det(\mathbf{i}) = -1$$

A molecule is chiral if and only if **no operation with $\det(\mathbf{R}) = -1$ belongs to its symmetry point group**. Therefore:
- Point groups containing only operations with $\det(\mathbf{R}) = +1$ are the **chiral point groups**: $C_1, C_n, D_n, T, O, I$.
- Any point group containing $C_s$ ($\sigma$), $C_i$ ($i$), $C_{nv}$, $C_{nh}$, $D_{nh}$, $D_{nd}$, or $S_n$ contains improper operations ($\det = -1$) and is strictly **achiral**."""

    # --- UNIT 7 EXPANSIONS ---
    u7 = units[6]
    u7["sections"][0]["content"] += r"""

### Spectroscopic & Thermodynamic Profile of Ethyl Acetoacetate Tautomers

The keto and enol tautomers of ethyl acetoacetate exhibit distinct spectroscopic signatures that allow non-destructive quantitative NMR analysis:

```
Spectroscopic Distinction Between EAA Tautomers:
Keto Form:  1H NMR: delta 3.45 (s, 2H, -CH2-); 13C NMR: delta 200.7 (C=O ketone), delta 167.2 (C=O ester)
            FT-IR:  1740 cm-1 (ester C=O), 1718 cm-1 (ketone C=O)
Enol Form:  1H NMR: delta 4.98 (s, 1H, =CH-), delta 12.05 (s, 1H, =C-OH H-bonded chelate)
            13C NMR: delta 173.0 (C=O), delta 89.8 (=CH-), delta 178.0 (=C-OH)
            FT-IR:  1650 cm-1 (conjugated chelated C=O), 1630 cm-1 (C=C enol), 3400-3000 cm-1 (broad O-H...O)
```

By integrating the singlet at $\delta\ 3.45\text{ ppm}$ ($2\text{H}$, keto $-\text{CH}_2-$) against the singlet at $\delta\ 4.98\text{ ppm}$ ($1\text{H}$, enol $=\text{CH}-$), the exact percentage of enol present in any solvent is determined instantaneously:

$$\% \text{ enol} = \frac{I_{4.98}}{I_{4.98} + \frac{1}{2} I_{3.45}} \times 100\% \tag{7.0a}$$

In deuterated benzene ($\text{C}_6\text{D}_6$), $\% \text{ enol} = 16.2\%$; in neat liquid, $\% \text{ enol} = 8.0\%$; in deuterated water ($\text{D}_2\text{O}$), $\% \text{ enol} = 0.4\%$, directly verifying the thermodynamic solvent dependence."""

    # --- UNIT 8 EXPANSIONS ---
    u8 = units[7]
    u8["sections"][0]["content"] += r"""

### Hansch Linear Free-Energy Analysis of Sulfonamide Antibacterials

Corwin Hansch (1964) established the quantitative structure-activity relationship (QSAR) linking the biological potency of sulfonamides to physical organic descriptors:

$$\log \left(\frac{1}{C}\right) = -k_1 (\log P)^2 + k_2 (\log P) + \rho \, \sigma + \delta \, E_s + \text{constant} \tag{8.0a}$$

where:
- $C$ is the minimum inhibitory concentration ($\text{MIC}$) required to arrest bacterial growth.
- $\log P$ is the octanol-water partition coefficient, reflecting molecular **lipophilicity** and membrane permeation.
- $\sigma$ is the **Hammett electronic substituent constant** of the group attached to the sulfonamide nitrogen.
- $E_s$ is the **Taft steric parameter**.

For a series of $N^1$-heterocyclic sulfanilamide derivatives:
1. Antibacterial potency increases as the sulfonamide $\text{p}K_a$ decreases from $10.4$ down to **$\text{p}K_a \approx 6.5\text{–}7.0$**.
2. At $\text{p}K_a \approx 6.5\text{–}7.0$, the degree of ionization at physiological $\text{pH}$ ($7.4$) is $\sim 50\%$. The neutral form permeates through the bacterial lipid bilayer, while the ionized sulfonamidate anion ($-\text{SO}_2\text{N}^-\text{-R}$) docks into the cationic active site of dihydropteroate synthase (DHPS), maximizing antibacterial efficacy."""

    # --- UNIT 9 EXPANSIONS ---
    u9 = units[8]
    u9["sections"][3]["content"] += r"""

### Natural Product Alkaloids Derived from the Indole & Quinoline Skeletons

Fused heterocyclic rings serve as the universal structural templates for thousands of bioactive natural alkaloids isolated from terrestrial flora and marine fauna:

| Alkaloid Class | Representative Molecule | Botanical Source | Heterocyclic Skeleton | Pharmacological Mechanism & Therapeutic Application |
| :--- | :--- | :--- | :--- | :--- |
| **Indole Alkaloid** | **Vinblastine / Vincristine** | *Catharanthus roseus* (Madagascar periwinkle) | Bis-indole (vindoline + catharanthine) | Binds to tubulin dimers, preventing microtubule assembly; frontline chemotherapy for Hodgkin lymphoma and childhood acute lymphoblastic leukemia |
| **Indole Alkaloid** | **Strychnine** | *Strychnos nux-vomica* | Hexacyclic indole | Competitive antagonist of glycine receptors in spinal motor neurons; causes violent tetanic convulsions |
| **Indole Alkaloid** | **Reserpine** | *Rauvolfia serpentina* (Indian snakeroot) | Pentacyclic indole | Irreversibly blocks vesicular monoamine transporter 2 (VMAT2); historically used as antipsychotic and antihypertensive |
| **Quinoline Alkaloid** | **Quinine** | *Cinchona officinalis* (Cinchona bark) | Fused quinoline + quinuclidine | Inhibits biocrystallization of toxic heme into hemozoin inside malarial food vacuole; historic antimalarial |
| **Quinoline Alkaloid** | **Camptothecin** | *Camptotheca acuminata* (Happy tree) | Pyrrolo[3,4-b]quinoline pentacycle | Inhibits human topoisomerase I, stabilizing cleavable DNA complexes; parent of modern oncology drugs Topotecan and Irinotecan |
| **Isoquinoline Alkaloid** | **Morphine / Codeine** | *Papaver somniferum* (Opium poppy) | Phenanthrene-fused tetrahydroisoquinoline | Potent agonist of $\mu$-opioid G-protein coupled receptors; gold standard clinical analgesic |"""

    print("Deep expansions completed across all 9 units!")
