import json

print("=== FIXING PROBLEM STATEMENTS IN AMP & BE ===")

# --- AMP UNITS 1 to 6 ---
with open("amp_u1.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "An observer on a space station observes spaceship $A$ traveling along the positive $x$-axis at velocity $v_A = +0.80 c$. Spaceship $B$ is observed traveling along the same axis in pursuit at velocity $v_B = +0.90 c$. (a) Using the relativistic velocity addition formula, calculate the relative velocity $v_{BA}$ of spaceship $B$ as measured by an observer aboard spaceship $A$. (b) What would the classical Galilean velocity addition formula predict, and what is the percentage error of the classical calculation?"
d["problems"][1]["statement"] = "Muons created at an altitude of $H = 10.0\\text{ km}$ in the upper atmosphere travel downward toward Earth at speed $v = 0.998 c$. The proper rest lifetime of a muon is $\\tau_0 = 2.20\\ \\mu\\text{s}$. (a) Calculate the Lorentz factor $\\gamma$ and the classical distance a muon travels before decaying without relativistic time dilation. (b) Calculate the mean decay distance in the Earth's reference frame taking time dilation into account. (c) Explain from the perspective of an observer traveling in the muon's rest frame (length contraction) how muons reach the Earth's surface."
d["problems"][2]["statement"] = "An antiproton ($\\bar{p}$) can be created in a high-energy proton-proton collision when a moving proton of rest mass $m_p$ strikes a stationary target proton: $p + p \\to p + p + p + \\bar{p}$. Given that the rest energy of a proton and antiproton is $m_p c^2 = 938.3\\text{ MeV}$: (a) Use four-momentum invariants to derive the threshold total energy $E_{\\text{th}}$ and kinetic energy $K_{\\text{th}}$ of the incident beam proton. (b) Compute the numerical value of $K_{\\text{th}}$ in GeV."
with open("amp_u1.json", "w") as f:
    json.dump(d, f, indent=2)

with open("amp_u2.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "When a metallic cesium surface is illuminated with ultraviolet light of wavelength $\\lambda_1 = 300\\text{ nm}$, the stopping potential is measured to be $V_{01} = 2.24\\text{ V}$. When illuminated with light of wavelength $\\lambda_2 = 400\\text{ nm}$, the stopping potential is $V_{02} = 1.20\\text{ V}$. (a) Using Einstein's photoelectric equation, determine Planck's constant $h$ from these data. (b) Calculate the work function $\\Phi$ of cesium in electron-volts. (c) Determine the threshold cutoff frequency $\\nu_0$ and threshold wavelength $\\lambda_0$."
d["problems"][1]["statement"] = "A gamma-ray photon with energy $E = 0.511\\text{ MeV}$ (equal to the rest mass energy of an electron) collides with a stationary free electron and is scattered through an angle $\\theta = 60.0^\\circ$. (a) Determine the Compton shift $\\Delta\\lambda$ and the scattered photon wavelength $\\lambda'$. (b) Calculate the energy of the scattered photon $E'$ in keV. (c) Compute the kinetic energy $K_e$ and scattering recoil angle $\\phi$ of the recoil electron."
d["problems"][2]["statement"] = "An X-ray tube operates with an accelerating voltage of $V = 50\\text{ kV}$. (a) Calculate the Duane-Hunt minimum wavelength cutoff $\\lambda_{\\text{min}}$ in angstroms. (b) The $K_\\alpha$ characteristic line for a target with atomic number $Z = 42$ (Molybdenum) occurs at $\\lambda = 0.071\\text{ nm}$. Using Moseley's empirical law $\\sqrt{\\nu} = a(Z - \\sigma)$ with screening constant $\\sigma = 1$, predict the $K_\\alpha$ wavelength for a target with $Z = 74$ (Tungsten)."
with open("amp_u2.json", "w") as f:
    json.dump(d, f, indent=2)

with open("amp_u3.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "Calculate the de Broglie wavelength for three different physical systems: (a) An electron accelerated from rest across an electric potential difference $V = 100\\text{ V}$. (b) A relativistic electron with kinetic energy $K = 2.0\\text{ MeV}$ ($m_e c^2 = 0.511\\text{ MeV}$). (c) A thermal neutron at room temperature $T = 300\\text{ K}$ ($m_n = 1.675 \\times 10^{-27}\\text{ kg}$, $k_B = 1.381 \\times 10^{-23}\\text{ J/K}$)."
d["problems"][1]["statement"] = "An atomic nucleus has a characteristic diameter of $d = 8.0\\text{ fm}$ ($8.0 \\times 10^{-15}\\text{ m}$). Assuming an electron were confined inside this nuclear volume: (a) Use Heisenberg's uncertainty principle $\\Delta x \\Delta p \\ge \\hbar / 2$ with spatial uncertainty $\\Delta x \\approx d$ to estimate the minimum momentum uncertainty $\\Delta p$. (b) Using the relativistic energy-momentum relation $E^2 = p^2 c^2 + m^2 c^4$, compute the minimum kinetic energy of the electron in MeV. (c) Compare this result with observed beta-decay energies ($0.1\\text{ to }3\\text{ MeV}$) and explain why electrons cannot exist as permanent nuclear constituents."
d["problems"][2]["statement"] = "An excited atomic state of an atom has a mean lifetime of $\\tau = 1.20 \\times 10^{-8}\\text{ s}$ ($12.0\\text{ ns}$) before de-exciting to the ground state with the emission of a photon of wavelength $\\lambda_0 = 600.0\\text{ nm}$. (a) Calculate the intrinsic energy uncertainty $\\Delta E$ of the excited state in electron-volts using the energy-time uncertainty principle $\\Delta E \\Delta t \\ge \\hbar / 2$. (b) Determine the natural frequency linewidth $\\Delta\\nu$ in MHz and the natural wavelength linewidth $\\Delta\\lambda$ in angstroms. (c) Explain why observed spectroscopic lines in laboratory discharges are typically orders of magnitude broader than this natural limit."
with open("amp_u3.json", "w") as f:
    json.dump(d, f, indent=2)

with open("amp_u4.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "An alpha particle beam with kinetic energy $K = 7.7\\text{ MeV}$ is directed at a thin gold foil ($Z = 79$, density $\\rho = 19.3\\text{ g/cm}^3$, thickness $t = 1.0\\ \\mu\\text{m}$, molar mass $M = 197\\text{ g/mol}$). (a) Calculate the distance of closest approach $d_{\\text{min}}$ for a head-on collision (scattering angle $\\theta = 180^\\circ$). (b) Compute the impact parameter $b$ corresponding to a scattering angle $\\theta = 60.0^\\circ$. (c) Determine the fraction $f$ of incident alpha particles scattered through angles greater than $60.0^\\circ$."
d["problems"][1]["statement"] = "For singly-ionized helium ($\\text{He}^+, Z = 2$): (a) Calculate the radius of the ground state orbit $r_1$ and the ground state energy $E_1$ using the Bohr model. (b) Find the wavelength of the photon emitted in the transition from $n = 4$ to $n = 2$ in $\\text{He}^+$ and determine in what spectral region this line lies. (c) Compare this transition to the $n = 2 \\to n = 1$ Lyman-alpha transition of atomic hydrogen."
d["problems"][2]["statement"] = "Given the proton mass $m_p = 1.67262 \\times 10^{-27}\\text{ kg}$, deuteron mass $m_d = 3.34358 \\times 10^{-27}\\text{ kg}$, and electron mass $m_e = 9.10938 \\times 10^{-31}\\text{ kg}$: (a) Calculate the reduced mass of ordinary hydrogen $\\mu_H$ and deuterium $\\mu_D$. (b) Using the Rydberg constant $R = \\mu e^4 / (8 \\varepsilon_0^2 h^3 c)$, compute the wavelength of the Balmer alpha line ($n = 3 \\to 2$) for hydrogen ($\\lambda_H$) and deuterium ($\\lambda_D$). (c) Compute the isotope wavelength shift $\\Delta\\lambda = \\lambda_H - \\lambda_D$ in angstroms and explain how this shift led to the experimental discovery of deuterium."
with open("amp_u4.json", "w") as f:
    json.dump(d, f, indent=2)

with open("amp_u5.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "The Sodium doublet lines have measured wavelengths $\\lambda_1 = 589.6\\text{ nm}$ ($3^2P_{1/2} \\to 3^2S_{1/2}$) and $\\lambda_2 = 589.0\\text{ nm}$ ($3^2P_{3/2} \\to 3^2S_{1/2}$). (a) Calculate the fine structure energy splitting $\\Delta E$ between the $3^2P_{3/2}$ and $3^2P_{1/2}$ states in eV. (b) Assuming this splitting is due to the interaction of the electron's spin magnetic moment with an internal magnetic field $B_{\\text{int}}$, calculate the effective strength of $B_{\\text{int}}$ in Tesla ($\\Delta E = 2\\mu_B B_{\\text{int}}$)."
d["problems"][1]["statement"] = "An atom in a weak external magnetic field of $B = 1.50\\text{ Tesla}$ undergoes a transition between the $^2P_{3/2}$ state and the $^2S_{1/2}$ state. (a) Calculate the Landé $g$-factors $g_J$ for both states. (b) Determine the magnetic splitting $\\Delta E$ between adjacent $m_j$ levels for each state. (c) Applying the electric dipole selection rules $\\Delta m_j = 0, \\pm 1$, determine the number of allowed anomalous Zeeman spectral lines and draw an energy-level transition diagram."
d["problems"][2]["statement"] = "For an atom with two equivalent p-electrons ($p^2$ configuration, such as Carbon in its ground state): (a) Determine all possible microstates $(m_{l1}, m_{s1}, m_{l2}, m_{s2})$ satisfying the Pauli exclusion principle. (b) Group these microstates into allowed spectroscopic terms $^{2S+1}L_J$. (c) Apply Hund's rules to identify the ground-state term symbol."
with open("amp_u5.json", "w") as f:
    json.dump(d, f, indent=2)

with open("amp_u6.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "The pure rotational absorption spectrum of $^{12}\\text{C}^{16}\\text{O}$ exhibits a series of equidistant absorption lines with a constant wavenumber separation $\\Delta\\bar{\\nu} = 3.842\\text{ cm}^{-1}$. (a) Calculate the rotational constant $B$ in $\\text{cm}^{-1}$ and in Joules. (b) Determine the moment of inertia $I_0$ of the CO molecule. (c) Given atomic masses $m(^{12}\\text{C}) = 1.9926 \\times 10^{-26}\\text{ kg}$ and $m(^{16}\\text{O}) = 2.6567 \\times 10^{-26}\\text{ kg}$, calculate the reduced mass $\\mu$ and the equilibrium internuclear bond distance $r_0$ in angstroms."
d["problems"][1]["statement"] = "The fundamental infrared absorption band of hydrogen chloride ($^1\\text{H}^{35}\\text{Cl}$) has its band origin (missing Q-branch) at wavenumber $\\bar{\\nu}_0 = 2885.9\\text{ cm}^{-1}$. (a) Calculate the fundamental vibrational frequency $\\nu_0$ in Hz and the effective chemical bond force constant $k$ in N/m (reduced mass $\\mu = 1.6267 \\times 10^{-27}\\text{ kg}$). (b) Compute the zero-point vibrational energy (ZPE) of the molecule in eV. (c) Predict the fundamental vibrational wavenumber $\\bar{\\nu}_0'$ for deuterium chloride ($^2\\text{H}^{35}\\text{Cl}$) assuming the same force constant."
d["problems"][2]["statement"] = "A gas of nitrogen molecules ($\\text{N}_2$) is irradiated with a green Nd:YAG laser beam of wavelength $\\lambda_0 = 532.0\\text{ nm}$. The vibrational wavenumber of $\\text{N}_2$ is $\\Delta\\bar{\\nu} = 2331\\text{ cm}^{-1}$. (a) Calculate the wavelengths of the Stokes and anti-Stokes Raman scattered lines in nanometers. (b) At room temperature $T = 300\\text{ K}$, calculate the theoretical intensity ratio $I_{\\text{anti-Stokes}} / I_{\\text{Stokes}}$ using the Boltzmann factor and the $\\nu^4$ scattering law. (c) Compute this ratio at $T = 1500\\text{ K}$ and explain how Raman spectroscopy is used as an optical thermometer in combustion diagnostics."
with open("amp_u6.json", "w") as f:
    json.dump(d, f, indent=2)

print("Fixed all AMP worked problem statements.")

# --- BE UNITS 3 to 8 ---
with open("be_u3.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "An SCR is used in a half-wave phase-controlled rectifier circuit supplied from a $230\\text{ V}$ RMS, $50\\text{ Hz}$ sinusoidal source, feeding a resistive load of $R = 50\\ \\Omega$. The firing angle is set to $\\alpha = 60^\\circ$. (a) Derive and calculate the average DC load voltage $V_{\\text{dc}}$. (b) Calculate the average load current $I_{\\text{dc}}$ and total power delivered to the load. (c) Compute the circuit rectification efficiency."
d["problems"][1]["statement"] = "A UJT has an intrinsic standoff ratio $\\eta = 0.65$, interbase resistance $R_{BB} = 8\\text{ k}\\Omega$, and forward diode drop $V_D = 0.70\\text{ V}$. It is used in a relaxation oscillator with $V_{BB} = 15\\text{ V}$, charging resistor $R = 100\\text{ k}\\Omega$, and capacitor $C = 0.1\\ \\mu\\text{F}$. Assume valley voltage $V_V = 1.5\\text{ V}$. (a) Calculate the peak point firing voltage $V_P$. (b) Determine the oscillation frequency $f$ of the generated sawtooth waveform. (c) Check whether $R$ satisfies the firing condition $R_{\\text{min}} < R < R_{\\text{max}}$ if peak current $I_P = 2\\ \\mu\\text{A}$ and valley current $I_V = 3\\text{ mA}$."
d["problems"][2]["statement"] = "A single-phase full-wave controlled SCR bridge rectifier feeds a highly inductive load such that load current is continuous and ripple-free at $I_{dc} = 15\\text{ A}$. The AC supply is $230\\text{ V}$ RMS at $50\\text{ Hz}$. If the firing angle is $\\alpha = 45^\\circ$: (a) Calculate the average output DC voltage $V_{dc}$. (b) Calculate the active power delivered to the load. (c) Compute the input displacement factor and power factor of the converter."
with open("be_u3.json", "w") as f:
    json.dump(d, f, indent=2)

with open("be_u4.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "A Common Emitter BJT amplifier operates with a load resistance $R_L = 10\\text{ k}\\Omega$ and collector bias resistor $R_C = 4.7\\text{ k}\\Omega$. Transistor $h$-parameters are $h_{ie} = 2.0\\text{ k}\\Omega$, $h_{fe} = 100$, $h_{re} = 2.5 \\times 10^{-4}$, and $h_{oe} = 25\\ \\mu\\text{S}$. (a) Calculate the exact current gain $A_i = i_L / i_b$. (b) Calculate the input impedance $R_{\\text{in}}$ seen at the base terminal. (c) Determine the overall voltage gain $A_v = v_o / v_{\\text{in}}$ and output impedance $R_{\\text{out}}$."
d["problems"][1]["statement"] = "A two-stage RC-coupled BJT amplifier consists of identical Common Emitter stages. For each transistor, $h_{ie} = 1.5\\text{ k}\\Omega$, $h_{fe} = 80$, and $h_{oe} \\approx 0$. The collector resistors are $R_{C1} = R_{C2} = 3.3\\text{ k}\\Omega$, biasing resistors are $R_1 = 47\\text{ k}\\Omega$, $R_2 = 10\\text{ k}\\Omega$, and the load is $R_L = 4.7\\text{ k}\\Omega$. (a) Determine the effective AC load of the first stage $R_{L1}'$. (b) Calculate the individual voltage gains $A_{v1}$ and $A_{v2}$. (c) Compute the total overall voltage gain $A_v = A_{v1} \\times A_{v2}$ in decibels."
d["problems"][2]["statement"] = "A complementary-symmetry Class B push-pull amplifier operates from dual power supplies of $\\pm V_{CC} = \\pm 18\\text{ V}$ and drives an $8.0\\ \\Omega$ loudspeaker load. (a) Calculate the maximum unclipped output signal swing and maximum AC output power $P_{L,\\text{max}}$ (assuming ideal zero saturation voltage). (b) Determine the DC power supplied $P_{\\text{dc}}$ under maximum output conditions. (c) Calculate the conversion efficiency $\\eta$ and the maximum thermal power dissipation per transistor $P_{D,\\text{max}}$."
with open("be_u4.json", "w") as f:
    json.dump(d, f, indent=2)

with open("be_u5.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "An open-loop amplifier has a midband voltage gain of $A = 2000 \\pm 150$ (a 7.5% variation due to transistor manufacturing tolerances and temperature drift) and an upper cutoff frequency $f_H = 50\\text{ kHz}$. Negative voltage-series feedback is applied with feedback fraction $\\beta = 0.020$. (a) Calculate the closed-loop gain $A_f$. (b) Determine the percentage variation in closed-loop gain $\\Delta A_f / A_f$. (c) Compute the new closed-loop bandwidth $f_{Hf}$."
d["problems"][1]["statement"] = "A transistorized Colpitts oscillator operates with tank capacitors $C_1 = 0.001\\ \\mu\\text{F}$ and $C_2 = 0.01\\ \\mu\\text{F}$, and a tank inductor $L = 25\\ \\mu\\text{H}$. (a) Calculate the equivalent tank capacitance $C_{\\text{eq}}$. (b) Determine the fundamental oscillation frequency $f_0$. (c) Calculate the feedback factor $\\beta = C_1 / C_2$ and the minimum transistor voltage gain $A_v$ required to sustain oscillations according to the Barkhausen criterion."
d["problems"][2]["statement"] = "Design a Wien Bridge oscillator using an operational amplifier to generate a variable audio sine wave from $f_{\\text{min}} = 100\\text{ Hz}$ to $f_{\\text{max}} = 10\\text{ kHz}$ using a dual-gang variable resistor $R$ and fixed capacitors $C = 15\\text{ nF}$. (a) Determine the required range of resistance $R$. (b) Specify the feedback resistors $R_f$ and $R_1$ to ensure self-starting oscillations ($A_v \\ge 3$). (c) Explain why automatic gain control (e.g. tungsten lamp or JFET) is necessary in practical Wien bridge circuits."
with open("be_u5.json", "w") as f:
    json.dump(d, f, indent=2)

with open("be_u6.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "An AM broadcast transmitter radiates a total power of $P_t = 11.8\\text{ kW}$ when modulated by a single sinusoidal audio tone with a modulation index $m = 0.60$. (a) Calculate the unmodulated carrier power $P_c$. (b) Determine the total sideband power $P_{\\text{SB}}$ and the power in each individual sideband. (c) If the modulation depth increases to 100% ($m = 1.0$), calculate the new total radiated power and the percentage power efficiency of the transmitter."
d["problems"][1]["statement"] = "A commercial FM signal is given by the mathematical expression: $v(t) = 12 \\cos\\left( 2\\pi \\times 10^8 t + 6 \\sin(2\\pi \\times 10^4 t) \\right)\\text{ V}$. (a) Determine the carrier frequency $f_c$ in MHz and the modulating signal frequency $f_m$ in kHz. (b) Find the modulation index $\\beta$ and maximum frequency deviation $\\Delta f$. (c) Using Carson's rule, compute the transmission bandwidth required to pass 98% of the signal power."
d["problems"][2]["statement"] = "A standard AM broadcast superheterodyne receiver tunes across the medium wave band from $f_{s,\\text{min}} = 535\\text{ kHz}$ to $f_{s,\\text{max}} = 1605\\text{ kHz}$ using an intermediate frequency (IF) of $f_{\\text{IF}} = 455\\text{ kHz}$ with higher-side local oscillator injection ($f_{\\text{LO}} = f_s + f_{\\text{IF}}$). (a) Calculate the tuning range of the local oscillator $f_{\\text{LO}}$. (b) Determine the capacitance ratio $C_{\\text{max}} / C_{\\text{min}}$ of the variable tuning capacitor. (c) When tuned to a station at $700\\text{ kHz}$, determine the image frequency and the image rejection ratio in dB if the RF preselector circuit has a loaded quality factor $Q = 80$."
with open("be_u6.json", "w") as f:
    json.dump(d, f, indent=2)

with open("be_u7.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "Using standard op-amps operating with dual $\\pm 15\\text{ V}$ supplies and resistors in the range $10\\text{ k}\\Omega$ to $100\\text{ k}\\Omega$, design a summing amplifier circuit to produce an output voltage: $v_o = - (3 v_1 + 5 v_2 - 2 v_3)$. (a) Draw the schematic diagram using inverting amplifier stages. (b) Calculate the precise values for all resistors ($R_1, R_2, R_3, R_f$). (c) Determine the maximum allowable positive and negative excursions of input voltages before the output clips at $\\pm 13.5\\text{ V}$."
d["problems"][1]["statement"] = "A biomedical electrocardiogram (ECG) data acquisition system uses a 3-op-amp instrumentation amplifier with $R_1 = 25\\text{ k}\\Omega$, gain-setting resistor $R_G = 1.0\\text{ k}\\Omega$, and differential stage matched resistors $R_2 = R_3 = 50\\text{ k}\\Omega$. (a) Derive and calculate the differential voltage gain $A_d$. (b) If the input terminals receive a differential bio-potential signal $v_d = 2.0\\text{ mV}$ superimposed on a $50\\text{ Hz}$ power line common-mode noise voltage $v_{cm} = 2.0\\text{ V}$, calculate the output voltage if the op-amps have an intrinsic CMRR of $90\\text{ dB}$. (c) Explain why this instrumentation topology is superior to a single op-amp differential amplifier."
d["problems"][2]["statement"] = "A practical op-amp integrator has $R = 10\\text{ k}\\Omega$, $C = 0.01\\ \\mu\\text{F}$, and feedback stabilizing resistor $R_f = 100\\text{ k}\\Omega$. (a) Determine the lower cutoff 3-dB frequency $f_L$ below which integration degrades into inverting amplification. (b) Calculate the DC gain of the circuit. (c) If a square wave input of frequency $f = 10\\text{ kHz}$ and peak-to-peak amplitude $2.0\\text{ V}$ (zero DC offset) is applied, sketch the output waveform and compute its peak-to-peak amplitude."
with open("be_u7.json", "w") as f:
    json.dump(d, f, indent=2)

with open("be_u8.json", "r") as f:
    d = json.load(f)
d["problems"][0]["statement"] = "An operational amplifier has a specified slew rate of $SR = 2.0\\text{ V}/\\mu\\text{s}$. (a) If the op-amp is configured as a voltage follower and driven by a large-amplitude sine wave with peak voltage $V_m = 10.0\\text{ V}$, calculate the full-power bandwidth $f_{\\text{max}}$ before slew rate distortion occurs. (b) If the input frequency is increased to $100\\text{ kHz}$, calculate the maximum distortion-free output amplitude $V_{\\text{max}}$. (c) If a step input of $10.0\\text{ V}$ is applied, calculate the minimum rise time required for the output to transition between 10% and 90% of its final value."
d["problems"][1]["statement"] = "Design an inverting Schmitt trigger using an operational amplifier with supply rails of $\\pm 15\\text{ V}$ (assume saturation voltages $V_{\\text{sat}} = \\pm 13.5\\text{ V}$) to have an upper trip point $V_{\\text{UTP}} = +2.5\\text{ V}$ and a lower trip point $V_{\\text{LTP}} = -1.5\\text{ V}$. (a) Calculate the required reference voltage $V_{\\text{ref}}$ and the ratio of feedback resistors $R_1$ and $R_2$. (b) Choose standard $E24$ resistor values with $R_1 + R_2 \\approx 100\\text{ k}\\Omega$. (c) Compute the hysteresis width $V_H$ and sketch the input-output transfer characteristic."
d["problems"][2]["statement"] = "Design a second-order Sallen-Key low-pass filter with a maximally flat Butterworth response having a cutoff frequency $f_c = 1.0\\text{ kHz}$ and passband DC gain $A_v = 1.586$ (damping factor $\\zeta = 0.707$). Choose capacitors $C_1 = C_2 = 0.01\\ \\mu\\text{F}$. (a) Calculate the required filter resistances $R_1 = R_2 = R$. (b) Determine the gain-setting resistors $R_A$ and $R_B$ for the non-inverting op-amp configuration. (c) Calculate the attenuation of the filter at $f = 5.0\\text{ kHz}$ (in decibels) and verify its $-40\\text{ dB/decade}$ roll-off rate."
with open("be_u8.json", "w") as f:
    json.dump(d, f, indent=2)

print("Fixed all BE worked problem statements.")
